-- =============================================================================
-- LAYER  : Silver — Staging
-- MODEL  : fact_clm_seat_rate_stage
-- NOTES  : CLM seat rate staging; feeds fact_clm_seat_rate gold model
-- =============================================================================

{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('ffm') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the Pre Hook configuration #}
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT DATE_TRUNC(MONTH, DATEADD(MONTH,-16,CURRENT_DATE()))); ",
        "SET END_DATE   = (SELECT CURRENT_DATE()-1); "
    ]
  )
}}

{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_CJO_READONLY",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST"
    ]
  )
}}



WITH ASSIGNMENT_DAILY_DT AS
(
  SELECT DISTINCT DT
    , TENANT_ID
    , POOL_ID
    , SUBSCRIPTION_ID
    , CONTRACT_ID
    , ENTITLEMENT_ID
    , ENTITLEMENT_START_DATE
    , OXYGEN_ID_PA
    , DENSE_RANK() OVER (PARTITION BY TENANT_ID, POOL_ID, SUBSCRIPTION_ID, CONTRACT_ID, ENTITLEMENT_ID, OXYGEN_ID_PA ORDER BY DT) AS RN
  FROM {{ var('ASSIGNMENT_DAILY') }}
  WHERE ENTITLEMENT_START_DATE >= TO_DATE($START_DATE)
    AND ENTITLEMENT_END_DATE >= CURRENT_DATE
),

ASSIGNMENT_DAILY AS
(
  SELECT DISTINCT A.DT
    , A.TENANT_ID
    , A.POOL_ID
    , A.SUBSCRIPTION_ID
    , A.CONTRACT_ID
    , A.ENTITLEMENT_ID
    , A.ENTITLEMENT_START_DATE
    , A.OXYGEN_ID_PA
    , A.OFFERING_PRODUCT_LINE_CODE
    , COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.ACCOUNT_CSN) AS ACCOUNT_CSN
    , SUM(A.SEATS_PURCHASED) AS SEATS_PURCHASED
    , CASE
        WHEN SUM(A.SEATS_ASSIGNED) > SUM(A.SEATS_PURCHASED) THEN SUM(A.SEATS_PURCHASED)
        ELSE SUM(A.SEATS_ASSIGNED)
      END AS SEATS_ASSIGNED
    , B.RN
  FROM {{ var('ASSIGNMENT_DAILY') }} A
  LEFT JOIN ASSIGNMENT_DAILY_DT B
    ON A.DT = B.DT
    AND A.TENANT_ID = B.TENANT_ID
    AND A.POOL_ID = B.POOL_ID
    AND A.SUBSCRIPTION_ID = B.SUBSCRIPTION_ID
    AND A.CONTRACT_ID = B.CONTRACT_ID
    AND A.ENTITLEMENT_ID = B.ENTITLEMENT_ID
    AND A.ENTITLEMENT_START_DATE = B.ENTITLEMENT_START_DATE
    AND A.OXYGEN_ID_PA = B.OXYGEN_ID_PA
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE A.SEATS_PURCHASED <> 0
    AND A.ENTITLEMENT_START_DATE >= TO_DATE($START_DATE)
    AND A.ENTITLEMENT_END_DATE >= CURRENT_DATE
  GROUP BY ALL
),

USAGE_SUS_DAILY AS
(
  SELECT DISTINCT A.OXYGEN_ID
    , COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.ACCOUNT_CSN) AS ACCOUNT_CSN
    , A.CORPORATE_PARENT_ACCOUNT_CSN
    , A.TENANT_ID
    , A.POOL_ID
    , A.SUBSCRIPTION_ID
    , A.OFFERING_PRODUCT_LINE_CODE
    , A.USAGE_DATE
  FROM {{ var('USAGE_SUS_DAILY') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE A.USAGE_DATE BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE)
),

UTILIZATION_RATE AS
(
  SELECT USAGE_DATE
    , ACCOUNT_CSN
    , CORPORATE_PARENT_ACCOUNT_CSN
    , TENANT_ID
    , POOL_ID
    , SUBSCRIPTION_ID
    , OFFERING_PRODUCT_LINE_CODE
    , COUNT(DISTINCT OXYGEN_ID) AS USER_DETAILS
  FROM USAGE_SUS_DAILY
  GROUP BY ALL
),

PERSON AS
(
  SELECT DISTINCT PERSON_MDM_ID
    , OXYGEN_ID
  FROM {{ var('CORE_ENTERPRISE_DATA_SHARED.PERSON') }}
),

CONTACT_HISTORY AS
(
  SELECT DISTINCT CONTACT_UUID_CSN
    , JOURNEY_NAME
    , REGEXP_SUBSTR(SUBSTR(JOURNEY_NAME, 1, 7), '^[0-9]{7}$') AS TACTIC_ID
  FROM {{ var('CONTACT_HISTORY') }}
  WHERE TRY_TO_NUMBER(SUBSTRING(JOURNEY_NAME, 1, 7)) = TRUE
),

EDH_FINANCE AS
(
  SELECT DISTINCT COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.CORPORATE_CSN) AS CORPORATE_CSN
    , A.SAP_PRODUCT_LINE
    , A.CC_FBD_BSM_ORDER_ACTION
    , ROW_NUMBER() OVER(PARTITION BY COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.CORPORATE_CSN), A.SAP_PRODUCT_LINE ORDER BY A.TRANSACTION_DT DESC NULLS LAST) RNK
  FROM {{ var('FINMART_PRIVATE_DATA') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.CORPORATE_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.CORPORATE_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE UPPER(A.RECORD_TYPE) IN ('BILLING', 'BOOKING_BILLING')
    AND UPPER(A.CC_FBD_BIL_TERM_DAYS) <> 'NA'
    AND NOT (UPPER(A.SALES_ORDER_REASON) LIKE '%TEST ORDER%' OR UPPER(A.SALES_ORDER_REASON) LIKE '%TRIAL%')
    AND NOT (UPPER(A.PO_NBR) LIKE '%TEST%')
    AND (A.SETTLEMENT_END_DT >= CAST(A.TRANSACTION_DT AS DATE))
    AND A.CC_ACTIVE_END_DT >= A.TRANSACTION_DT
    AND A.TRANSACTION_DT >= TO_DATE($START_DATE)
  QUALIFY RNK = 1
),

CUSTOMER_PHASES AS
(
  SELECT DISTINCT PARENT_CSN
    , CUSTOMER_PHASE_START_DATE
    , CUSTOMER_PHASE_END_DATE
    , CUSTOMER_PHASE
  FROM {{ var('CUSTOMER_PHASES') }}
  WHERE CUSTOMER_PHASE_END_DATE >= CURRENT_DATE()
),

CMT_CAMPAIGN AS
(
  SELECT DISTINCT ALLOCADIA_ID__C AS ALLOCADIA_ID
    , MARKETING_EXECUTION_TEAM__C AS MARKETING_EXECUTION_TEAM
    , NAME AS CMT_CAMPAIGN_NAME 
  FROM {{ var('SFDC_SHARED.CAMPAIGN') }}
  WHERE MARKETING_EXECUTION_TEAM__C ='AGM-ILM'
),

TEST_CONTROL AS
(
  SELECT DISTINCT COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.ACCOUNT_CSN__C) AS ACCOUNT_CSN__C
    , SEMI_RANDOM_DIGIT
  FROM {{ var('ILM_ACCOUNTS') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN__C = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN__C = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE SEMI_RANDOM_DIGIT= 1
)

SELECT DISTINCT A.DT
  , A.ACCOUNT_CSN AS ACCOUNT_CSN
  , C.PARENT_ACCOUNT_CSN AS CORPORATE_PARENT_ACCOUNT_CSN
  , A.OXYGEN_ID_PA
  , A.TENANT_ID
  , A.POOL_ID
  , A.SUBSCRIPTION_ID
  , A.CONTRACT_ID
  , A.ENTITLEMENT_ID
  , A.ENTITLEMENT_START_DATE
  , A.OFFERING_PRODUCT_LINE_CODE
  , E.CC_FBD_BSM_ORDER_ACTION AS SEAT_TYPE
  , F.CUSTOMER_PHASE
  , CMT.CMT_CAMPAIGN_NAME
  , CMT.MARKETING_EXECUTION_TEAM
  , CASE WHEN TC.ACCOUNT_CSN__C IS NOT NULL THEN 'Control' ELSE 'Test' END AS TEST_CONTROL_FLAG
  
  , COALESCE(A.SEATS_PURCHASED, 0) AS SEATS_PURCHASED
  , COALESCE(A.SEATS_ASSIGNED, 0) AS SEATS_ASSIGNED
  , COALESCE(UTL.USER_DETAILS, 0) AS USAGE_DETAILS
  , A.RN AS DAYS_BUCKET
  , SYSDATE() AS DBT_LOAD_DATETIME
FROM ASSIGNMENT_DAILY A
LEFT JOIN {{ ref('DIM_CLM_ACCOUNT_ATTRIBUTIONS') }} C
  ON A.ACCOUNT_CSN = C.ACCOUNT_CSN
LEFT JOIN EDH_FINANCE E
  ON A.ACCOUNT_CSN = E.CORPORATE_CSN
  AND REPLACE(A.POOL_ID, '1_','') = UPPER(E.SAP_PRODUCT_LINE)
LEFT JOIN CUSTOMER_PHASES F
  ON C.PARENT_ACCOUNT_CSN  = F.PARENT_CSN
  AND A.ENTITLEMENT_START_DATE BETWEEN F.CUSTOMER_PHASE_START_DATE AND F.CUSTOMER_PHASE_END_DATE
LEFT JOIN PERSON B
  ON A.OXYGEN_ID_PA = B.OXYGEN_ID
LEFT JOIN CONTACT_HISTORY UCH
  ON B.PERSON_MDM_ID = UCH.CONTACT_UUID_CSN
LEFT JOIN CMT_CAMPAIGN CMT
  ON UCH.TACTIC_ID = CMT.ALLOCADIA_ID
LEFT JOIN UTILIZATION_RATE UTL
  ON A.DT = UTL.USAGE_DATE
  AND A.ACCOUNT_CSN = UTL.ACCOUNT_CSN
  AND C.PARENT_ACCOUNT_CSN = UTL.CORPORATE_PARENT_ACCOUNT_CSN
  AND A.TENANT_ID = UTL.TENANT_ID
  AND A.POOL_ID = UTL.POOL_ID
  AND A.SUBSCRIPTION_ID = UTL.SUBSCRIPTION_ID
  AND A.OFFERING_PRODUCT_LINE_CODE = UTL.OFFERING_PRODUCT_LINE_CODE
LEFT JOIN TEST_CONTROL TC
  ON A.ACCOUNT_CSN = TC.ACCOUNT_CSN__C

WHERE A.RN % 15=0
AND CMT.CMT_CAMPAIGN_NAME != '6836613_Cross-Ind_KPI_reporting_data_test'
AND A.OFFERING_PRODUCT_LINE_CODE NOT IN ('BIMCOLL', 'BLDUNLT', 'B36FP', 'QNTFY', 'ATOSPCS', 'BIM360C', 'BLD550', 'BM36PP', 'BM36DP', 'DOCS', 'COLLRP', 'BLD5K')

