-- =============================================================================
-- LAYER  : Silver — Staging
-- MODEL  : FFM_TRIAL_ORDER_CONVERSION_STAGE (CLM / FFM pipeline stage)
-- NOTES  : Intermediate staging model; feeds gold fact tables
-- =============================================================================
{% set db_properties=get_dbproperties('fullfunnel') %}

{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Set the right tag
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

WITH DATE_DETAILS AS
(
    SELECT
    DATE_KEY
    , WEEK_NUMBER_FISCAL_QUARTER FYWEEK
    , MONTH_NUMBER_IN_FISCAL_YEAR FYMONTH
    , FISCAL_YEAR_AND_FISCAL_QUARTER_NAME FYQUARTER
    , FISCAL_YEAR_NAME FYYEAR
    FROM {{ ref('FFM_FIN_CALENDAR') }}
   WHERE DATE_KEY >='2021-01-31'
),
FINMART_DEC AS
(
      SELECT
        ECC_SALES_ORDER_NBR,
        CC_FBM_TOTAL_ACV_NET3_CC,
        CASE
            WHEN PELICAN_SUBSCRIPTION_ID = '963769' AND  CORPORATE_CSN<> '5138666375' then SUBSCRIPTION_ID
            WHEN PELICAN_SUBSCRIPTION_ID = '*' THEN SUBSCRIPTION_ID
            ELSE PELICAN_SUBSCRIPTION_ID
        END AS COMBINED_SUBSCRIPTION_ID,
        CASE
            WHEN FIN.OXYGEN_ID = '*' AND H.OXYGEN_ID__C IS NULL THEN I.OWNEREXTERNALKEY
            WHEN FIN.OXYGEN_ID = '*' AND H.OXYGEN_ID__C IS NOT NULL THEN H.OXYGEN_ID__C
        ELSE FIN.OXYGEN_ID END AS OXYGEN_ID,
        CASE
            WHEN CORPORATE_PARENT_ACCOUNT_CSN   <> 'UNKNOWN' THEN CORPORATE_PARENT_ACCOUNT_CSN
            WHEN CORPORATE_PARENT_ACCOUNT_CSN  = 'UNKNOWN' THEN CORPORATE_CSN
       END  AS ACCOUNT_CSN,
        CASE WHEN CORPORATE_NAMED_ACCOUNT_GROUP_NM <>'*' THEN CORPORATE_NAMED_ACCOUNT_GROUP_NM END CORPORATE_NAMED_ACCOUNT_GROUP_NM,
        CASE WHEN SAP_PRODUCT_LINE <>'*' THEN SAP_PRODUCT_LINE END SAP_PRODUCT_LINE,
        CASE
            WHEN UPPER(CC_FBD_SF_WWS_GEO) LIKE 'APAC%' THEN 'APAC'
            WHEN CC_FBD_SF_WWS_GEO <>'Corp' THEN UPPER(CC_FBD_SF_WWS_GEO)
            ELSE UPPER(CC_FBD_SF_WWS_GEO)
        END AS  GEO,        -- Rename APAC excl. Japan to APAC
        CORPORATE_COUNTRY_NM AS  COUNTRY,
        CORPORATE_COUNTRY_CD AS CORPORATE_COUNTRY_CD,
        CC_FBD_SF_BIL_TERM_SETL AS TERM,
        CC_FBD_BSM_SALES_CH AS SALES_CHANNEL,
        CC_FBD_SF_FOX_RENEWAL_IND,
        FIN.PRODUCT_CLASS,
        TRANSACTION_DT AS ORDER_DT
     FROM {{ var('FINMART_PRIVATE_DATA') }} FIN
     LEFT JOIN
     (
        SELECT DISTINCT * FROM (
            SELECT F.*,G.* FROM (SELECT DISTINCT ORDERNUMBER__C,CONTACT__C FROM BSD_PUBLISH.SFDC_SHARED.ORDER__C) F
                            INNER JOIN (SELECT DISTINCT OXYGEN_ID__C,ID FROM {{ var('CONTACT') }}) G
                             ON F.CONTACT__C = G.ID )
     ) H ON FIN.ECC_SALES_ORDER_NBR = H.ORDERNUMBER__C
     LEFT JOIN
            (SELECT DISTINCT OWNEREXTERNALKEY, TO_VARCHAR (ID) AS ID
                FROM ADP_PUBLISH.ENTITLEMENT_PUBLIC.SUBSCRIPTION_PELICAN
            ) I
     ON I.ID = COMBINED_SUBSCRIPTION_ID
  WHERE
  UPPER(RECORD_TYPE) IN ('BILLING', 'BOOKING_BILLING') AND TRANSACTION_DT>='2021-01-01'

),
FINMART_DATA AS
(
    SELECT * FROM FINMART_DEC
    WHERE CC_FBD_SF_FOX_RENEWAL_IND ='New' AND OXYGEN_ID IS NOT NULL
    AND CC_FBM_TOTAL_ACV_NET3_CC > 0

),

TRIAL_ACTIVATIONS AS
(
    SELECT ACTIVATION_OXYGEN_ID,
    TRAIL_DOWNLOAD_OXYGEN_ID,
    ACTIVATION_DATE,
    ENTITLEMENT_START_DATE,
    PRODUCT_LINE_CODE,
    SUB_ID_DOWNLOAD,
    OFFERING_PRODUCT_LINE_CODE,
    PRODUCTLINE_NAME,
    IS_VALID_DOWNLOAD,
    IS_VALID_ACTIVATION
    FROM {{ ref('FFM_TRIALS_STAGE') }}

),
TRIAL_CONVERSION AS
(
   SELECT
        FIN.ECC_SALES_ORDER_NBR,
        FIN.OXYGEN_ID,
        TRI.OFFERING_PRODUCT_LINE_CODE,
        FIN.ORDER_DT AS ORDER_DT,
        TRI.ACTIVATION_DATE AS ACTIVATION_DATE,
        TRI.ENTITLEMENT_START_DATE,
        PRODUCTLINE_NAME AS TRIALS_PRODUCTLINE_NAME,
        SUB_ID_DOWNLOAD,
         CASE
            WHEN TRI.OFFERING_PRODUCT_LINE_CODE = FIN.SAP_PRODUCT_LINE THEN 1 --SAP_PRODUCT_LINE
            WHEN LEFT(TRI.OFFERING_PRODUCT_LINE_CODE, 3 ) = LEFT (FIN.SAP_PRODUCT_LINE , 3) THEN 2
            WHEN UPPER(TRI.PRODUCTLINE_NAME) LIKE '%AUTOCAD%' AND UPPER(FIN.PRODUCT_CLASS) LIKE '%AUTOCAD%'THEN 2
            WHEN UPPER(TRI.PRODUCTLINE_NAME) LIKE '%BIM%COLLAB%' AND UPPER(FIN.PRODUCT_CLASS) LIKE '%BIM%COLLAB%'THEN 2
            WHEN UPPER(TRI.PRODUCTLINE_NAME) LIKE '%FUSION%' AND UPPER(FIN.PRODUCT_CLASS) LIKE '%FUSION%'THEN 2
            WHEN UPPER(FIN.PRODUCT_CLASS) LIKE '%COLLECTION%'THEN 3
        ELSE 4
        END AS TRIAL_ORDER_MATCH
        FROM FINMART_DATA FIN
        INNER JOIN TRIAL_ACTIVATIONS TRI
        ON FIN.OXYGEN_ID = TRI.TRAIL_DOWNLOAD_OXYGEN_ID
        AND FIN.ORDER_DT >= TRI.ACTIVATION_DATE
        AND FIN.ORDER_DT<= TRI.ENTITLEMENT_START_DATE +90
        GROUP BY ALL

),
GET_MIN_TRIAL_ORDER_MATCH AS
(
    SELECT ECC_SALES_ORDER_NBR,OXYGEN_ID,OFFERING_PRODUCT_LINE_CODE,ORDER_DT,
    ACTIVATION_DATE,ENTITLEMENT_START_DATE,TRIALS_PRODUCTLINE_NAME,
    SUB_ID_DOWNLOAD,min(TRIAL_ORDER_MATCH) AS TRIAL_ORDER_MATCH
    FROM TRIAL_CONVERSION
    GROUP BY ALL
),
GET_CONVERTED_FLAG AS
(
        SELECT G.*,DENSE_RANK() OVER (PARTITION BY  ECC_SALES_ORDER_NBR,
                                         ORDER_DT,
                                         OXYGEN_ID
                           ORDER BY      TRIAL_ORDER_MATCH ASC,
                                         ACTIVATION_DATE DESC,
                                         SUB_ID_DOWNLOAD DESC ) AS TRIALS_BEFORE_ORDER_RANK,

                                         CASE
                                            WHEN TRIALS_BEFORE_ORDER_RANK = 1 THEN TRUE
                                            ELSE FALSE
                                          END AS TRIAL_CONVERTED_FLAG
                                         FROM GET_MIN_TRIAL_ORDER_MATCH G

),
GET_ACV_N_ORDERS AS
(
    SELECT FLG.ECC_SALES_ORDER_NBR AS ECC_SALES_ORDER_NBR,
    FIN.CC_FBM_TOTAL_ACV_NET3_CC AS CC_FBM_TOTAL_ACV_NET3_CC,
    FLG.OXYGEN_ID AS OXYGEN_ID,

    FLG.OFFERING_PRODUCT_LINE_CODE AS OFFERING_PRODUCT_LINE_CODE,
    FLG.TRIALS_PRODUCTLINE_NAME AS TRIALS_PRODUCTLINE_NAME,
    PROD.PRODUCT AS PRODUCT,
    PROD.PRODUCT_FAMILY AS PRODUCT_FAMILY,
    PROD.PRODUCT_INDUSTRY AS PRODUCT_INDUSTRY,
    FIN.SAP_PRODUCT_LINE AS ORDERED_PRODUCT_CODE,

    FLG.ORDER_DT AS ORDER_DT,
    FLG.ACTIVATION_DATE AS ACTIVATION_DATE,
    FLG.ENTITLEMENT_START_DATE AS ENTITLEMENT_START_DATE,

    FLG.TRIALS_BEFORE_ORDER_RANK AS TRIALS_BEFORE_ORDER_RANK,
    FLG.TRIAL_CONVERTED_FLAG AS TRIAL_CONVERTED_FLAG,


    FIN.ACCOUNT_CSN AS ACCOUNT_CSN,
    FIN.CORPORATE_NAMED_ACCOUNT_GROUP_NM AS BUSINESS_TIER,
    FIN.GEO AS GEO,
    FIN.COUNTRY AS COUNTRY,
    COALESCE(LKUP.GDPR_FLAG, 'NON-GDPR') AS GDPR_FLAG,

    FIN.TERM AS TERM,
    FIN.SALES_CHANNEL AS SALES_CHANNEL,

    DT.FYWEEK,
    DT.FYMONTH,
    DT.FYYEAR,
    DT.FYQUARTER

  --  FIN.CORPORATE_COUNTRY_CD,
     FROM GET_CONVERTED_FLAG FLG
     LEFT JOIN FINMART_DATA FIN
        ON FLG.ECC_SALES_ORDER_NBR = FIN.ECC_SALES_ORDER_NBR
        AND FLG.ORDER_DT = FIN.ORDER_DT
     LEFT JOIN {{ ref('LOOKUP_MPM_PRODUCT_CODE_TO_PRODUCT') }}  PROD
         ON FIN.SAP_PRODUCT_LINE = PROD.CODE
     LEFT JOIN DATE_DETAILS DT
         ON FLG.ORDER_DT = DT.DATE_KEY

     LEFT JOIN {{ ref('DIM_FFM_COUNTRY_VW') }}  LKUP
        ON UPPER (FIN.CORPORATE_COUNTRY_CD) = UPPER(LKUP.COUNTRY_SEARCH_CODE)


)
SELECT * FROM GET_ACV_N_ORDERS

