-- =============================================================================
-- LAYER  : Silver — Staging
-- MODEL  : FFM_CUSTOMERS_STAGE (CLM / FFM pipeline stage)
-- NOTES  : Intermediate staging model; feeds gold fact tables
-- =============================================================================
/* This model serves as base table to derive New Customers
   Logic of Survivor account CSN is referenced from DEC team.
*/
{% set db_properties=get_dbproperties('fullfunnel') %}

{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Set the right tag
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{{
  config(
    pre_hook = [
        "SET START_DATE = (select CALENDAR_DATE from ADP_PUBLISH.COMMON_REFERENCE_DATA_OPTIMIZED.DATE_TIME_HIERARCHY where FISCAL_QUARTER_VS_CURRENT_NUMBER = -13 and FISCAL_QUARTER_DAY_NUMBER = 1); " ,
        "SET END_DATE   = (SELECT CURRENT_DATE()-1);"
    ]
  )
}}

-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

WITH DATE_DETAILS AS (
    SELECT
        DATE_KEY,
        WEEK_START_DATE,
        WEEK_NUMBER_FISCAL_QUARTER FYWEEK,
        MONTH_NUMBER_IN_FISCAL_YEAR FYMONTH,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME FYQUARTER,
        FISCAL_YEAR_NAME FYYEAR
    FROM
        {{ ref('LOOKUP_FINANCE_CALENDAR') }}
    WHERE
       DATE_KEY BETWEEN $START_DATE AND $END_DATE
),
CUSTOMER_PHASE AS (
    SELECT
        DISTINCT CUST.PARENT_CSN,
        CUST.CUSTOMER_PHASE,
        CUST.CUSTOMER_PHASE_END_DATE,
        CUST.CUSTOMER_PHASE_START_DATE,
        CONCAT('FY', SUBSTR(CUST.START_FISCAL_YEAR_QUARTER, 3)) AS START_FISCAL_YEAR_QUARTER,
        ACC.INDUSTRY_SEGMENT__C AS ACC_INDUSTRY_SEGMENT,
        ACC.NAMED_ACCOUNT_GROUP__C AS ACC_NAG,
        LKUP.GEO AS ACC_GEO,
        LKUP.COUNTRY AS ACC_COUNTRY,
        COALESCE(LKUP.GDPR_FLAG, 'NON-GDPR') AS ACC_GDPR_FLAG, -- Added GDPR Flag from Country Lookup
        NAG.NAG_ACCOUNT_TYPE AS ACC_ABSM_FLAG
    FROM
        {{ var('CUSTOMER_PHASES') }} CUST
        LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} ACC ON CUST.PARENT_CSN = ACC.ACCOUNT_CSN__C
        LEFT JOIN {{ ref('DIM_FFM_COUNTRY_VW') }} LKUP ON UPPER (ACC.COUNTRY_PICKLIST__C) = UPPER(LKUP.COUNTRY_SEARCH_CODE)
        LEFT JOIN {{ var('NAG_MAPPING') }} AS NAG ON UPPER (ACC.NAMED_ACCOUNT_GROUP__C) = UPPER (NAG.NAMED_ACCOUNT_GROUP)
    WHERE CUST.CUSTOMER_PHASE_START_DATE BETWEEN $START_DATE AND $END_DATE
),

FINMART_SURVIVOR_COMBINED AS
(
    SELECT * FROM {{ ref('FFM_TOTAL_ACV_STAGE') }} WHERE SETTLEMENT_START_DT BETWEEN $START_DATE AND $END_DATE
)

SELECT
    DT.FYYEAR,
    DT.FYQUARTER,
    DT.FYMONTH,
    DT.FYWEEK,
    DT.WEEK_START_DATE,
    COMB_CSN.SRC_ID,
    COMB_CSN.TRANSACTION_DT,
    COMB_CSN.SETTLEMENT_START_DT,
    COMB_CSN.SETTLEMENT_END_DT,
    COMB_CSN.SETTLEMENT_START_FY_AND_FQ_NAME,
    COMB_CSN.CONTRCT_START_DT,
    COMB_CSN.CONTRCT_END_DT,
    COMB_CSN.CC_FBM_TOTAL_ACV_NET3_CC,
    COMB_CSN.ACS_NEW_ACV,
    COMB_CSN.ACS_EXPANSION_ACV,
    COMB_CSN.ACS_RENEW_ACV,
    COMB_CSN.ACS_INSTALLMENT_ACV,
    COMB_CSN.ACV_SOURCE,
    COMB_CSN.CORPORATE_PARENT_ACCOUNT_CSN,
    COMB_CSN.CORPORATE_CSN,
    COMB_CSN.CORPORATE_NAMED_ACCOUNT_GROUP_NM,
    COMB_CSN.CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM,
    COMB_CSN.CORPORATE_COUNTRY_NM,
    COMB_CSN.CORPORATE_COUNTRY_CD,
    COMB_CSN.CORPORATE_PARENT_COUNTRY_CD,
    COMB_CSN.CORPORATE_PARENT_COUNTRY_NM,
    COMB_CSN.CORPORATE_PARENT_GEO_CD,
    COMB_CSN.CC_FBD_SF_WWS_GEO,
    COMB_CSN.CC_FBD_BSM_ESTORE_ORDER_ORIGIN,
    COMB_CSN.ORIGIN_SEGMENT,
    COMB_CSN.CORPORATE_HIER_INDUSTRY_SEGMENT_NM,
    COMB_CSN.CC_FBD_BSM_SALES_CH,
    COMB_CSN.CC_FBD_SF_BIL_TERM_SETL,
    COMB_CSN.SAP_PRODUCT_LINE,
    COMB_CSN.PRODUCT_CLASS,
    COMB_CSN.PRODUCT,
    COMB_CSN.PRODUCT_FAMILY,
    COMB_CSN.PRODUCT_INDUSTRY,
    COMB_CSN.GDPR_FLAG AS FIN_GDPR_FLAG,
    COMB_CSN.ABSM_FLAG AS FIN_ABSM_FLAG,
    COMB_CSN.FINAL_CSN AS FIN_FINAL_SURVIVOR_CSN,
    COMB_CSN.PARENT_SURVIVOR_CORPORATE_CSN,
    COMB_CSN.PARENT_SURVIVING_PARENTACCOUNT_CSN,
    --COMB_CSN.CORPORATE_PARENT_CSN_STATIC,
    --COMB_CSN.SURVIVING_ACCOUNT_CSN,
    --COMB_CSN.SURVIVOR_CSN,
    CUST.PARENT_CSN AS CUSTOMER_PARENT_CSN,
    CUST.CUSTOMER_PHASE,
    CUST.CUSTOMER_PHASE_START_DATE,
    CUST.CUSTOMER_PHASE_END_DATE,
    CUST.START_FISCAL_YEAR_QUARTER,
    CUST.ACC_INDUSTRY_SEGMENT,
    CUST.ACC_NAG AS CUSTOMER_NAG,
    CUST.ACC_COUNTRY AS CUSTOMER_COUNTRY,
    CUST.ACC_GEO AS CUSTOMER_GEO,
    CUST.ACC_ABSM_FLAG AS CUSTOMER_ABSM_FLAG,
    CUST.ACC_GDPR_FLAG AS CUSTOMER_GDPR_FLAG,
    CASE WHEN
        UPPER(COALESCE(COMB_CSN.CORPORATE_HIER_INDUSTRY_SEGMENT_NM, CUST.ACC_INDUSTRY_SEGMENT)) NOT IN  ('*' ,'UNKNOWN')
        THEN COALESCE(COMB_CSN.CORPORATE_HIER_INDUSTRY_SEGMENT_NM, CUST.ACC_INDUSTRY_SEGMENT)
    END AS CUSTOMER_SEGMENT,
    CASE WHEN
        UPPER(COALESCE(COMB_CSN.CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM, CUST.ACC_NAG)) NOT IN  ('*' ,'UNKNOWN')
        THEN COALESCE(COMB_CSN.CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM, CUST.ACC_NAG)
    END AS NAG,
    COALESCE(COMB_CSN.PARENT_GEO, CUST.ACC_GEO) AS GEO,
    COALESCE(COMB_CSN.CORPORATE_PARENT_COUNTRY_NM, CUST.ACC_COUNTRY) AS COUNTRY,
    COALESCE(COMB_CSN.GDPR_FLAG, CUST.ACC_GDPR_FLAG) AS GDPR_FLAG,
    COALESCE(COMB_CSN.ABSM_FLAG, CUST.ACC_ABSM_FLAG) AS ABSM_FLAG,
    COMB_CSN.ALLOCADIA_ID,
    COMB_CSN.CAMPAIGN_INDUSTRY,
    COMB_CSN.CHILD_CAMPAIGN_NAME,
    COMB_CSN.PARENT_CAMPAIGN_NAME,
    COMB_CSN.TACTIC_OWNER,
    COMB_CSN.EVT_CHANNEL,
    COMB_CSN.CHANNEL_TYPE,
    COMB_CSN.REF_URL,
    COMB_CSN.BIC_ORDER_NBR,
    COMB_CSN.PO_NBR,
    CURRENT_TIMESTAMP AS RUN_TIMESTAMP
FROM CUSTOMER_PHASE CUST
LEFT JOIN FINMART_SURVIVOR_COMBINED  COMB_CSN 
    ON COMB_CSN.FINAL_CSN = CUST.PARENT_CSN
    AND COMB_CSN.SETTLEMENT_START_DT >= CUST.CUSTOMER_PHASE_START_DATE
    AND COMB_CSN.SETTLEMENT_START_DT <= CUST.CUSTOMER_PHASE_END_DATE
LEFT JOIN DATE_DETAILS DT
    ON CUST.CUSTOMER_PHASE_START_DATE = DT.DATE_KEY