-- =============================================================================
-- LAYER  : Silver — Staging
-- MODEL  : FFM_NEW_CONTACTS_STAGE (CLM / FFM pipeline stage)
-- NOTES  : Intermediate staging model; feeds gold fact tables
-- =============================================================================
{% set db_properties=get_dbproperties('fullfunnel') %}

{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Set the right tag
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

-- Set the configuration
{{
    config(
        materialized='table'
    )
}}

--Truncate table and reload data on each run
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT CALENDAR_DATE FROM ADP_PUBLISH.COMMON_REFERENCE_DATA_OPTIMIZED.DATE_TIME_HIERARCHY WHERE FISCAL_QUARTER_VS_CURRENT_NUMBER=-6 AND  FISCAL_QUARTER_DAY_NUMBER=1);" ,
        "SET END_DATE   = (SELECT CURRENT_DATE()-1);"
    ]
  )
}}
-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

WITH MARKETABLE_DATA AS
(
    SELECT DISTINCT
    SFDC_ACCOUNT_ID
    ,ACCOUNT_CSN
    ,CORE_MARKETABILITY_SOURCE
    ,MARKETO_LEAD_ID
    ,SFDC_CONTACT_ID
    ,DATE(CONTACT_CREATED_DATE) CONTACT_CREATED_DATE
    ,GEO
    ,COUNTRY
    ,REPORTABLE
    ,AC_INDUSTRY_SEGMENT
    ,SIC_INDUSTRY_SEGMENT
    ,AC_AUDIENCE
    ,END_USER_PERSONA
    ,ACCOUNT_ADMIN_PERSONA
    ,EXECUTIVE_PERSONA
    ,VERY_SMALL_BUSINESS_PERSONA
    ,SOLUTION_BUYER_PERSONA
    ,ABSM_FLAG
    FROM {{ var('MARKETABILITY') }}
    WHERE DATE(CONTACT_CREATED_DATE) between $START_DATE and $END_DATE
),

ACCOUNT_DETAILS AS
(
    SELECT DISTINCT
    ACC.SFDC_ACCOUNT_ID
    ,ACC.ACCOUNT_CSN
    ,ACC.CORPORATE_PARENT_ACCOUNT_CSN AS PARENT_ACCOUNT_CSN
    ,ACC.CREATED_DATE AS ACCOUNT_CREATED_DATE
    ,NAG.NAG_ACCOUNT_TYPE AS ABSM_FLAG
    FROM {{ var('ACCOUNTS_WITH_CORPORATE_PARENTS') }}  ACC
    LEFT JOIN {{ var('NAG_MAPPING') }}  NAG
    ON (UPPER (ACC.NAMED_ACCOUNT_GROUP) = UPPER (NAG.NAMED_ACCOUNT_GROUP))
),

CUSTOMER_PHASE AS
(
    SELECT DISTINCT
    PARENT_CSN
    ,CUSTOMER_PHASE
    ,CUSTOMER_PHASE_END_DATE
    ,CUSTOMER_PHASE_START_DATE
    FROM {{ var('CUSTOMER_PHASES') }}
)

SELECT DISTINCT
    MAR.CORE_MARKETABILITY_SOURCE
    ,MAR.MARKETO_LEAD_ID
    ,MAR.SFDC_CONTACT_ID
    ,MAR.CONTACT_CREATED_DATE
    ,LKUP.MKT_REPORTING_GEO GEO
    ,MAR.AC_INDUSTRY_SEGMENT
    ,MAR.SIC_INDUSTRY_SEGMENT
    ,MAR.AC_AUDIENCE
    ,MAR.END_USER_PERSONA
    ,MAR.ACCOUNT_ADMIN_PERSONA
    ,MAR.EXECUTIVE_PERSONA
    ,MAR.VERY_SMALL_BUSINESS_PERSONA
    ,MAR.SOLUTION_BUYER_PERSONA
    ,MAR.REPORTABLE
    ,COALESCE(MAR.ABSM_FLAG,ACC_ID.ABSM_FLAG, ACC_CSN.ABSM_FLAG) AS ABSM_FLAG
    ,COALESCE(ACC_ID.SFDC_ACCOUNT_ID, ACC_CSN.SFDC_ACCOUNT_ID) AS SFDC_ACCOUNT_ID
    ,COALESCE(ACC_ID.PARENT_ACCOUNT_CSN, ACC_CSN.PARENT_ACCOUNT_CSN) AS PARENT_ACCOUNT_CSN
    ,COALESCE(ACC_ID.ACCOUNT_CSN, ACC_CSN.ACCOUNT_CSN) AS ACCOUNT_CSN
    ,COALESCE(ACC_ID.ACCOUNT_CREATED_DATE,ACC_CSN.ACCOUNT_CREATED_DATE) AS ACCOUNT_CREATED_DATE
    ,CUST.CUSTOMER_PHASE
    ,DT.WEEK_NUMBER_FISCAL_QUARTER AS FYWEEK
    ,DT.MONTH_NUMBER_IN_FISCAL_YEAR AS FYMONTH
    ,DT.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FYQUARTER
    ,DT.FISCAL_YEAR_NAME AS FYYEAR
FROM MARKETABLE_DATA MAR
LEFT JOIN ACCOUNT_DETAILS ACC_ID
    ON MAR.SFDC_ACCOUNT_ID=ACC_ID.SFDC_ACCOUNT_ID
LEFT JOIN ACCOUNT_DETAILS ACC_CSN
    ON MAR.ACCOUNT_CSN=ACC_CSN.ACCOUNT_CSN
LEFT JOIN {{ ref('LOOKUP_COUNTRY_MAPPING') }} LKUP
    ON UPPER (MAR.COUNTRY) = UPPER(LKUP.FUZZY_SEARCH_CODE)
LEFT JOIN CUSTOMER_PHASE CUST
    ON CUST.PARENT_CSN=COALESCE(ACC_ID.PARENT_ACCOUNT_CSN, ACC_CSN.PARENT_ACCOUNT_CSN)
    AND DATE(MAR.CONTACT_CREATED_DATE) BETWEEN  CUST.CUSTOMER_PHASE_START_DATE AND CUST.CUSTOMER_PHASE_END_DATE
LEFT JOIN {{ var('FINANCE_CALENDAR') }}  DT
        ON DATE(MAR.CONTACT_CREATED_DATE)=DT.DATE_KEY

