-- =============================================================================
-- LAYER  : Silver — Staging
-- MODEL  : FFM_TOTAL_ACV_STAGE (CLM / FFM pipeline stage)
-- NOTES  : Intermediate staging model; feeds gold fact tables
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}
{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

-- Set the start and end dates 
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT CALENDAR_DATE FROM ADP_PUBLISH.COMMON_REFERENCE_DATA_OPTIMIZED.DATE_TIME_HIERARCHY WHERE FISCAL_QUARTER_VS_CURRENT_NUMBER=-13 AND  FISCAL_QUARTER_DAY_NUMBER=1);" ,
        "SET END_DATE   = (SELECT CURRENT_DATE()-1);"
    ]
  )
}}


-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

WITH WEEK_CALENDAR AS (
    SELECT DISTINCT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        WEEK_NUMBER_FISCAL_QUARTER,
        WEEK_START_DATE,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER
    FROM
        {{ ref('LOOKUP_FINANCE_CALENDAR') }}
    WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -12 AND DATE_KEY < CURRENT_DATE
),
-- Logic for extraction of CAMPAIGN_INDUSTRY from MPM ----
ALLOCADIA AS (
    SELECT
        DISTINCT LINE_ITEM_ID, CAMPAIGN_INDUSTRY, CHILD_CAMPAIGN_NAME, PARENT_CAMPAIGN_NAME, TACTIC_OWNER
    FROM
        {{ var('ALLOCADIA_LINEITEM_MASTER') }}
    WHERE
        ACTIVE_TO_DATE IS NULL
),
--Get all Order ID to Tactic Mapping with non null Campaign Industry
USTACK_DATA AS (
    SELECT
        TRIM(REGEXP_REPLACE(USTACK.CONV_PURCHASE_ID, '[^[:digit:]]', ' ')) AS CONV_PURCHASE_ID,
        NULLIF(USTACK.EVT_ALLOCADIA_ID, '-1') AS EVT_ALLOCADIA_ID,
        USTACK.EVT_CHANNEL,
        USTACK.CONV_REF_URL AS REF_URL,
        --ALID.CAMPAIGN_INDUSTRY,
        EVT_CAMPAIGN_ID || '_' || IFNULL(EVT_PLACEMENT_ID, '') || '_' || IFNULL(EVT_ADSET_ID, '') AS SPD_KEY,
        MAX(MIN_EVT_TIMESTAMP_UTC) EVT_TIMESTAMP
    FROM
        {{ var('FA_USER_STACK') }} USTACK
        --LEFT JOIN ALLOCADIA ALID ON CAST(EVT_ALLOCADIA_ID AS VARCHAR) = CAST(ALID.LINE_ITEM_ID AS VARCHAR)
    WHERE
        CONV_CONVERSION_TYPE = 'eStorePurchase'
        AND CONV_DATE BETWEEN $START_DATE AND $END_DATE
        AND CONV_PURCHASE_ID IS NOT NULL
        --AND CAMPAIGN_INDUSTRY IS NOT NULL
    GROUP BY
        ALL
),
--Get the latest touchpoint with non-null campaign industry
CAMPAIGN_INDUSTRY_LATEST AS (
    SELECT
        CONV_PURCHASE_ID,
        EVT_ALLOCADIA_ID,
        EVT_CHANNEL,
        REF_URL,
        --CAMPAIGN_INDUSTRY,
        SPD_KEY,
        ROW_NUMBER() OVER(
            PARTITION BY CONV_PURCHASE_ID
            ORDER BY
                EVT_TIMESTAMP DESC NULLS LAST
        ) RN
    FROM
        USTACK_DATA
    QUALIFY RN = 1
),
-- Remapping logic in MPM model MPM_USERFACT_METRICSCALC_STAGE
ALLOCADIA_ID_REMAPPING_FOR_INDUSTRY AS (
    SELECT
        A.CONV_PURCHASE_ID,
        ALID1.CAMPAIGN_INDUSTRY,
        ALID1.CHILD_CAMPAIGN_NAME,
        ALID1.PARENT_CAMPAIGN_NAME,
        ALID1.TACTIC_OWNER,
        COALESCE(TAXO.SPD_ALLOCADIA_ID, A.EVT_ALLOCADIA_ID) AS EVT_ALLOCADIA_ID,
        A.EVT_CHANNEL,
        A.REF_URL,
        ROW_NUMBER() OVER(
            PARTITION BY A.CONV_PURCHASE_ID
            ORDER BY ALID1.CAMPAIGN_INDUSTRY NULLS LAST
        ) AS RANK
    FROM
        CAMPAIGN_INDUSTRY_LATEST A
        LEFT JOIN (
            SELECT
                DISTINCT KEY,
                SPD_ALLOCADIA_ID
            FROM
                {{ ref('DIGITAL_EXECUTIONS_CAMPAIGN_TAXONOMY_MASTER') }}
            WHERE
                ACTIVE_TO IS NULL
        ) TAXO ON A.SPD_KEY = TAXO.KEY
        LEFT JOIN ALLOCADIA ALID1 ON COALESCE(CAST(TAXO.SPD_ALLOCADIA_ID AS VARCHAR),A.EVT_ALLOCADIA_ID) = CAST(ALID1.LINE_ITEM_ID AS VARCHAR)
    QUALIFY RANK = 1
),
FINMART_RAW AS ( 
    SELECT  
         CAST(SRC_ID AS VARCHAR) AS SRC_ID
        ,CASE
            WHEN PELICAN_SUBSCRIPTION_ID = '963769' AND  CORPORATE_CSN<> '5138666375' then SUBSCRIPTION_ID
            WHEN PELICAN_SUBSCRIPTION_ID = '*' THEN SUBSCRIPTION_ID
            ELSE PELICAN_SUBSCRIPTION_ID
        END AS COMBINED_SUBSCRIPTION_ID
        ,OXYGEN_ID
        ,CASE
            WHEN FIN.OXYGEN_ID = '*' AND H.OXYGEN_ID__C IS NULL THEN I.OWNEREXTERNALKEY
            WHEN FIN.OXYGEN_ID = '*' AND H.OXYGEN_ID__C IS NOT NULL THEN H.OXYGEN_ID__C
         ELSE FIN.OXYGEN_ID END AS ENRICHED_OXYGEN_ID
        ,COALESCE(AL.EVT_ALLOCADIA_ID,AL_2.EVT_ALLOCADIA_ID) as ALLOCADIA_ID
        ,TRANSACTION_DT
        ,CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FY_AND_FQ_NAME
        ,CAL.WEEK_NUMBER_FISCAL_QUARTER
        ,CAL.WEEK_START_DATE
        ,CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER
        ,CONCAT(
            'FY',
            REPLACE(
                SUBSTR(SETTLEMENT_START_FY_AND_FQ_NAME, 3),
                ' ',
                '-'
            )
        ) AS SETTLEMENT_START_FY_AND_FQ_NAME
        ,SETTLEMENT_START_DT
        ,SETTLEMENT_END_DT
        ,CONTRCT_START_DT
        ,CONTRCT_END_DT
        ,CASE WHEN CC_FBD_SF_FOX_RENEWAL_IND <> 'N/A' THEN CC_FBD_SF_FOX_RENEWAL_IND END CC_FBD_SF_FOX_RENEWAL_IND
        ,CASE WHEN BIC_ORDER_NBR <>'*' THEN BIC_ORDER_NBR END BIC_ORDER_NBR
        ,CASE WHEN PO_NBR <>'*' THEN PO_NBR END PO_NBR
        ,CASE WHEN ECC_SALES_ORDER_NBR <> '*' THEN ECC_SALES_ORDER_NBR END ECC_SALES_ORDER_NBR
        ,CASE WHEN QUOTE_NBR <> '*' THEN QUOTE_NBR END QUOTE_NBR 
        ,CASE WHEN QUOTE_LINE_ITEM_ID <> '*' THEN QUOTE_LINE_ITEM_ID END QUOTE_LINE_ITEM_ID
        ,CASE WHEN CORPORATE_PARENT_ACCOUNT_CSN <>'*' THEN CORPORATE_PARENT_ACCOUNT_CSN END CORPORATE_PARENT_ACCOUNT_CSN
        ,NULLIF(CORPORATE_CSN, '*') AS CORPORATE_CSN
        ,CASE WHEN SAP_PRODUCT_LINE <> '*' THEN SAP_PRODUCT_LINE END SAP_PRODUCT_LINE
        ,CASE WHEN PRODUCT_CLASS <> '*' THEN PRODUCT_CLASS END PRODUCT_CLASS
        ,CASE WHEN UPPER(CORPORATE_NAMED_ACCOUNT_GROUP_NM) NOT IN ('UNKNOWN','*') THEN CORPORATE_NAMED_ACCOUNT_GROUP_NM END CORPORATE_NAMED_ACCOUNT_GROUP_NM
        ,CASE WHEN UPPER(CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM) NOT IN ('UNKNOWN', '*') THEN CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM END AS CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM
        ,CASE WHEN CORPORATE_COUNTRY_NM <> '*' THEN CORPORATE_COUNTRY_NM END CORPORATE_COUNTRY_NM
        ,CASE WHEN CORPORATE_ACCOUNT_NM <> '*' THEN CORPORATE_ACCOUNT_NM END CORPORATE_ACCOUNT_NM
        ,CASE WHEN CORPORATE_COUNTRY_CD <> '*' THEN CORPORATE_COUNTRY_CD END CORPORATE_COUNTRY_CD
        ,CASE WHEN CORPORATE_PARENT_COUNTRY_CD <> '*' THEN CORPORATE_PARENT_COUNTRY_CD END CORPORATE_PARENT_COUNTRY_CD
        ,NULLIF(CORPORATE_PARENT_COUNTRY_NM, '*') AS CORPORATE_PARENT_COUNTRY_NM
        ,NULLIF(CORPORATE_PARENT_GEO_CD, '*') AS CORPORATE_PARENT_GEO_CD
        ,CC_FBD_BSM_ESTORE_ORDER_ORIGIN
        --LOGIC CHANGE AS PER STORE FUNNEL
        ,CASE
            WHEN CC_FBD_BSM_SALES_CH = 'eStore' THEN
                CASE 
                    WHEN CC_FBD_BSM_ESTORE_ORDER_ORIGIN = 'PORTAL' THEN 'Accounts'
                    WHEN CC_FBD_BSM_ESTORE_ORDER_ORIGIN in ('*','CLEVERBRIDGE','ESTORE','IPP','ipp','ERENEWAL') THEN 'E-Commerce'
                    WHEN CC_FBD_BSM_ESTORE_ORDER_ORIGIN in ('GUAC_MOE_DIRECT','GUAC_MOE_DTC','MOE','MOE_DIRECT','INSIDE SALES','Inside Sales CPQ') THEN 'Inside Sales'
                    ELSE 'App Store & Other'
                END
            ELSE 'App Store & Other'
         END AS ORIGIN_SEGMENT
        --IDENTIFY RETURN ORDERS
        ,CASE WHEN (BILLED_QUANTITY<0 OR CC_FBM_TOTAL_ACV_NET3_CC<0) THEN 1 ELSE 0 END AS RETURN_ORDER_FLG
        ,CASE WHEN UPPER(CORPORATE_HIER_INDUSTRY_SEGMENT_NM) NOT IN ('UNKNOWN', '*') THEN CORPORATE_HIER_INDUSTRY_SEGMENT_NM END AS CORPORATE_HIER_INDUSTRY_SEGMENT_NM
        ,CASE WHEN CC_FBD_SF_WWS_GEO ='APAC excl. Japan' THEN 'APAC' ELSE CC_FBD_SF_WWS_GEO END AS CC_FBD_SF_WWS_GEO
        ,CC_FBD_BSM_SALES_CH
        ,RECORD_TYPE
        ,CC_FBD_SF_BIL_TERM_SETL
        ,CC_FBM_SF_SUBS_SEATS_BILLED
        ,CC_BILLED_BGT_USD_FUT
        ,CC_FBM_TOTAL_ACV_NET3_CC_FUT
        ,CC_FBM_TOTAL_ACV_NET3_CC
        ,NULL AS ACS_NEW_ACV
        ,NULL AS ACS_NET_NEW_ACV
        ,NULL AS ACS_EXPANSION_ACV
        ,NULL AS ACS_RENEW_ACV
        ,NULL AS ACS_INSTALLMENT_ACV
        ,BILLED_QUANTITY
        ,FIN.SOLUTION_DIVISION
        ,FIN.ORD_OPTY_ID
        ,PROD.PRODUCT
        ,PROD.PRODUCT_FAMILY
        ,PROD.PRODUCT_INDUSTRY

        ,COALESCE(LKUP.GDPR_FLAG, 'NON-GDPR') AS GDPR_FLAG -- Added GDPR Flag from Country Lookup
        ,NAG.NAG_ACCOUNT_TYPE AS ABSM_FLAG
        ,LKUP.GEO AS CHILD_GEO
        ,LKUP_P.GEO AS PARENT_GEO
        ,COALESCE(AL.CAMPAIGN_INDUSTRY,AL_2.CAMPAIGN_INDUSTRY) as CAMPAIGN_INDUSTRY
        ,COALESCE(AL.CHILD_CAMPAIGN_NAME, AL_2.CHILD_CAMPAIGN_NAME) AS CHILD_CAMPAIGN_NAME
        ,COALESCE(AL.PARENT_CAMPAIGN_NAME, AL_2.PARENT_CAMPAIGN_NAME) AS PARENT_CAMPAIGN_NAME
        ,COALESCE(AL.TACTIC_OWNER, AL_2.TACTIC_OWNER) AS TACTIC_OWNER
        ,COALESCE(AL.EVT_CHANNEL, AL_2.EVT_CHANNEL) AS EVT_CHANNEL
        ,COALESCE(AL.REF_URL, AL_2.REF_URL) AS REF_URL
        ,FIN.CC_FBD_SF_SALES_TEAM_STARTS
        ,FIN.OFFER_TYPE_GROUP
        ,'Finmart Integrated' AS ACV_SOURCE
    FROM {{ source('FINMART_PUBLISH_PRIVATE', 'VW_FINMART') }} FIN
    LEFT JOIN {{ ref('LOOKUP_FINANCE_CALENDAR') }} CAL
        ON FIN.TRANSACTION_DT = CAL.DATE_KEY

    INNER JOIN (
        SELECT DISTINCT SRC_ID CVC_SRC_ID FROM {{ source('FINMART_PRIVATE', 'CVC_FINMART') }} WHERE SRC_ID IS NOT NULL
        ) CVC
        ON NVL(FIN.SRC_ID,'') = NVL(CVC.CVC_SRC_ID,'')
    
    LEFT JOIN(
        SELECT DISTINCT * FROM (
            SELECT F.*,G.* FROM (SELECT DISTINCT ORDERNUMBER__C,CONTACT__C FROM {{ source('SFDC_SHARED', 'ORDER__C') }}) F
            INNER JOIN 
            (SELECT DISTINCT OXYGEN_ID__C,ID FROM {{ var('CONTACT') }}) G
                ON F.CONTACT__C = G.ID )
        ) H 
        ON FIN.ECC_SALES_ORDER_NBR = H.ORDERNUMBER__C
    
    LEFT JOIN(
        SELECT DISTINCT OWNEREXTERNALKEY, TO_VARCHAR (ID) AS ID FROM {{ source('ENTITLEMENT_PUBLIC', 'SUBSCRIPTION_PELICAN') }}
        ) I
        ON I.ID = COMBINED_SUBSCRIPTION_ID
    LEFT JOIN ALLOCADIA_ID_REMAPPING_FOR_INDUSTRY AL 
        ON AL.CONV_PURCHASE_ID = TRIM(NULLIF(FIN.BIC_ORDER_NBR, '*'))
     LEFT JOIN ALLOCADIA_ID_REMAPPING_FOR_INDUSTRY AL_2 
        ON AL_2.CONV_PURCHASE_ID = TRIM(NULLIF(FIN.PO_NBR, '*'))
    LEFT JOIN {{ ref('LOOKUP_MPM_PRODUCT_CODE_TO_PRODUCT') }} PROD
        ON NULLIF(FIN.SAP_PRODUCT_LINE, '*') = NULLIF(PROD.CODE, '')
    LEFT JOIN {{ ref('DIM_FFM_COUNTRY_VW') }} LKUP
        ON UPPER(NULLIF(FIN.CORPORATE_COUNTRY_CD, '*')) = UPPER(LKUP.COUNTRY_SEARCH_CODE)
    LEFT JOIN {{ ref('DIM_FFM_COUNTRY_VW') }} LKUP_P
        ON UPPER(NULLIF(FIN.CORPORATE_PARENT_COUNTRY_CD, '*')) = UPPER(LKUP_P.COUNTRY_SEARCH_CODE)
    LEFT JOIN {{ var('NAG_MAPPING') }} AS NAG
        ON UPPER(FIN.CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM) = UPPER(NAG.NAMED_ACCOUNT_GROUP)

    WHERE 
        (
            FIN.TRANSACTION_DT BETWEEN $START_DATE AND $END_DATE
        OR FIN.SETTLEMENT_START_DT BETWEEN $START_DATE AND $END_DATE
        )
        AND UPPER(FIN.RECORD_TYPE) IN ('BILLING', 'BOOKING_BILLING')
        {# AND UPPER(COALESCE(FIN.PRODUCT_FAMILY_SD, '')) <> 'ACS' -- Exclude ACS Core records #}
        AND LOWER(COALESCE(FIN.CC_FBD_SF_SALES_TEAM_STARTS, '')) <> 'acs core' -- Exclude ACS Core records
),
ACS_CORE AS (
    SELECT
        CASE 
            WHEN LOWER(ACS.DATA_SOURCE) = 'acs core unintegrated' THEN CAST(SEQ8() AS VARCHAR)
            ELSE CAST(ACS.SRC_ID AS VARCHAR)
        END AS SRC_ID, -- 'acs core unintegrated' doesn't have unique src_id
        NULL AS COMBINED_SUBSCRIPTION_ID,
        NULL AS OXYGEN_ID,
        NULL AS ENRICHED_OXYGEN_ID,
        NULL AS ALLOCADIA_ID,
        ACS.INVOICE_DT AS TRANSACTION_DT,
        CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FY_AND_FQ_NAME,
        CAL.WEEK_NUMBER_FISCAL_QUARTER,
        CAL.WEEK_START_DATE,
        CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        CONCAT(
            'FY',
            REPLACE(
                SUBSTR(ACS.SETTLEMENT_START_FY_AND_FQ_NAME, 3),
                ' ',
                '-'
            )
        ) AS SETTLEMENT_START_FY_AND_FQ_NAME,
        ACS.SETTLEMENT_START_DT,
        ACS.SETTLEMENT_END_DT,
        ACS.CONTRACT_START_DT AS CONTRCT_START_DT,
        ACS.CONTRACT_END_DT AS CONTRCT_END_DT,
        NULL AS CC_FBD_SF_FOX_RENEWAL_IND,
        NULL AS BIC_ORDER_NBR,
        NULL AS PO_NBR,
        ACS.SALES_ORDER_NBR AS ECC_SALES_ORDER_NBR,
        NULL AS QUOTE_NBR,
        NULL AS QUOTE_LINE_ITEM_ID,
        NULLIF(ACS.CORPORATE_PARENT_ACCOUNT_CSN, '*') AS CORPORATE_PARENT_ACCOUNT_CSN,
        NULLIF(ACS.CORPORATE_CSN, '*') AS CORPORATE_CSN,
        NULL AS SAP_PRODUCT_LINE,
        ACS.PRODUCT_CLASS AS PRODUCT_CLASS,
        CASE WHEN UPPER(ACS.CORPORATE_NAMED_ACCOUNT_GROUP_NM) NOT IN ('UNKNOWN','*') THEN ACS.CORPORATE_NAMED_ACCOUNT_GROUP_NM END AS CORPORATE_NAMED_ACCOUNT_GROUP_NM,
        NULL AS CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM,
        NULLIF(ACS.CORPORATE_COUNTRY_NM, '*') AS CORPORATE_COUNTRY_NM,
        NULLIF(ACS.CORPORATE_ACCOUNT_NM, '*') AS CORPORATE_ACCOUNT_NM,
        NULL AS CORPORATE_COUNTRY_CD,
        NULL AS CORPORATE_PARENT_COUNTRY_CD,
        NULL AS CORPORATE_PARENT_COUNTRY_NM,
        NULL AS CORPORATE_PARENT_GEO_CD,
        NULL AS CC_FBD_BSM_ESTORE_ORDER_ORIGIN,
        NULL AS ORIGIN_SEGMENT,
        NULL AS RETURN_ORDER_FLG,
        CASE WHEN UPPER(ACS.CORPORATE_HIER_INDUSTRY_SEGMENT_NM) NOT IN ('UNKNOWN', '*') THEN ACS.CORPORATE_HIER_INDUSTRY_SEGMENT_NM END AS CORPORATE_HIER_INDUSTRY_SEGMENT_NM,
        CASE WHEN ACS.CC_FBD_SF_WWS_GEO = 'APAC excl. Japan' THEN 'APAC' ELSE ACS.CC_FBD_SF_WWS_GEO END AS CC_FBD_SF_WWS_GEO,
        ACS.CC_FBD_BSM_SALES_CH,
        NULL AS RECORD_TYPE,
        NULL AS CC_FBD_SF_BIL_TERM_SETL,
        NULL AS CC_FBM_SF_SUBS_SEATS_BILLED,
        NULL AS CC_BILLED_BGT_USD_FUT,
        NULL AS CC_FBM_TOTAL_ACV_NET3_CC_FUT,
        ACS.CC_FBM_TOTAL_ACV_NET3_CC,
        ACS.NEW_ACV AS ACS_NEW_ACV,
        ACS.NET_NEW_ACV AS ACS_NET_NEW_ACV,
        ACS.EXPANSION_ACV AS ACS_EXPANSION_ACV,
        ACS.RENEW_ACV AS ACS_RENEW_ACV,
        ACS.INSTALLMENT_ACV AS ACS_INSTALLMENT_ACV,
        NULL AS BILLED_QUANTITY,
        ACS.SOLUTION_DIVISION AS SOLUTION_DIVISION,
        NULL AS ORD_OPTY_ID,
        NULL AS PRODUCT,
        'ACS' AS PRODUCT_FAMILY,
        'ACS' AS PRODUCT_INDUSTRY,
        COALESCE(LKUP.GDPR_FLAG, 'NON-GDPR') AS GDPR_FLAG, -- Added GDPR Flag from Country Lookup
        NULL AS ABSM_FLAG,
        LKUP.GEO AS CHILD_GEO,
        NULL AS PARENT_GEO,
        NULL AS CAMPAIGN_INDUSTRY,
        NULL AS CHILD_CAMPAIGN_NAME,
        NULL AS PARENT_CAMPAIGN_NAME,
        NULL AS TACTIC_OWNER,
        NULL AS EVT_CHANNEL,
        NULL AS REF_URL,
        ACS.CC_FBD_SF_SALES_TEAM_STARTS,
        NULL AS OFFER_TYPE_GROUP,
        ACS.DATA_SOURCE AS ACV_SOURCE
    FROM
        {{ source('FINMART_PUBLISH_PRIVATE', 'ACS_FINANCE_RENEWALS') }} ACS
    LEFT JOIN {{ ref('LOOKUP_FINANCE_CALENDAR') }} CAL
        ON ACS.INVOICE_DT = CAL.DATE_KEY
    LEFT JOIN {{ ref('DIM_FFM_COUNTRY_VW') }} LKUP
        ON UPPER(NULLIF(ACS.CORPORATE_COUNTRY_NM, '*')) = UPPER(LKUP.COUNTRY_SEARCH_CODE)
    WHERE
        LOWER(DATA_SOURCE) IN ('acs core integrated', 'acs core unintegrated')
        AND LOWER(ACS_PRODUCT_PHASE) <> 'design'
        AND LOWER(PRODUCT_LEVEL) = 'customer_parent'
        AND (
            SOURCE_RM <> 'Michael Counte'
            OR SOURCE_RM IS NULL
            OR SOURCE_RM = ''
        )  
        AND SOURCE <> 'eba_token_deals'
        AND INVOICE_DT BETWEEN $START_DATE AND $END_DATE
),
INNOVYZE_MA AS (
    SELECT 
        NULL AS SRC_ID,
        NULL AS COMBINED_SUBSCRIPTION_ID,
        NULL AS OXYGEN_ID,
        NULL AS ENRICHED_OXYGEN_ID,
        NULL AS ALLOCADIA_ID,
        NULL AS TRANSACTION_DT,
        CONCAT(
            'FY',
            REPLACE(
                SUBSTR(FIN.FISCAL_QUARTER, 3),
                ' ',
                '-'
            )
        ) AS FY_AND_FQ_NAME,
        CAL.WEEK_NUMBER_FISCAL_QUARTER,
        CAL.WEEK_START_DATE,
        CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        NULL AS SETTLEMENT_START_FY_AND_FQ_NAME,
        NULL AS SETTLEMENT_START_DT,
        NULL AS SETTLEMENT_END_DT,
        NULL AS CONTRCT_START_DT,
        NULL AS CONTRCT_END_DT,
        CASE
            WHEN DATA_SOURCE = 'Unint. M&A' THEN NULL -- M&A doesn't have Renewal Indicator
            ELSE FIN.CUST_DIM_NEWRENEW
        END AS CC_FBD_SF_FOX_RENEWAL_IND,
        NULL AS BIC_ORDER_NBR,
        NULL AS PO_NBR,
        NULL AS ECC_SALES_ORDER_NBR,
        NULL AS QUOTE_NBR,
        NULL AS QUOTE_LINE_ITEM_ID,
        NULL AS CORPORATE_PARENT_ACCOUNT_CSN,
        NULL AS CORPORATE_CSN,
        NULL AS SAP_PRODUCT_LINE,
        FIN.CUST_DIM_PRODUCT_CLASS AS PRODUCT_CLASS,
        NULL AS CORPORATE_NAMED_ACCOUNT_GROUP_NM,
        NULL AS CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM,
        NULL AS CORPORATE_COUNTRY_NM,
        NULL AS CORPORATE_ACCOUNT_NM,
        NULL AS CORPORATE_COUNTRY_CD,
        NULL AS CORPORATE_PARENT_COUNTRY_CD,
        NULL AS CORPORATE_PARENT_COUNTRY_NM,
        NULL AS CORPORATE_PARENT_GEO_CD,
        NULL AS CC_FBD_BSM_ESTORE_ORDER_ORIGIN,
        NULL AS ORIGIN_SEGMENT,
        NULL AS RETURN_ORDER_FLG,
        NULL AS CORPORATE_HIER_INDUSTRY_SEGMENT_NM,
        CASE WHEN FIN.CUST_DIM_GEO = 'APAC excl. Japan' THEN 'APAC' ELSE FIN.CUST_DIM_GEO END AS CC_FBD_SF_WWS_GEO,
        CASE
            WHEN DATA_SOURCE = 'Unint. M&A' THEN NULL -- M&A doesn't have Sales Channel
            ELSE FIN.CC_FBD_BSM_SALES_CH
        END AS CC_FBD_BSM_SALES_CH,
        NULL AS RECORD_TYPE,
        NULL AS CC_FBD_SF_BIL_TERM_SETL,
        NULL AS CC_FBM_SF_SUBS_SEATS_BILLED,
        NULL AS CC_BILLED_BGT_USD_FUT,
        NULL AS CC_FBM_TOTAL_ACV_NET3_CC_FUT,
        SUM(FIN.ACV_ACTUALS_CQ) AS CC_FBM_TOTAL_ACV_NET3_CC,
        NULL AS ACS_NEW_ACV,
        NULL AS ACS_NET_NEW_ACV,
        NULL AS ACS_EXPANSION_ACV,
        NULL AS ACS_RENEW_ACV,
        NULL AS ACS_INSTALLMENT_ACV,
        NULL AS BILLED_QUANTITY,
        NULL AS SOLUTION_DIVISION,
        NULL AS ORD_OPTY_ID,
        NULL AS PRODUCT,
        CASE
            WHEN FIN.DATA_SOURCE = 'Unint. M&A' THEN 'M&A'
            WHEN FIN.DATA_SOURCE IN ('Innovyze Int.', 'Innovyze Unint.') THEN 'Innovyze'
        END AS PRODUCT_FAMILY,
        CASE
            WHEN FIN.DATA_SOURCE = 'Unint. M&A' THEN 'M&A'
            WHEN FIN.DATA_SOURCE IN ('Innovyze Int.', 'Innovyze Unint.') THEN 'AEC'
        END AS PRODUCT_INDUSTRY,
        NULL AS GDPR_FLAG, -- GDPR Flag not applicable for Innovyze M&A as there is no Country field
        NULL AS ABSM_FLAG,
        NULL AS CHILD_GEO,
        NULL AS PARENT_GEO,
        NULL AS CAMPAIGN_INDUSTRY,
        NULL AS CHILD_CAMPAIGN_NAME,
        NULL AS PARENT_CAMPAIGN_NAME,
        NULL AS TACTIC_OWNER,
        NULL AS EVT_CHANNEL,
        NULL AS REF_URL,
        NULL AS CC_FBD_SF_SALES_TEAM_STARTS,
        NULL AS OFFER_TYPE_GROUP,
        CASE
            WHEN FIN.DATA_SOURCE = 'Unint. M&A' THEN 'M&A Unintegrated'
            WHEN FIN.DATA_SOURCE = 'Innovyze Int.' THEN 'Innovyze Integrated'
            WHEN FIN.DATA_SOURCE = 'Innovyze Unint.' THEN 'Innovyze Unintegrated'
        END AS ACV_SOURCE
    FROM
        {{ source('CORPORATE_FINMART_PUBLISH_PRIVATE', 'FINANCE_CURATED') }} FIN
    INNER JOIN WEEK_CALENDAR AS CAL
        ON FY_AND_FQ_NAME = CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND TRY_TO_NUMBER(SPLIT_PART(FIN.FISCAL_WEEK, '_', 2)) = CAST(CAL.WEEK_NUMBER_FISCAL_QUARTER AS INT)
    WHERE
        DATA_SOURCE IN ('Unint. M&A', 'Innovyze Int.', 'Innovyze Unint.')
        AND HEDGE_INDICATOR = 'With VP'
        AND MYAB_INDICATOR = 'WITH MYAB'
    GROUP BY ALL
),
-- Combine Finmart, ACS Core, Innovyze & M&A data
FINMART_ACS_CORE AS (
    SELECT * FROM FINMART_RAW
    UNION ALL
    SELECT * FROM ACS_CORE
    UNION ALL
    SELECT * FROM INNOVYZE_MA
),
VICTIM_SURVIVOR AS (
    SELECT
        DISTINCT VICTIM_ACCOUNT_CSN, SURVIVING_ACCOUNT_CSN, FINAL_MERGE_STATUS
    FROM
        {{ source('EDM_PUBLIC', 'VICTIM_SURVIVOR_MAPPING') }}
)

,SURVIVOR_MAPPING AS (
    SELECT
        FIN_SURV.*,
        PAR1.CORPORATE_PARENT_CSN_STATIC AS PARENT_SURVIVOR_CORPORATE_CSN,
        PAR_ACC_SURV.SURVIVING_ACCOUNT_CSN AS PARENT_SURVIVING_PARENTACCOUNT_CSN,
        COALESCE(
            PAR_ACC_SURV.SURVIVING_ACCOUNT_CSN, -- survivor of parent of survivor 
            PAR1.CORPORATE_PARENT_CSN_STATIC, -- parent of survivor csn 
            FIN_SURV.SURVIVOR_CORPORATE_CSN
        ) AS FINAL_CSN
    FROM(
        SELECT
            FIN.*,
            IFNULL(ACC_SURV.SURVIVING_ACCOUNT_CSN, FIN.CORPORATE_CSN) AS SURVIVOR_CORPORATE_CSN
        FROM
            FINMART_ACS_CORE FIN
            LEFT JOIN (
                SELECT DISTINCT VICTIM_ACCOUNT_CSN, SURVIVING_ACCOUNT_CSN
                FROM VICTIM_SURVIVOR
                WHERE FINAL_MERGE_STATUS = 'COMPLETED'
            ) ACC_SURV 
            ON FIN.CORPORATE_CSN = ACC_SURV.VICTIM_ACCOUNT_CSN
        ) FIN_SURV
        
        LEFT JOIN (
            SELECT
                T.ACCOUNT_CSN, A.CORPORATE_PARENT_CSN_STATIC
            FROM
            {{ source('ACCOUNT_OPTIMIZED', 'ACCOUNT_EDP_OPTIMIZED') }} A
            INNER JOIN {{ source('ACCOUNT_OPTIMIZED', 'TRANSACTIONAL_CSN_MAPPING_OPTIMIZED') }} T
            ON T.SITE_UUID_CSN = A.SITE_UUID_CSN
        ) PAR1 ON FIN_SURV.SURVIVOR_CORPORATE_CSN = PAR1.ACCOUNT_CSN

        LEFT JOIN (
            SELECT DISTINCT VICTIM_ACCOUNT_CSN, SURVIVING_ACCOUNT_CSN
            FROM VICTIM_SURVIVOR
        ) PAR_ACC_SURV ON PAR1.CORPORATE_PARENT_CSN_STATIC = PAR_ACC_SURV.VICTIM_ACCOUNT_CSN
)

SELECT *,
    CASE
      WHEN UPPER(EVT_CHANNEL) LIKE '%ORGANIC%' OR UPPER(EVT_CHANNEL) IN ('DIRECT', 'INTERNAL') THEN 'Organic'
      WHEN UPPER(EVT_CHANNEL) LIKE '%PAID%' OR UPPER(EVT_CHANNEL) IN ('DISPLAY', 'AFFILIATES', 'EMAIL', 'VIDEO', 'IPM', 'ITM') THEN 'Paid'
      ELSE 'Other'
    END AS CHANNEL_TYPE
FROM SURVIVOR_MAPPING