-- airflow Dag which regulates this model: 
-- dir: mdp_360/mdp_i360_new_dag 
-- dag: mdp_i360_new_trg

-- Get the right stack database properties.
{% set db_properties=get_dbproperties('MDP_I360_NEW') %}


-- Set the database properties.
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Setting the Materialization.
{{ config(
        materialized='table'
) }}

-- set the right tags.
{{ config(tags= [var('TAG_MDP_I360_NEW'), var('TAG_MDP_I360_NEW_SFTP_DATA_INTEGRATION')]) }}



-- in INITAL_SFTP_DATA cte we are combining data from 3 SFTP data tables
-- MDP_PLANCLAIMHEADER, MDP_CAMPAIGNS, MDP_ACTIVITY_QUESTIONS
-- files in sftp : ['ActivityQuestions_date.csv', 'Campaigns_date.csv', 'PlanClaimHeader_date
WITH INITAL_SFTP_DATA AS (

WITH
PIVOT_QUESTION AS (
    SELECT DISTINCT PLANID,
    PLANDETAILID,
    CLAIMNUMBER,
    CLAIMDETAILID,
    SCENARIO,
    SUM(ACTIVITY_MQLS_EXPECTED_EXPECTED_NUMBER_OF_MARKETING_QUALIFIED_LEADS) AS ACTIVITY_MQLS_EXPECTED_EXPECTED_NUMBER_OF_MARKETING_QUALIFIED_LEADS,
    SUM(ACTIVITY_MQLS_ACTUAL_ACTUAL_NUMBER_OF_MARKETING_QULIFIED_LEADS) AS ACTIVITY_MQLS_ACTUAL_ACTUAL_NUMBER_OF_MARKETING_QULIFIED_LEADS,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_CLICKS) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_CLICKS,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_CLICKS) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_CLICKS,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS,
    SUM(ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS) AS ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS
FROM(
      SELECT DISTINCT 
      PLANID, 
      PLANDETAILID, 
      CASE WHEN CLAIMNUMBER IS NULL THEN 'NULL' ELSE CLAIMNUMBER END AS CLAIMNUMBER, 
      CASE WHEN CLAIMDETAILID IS NULL THEN 'NULL' ELSE CLAIMDETAILID END AS CLAIMDETAILID,
      CASE WHEN QUESTIONID = '1' THEN "ACTIVITY ANSWER" ELSE '' END PRIMARY_TARGET_GEO,
      CASE WHEN QUESTIONID = '2' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_MQLS_EXPECTED_EXPECTED_NUMBER_OF_MARKETING_QUALIFIED_LEADS,
      CASE WHEN QUESTIONID = '5' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_MQLS_ACTUAL_ACTUAL_NUMBER_OF_MARKETING_QULIFIED_LEADS,       
      CASE WHEN QUESTIONID = '8' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_CLICKS,   
      CASE WHEN QUESTIONID = '9' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS,    
      CASE WHEN QUESTIONID = '10' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
      CASE WHEN QUESTIONID = '11' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
      CASE WHEN QUESTIONID = '12' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_CLICKS,   
      CASE WHEN QUESTIONID = '13' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS, 
      CASE WHEN QUESTIONID = '14' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
      CASE WHEN QUESTIONID = '15' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
      CASE WHEN QUESTIONID = '16' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS,
      CASE WHEN QUESTIONID = '17' THEN TRY_TO_NUMBER(REPLACE("ACTIVITY ANSWER",',','')) END ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS,
      CASE WHEN QUESTIONID IN ('1','5') THEN 'S1.1'
           WHEN QUESTIONID IN ('2','8','9','10','11','16') THEN 'S2.1'
           WHEN QUESTIONID IN ('12','13','14','15','17') THEN 'S2.2'
         END AS SCENARIO
      FROM -- BSM_ETL.MDF.MDP_ACTIVITY_QUESTIONS
            {{ source('MDF_ETL', 'MDP_ACTIVITY_QUESTIONS') }}


    )
GROUP BY 1,2,3,4,5
)
    
SELECT PH.*, C."CAMPAIGN NAME",
      CAST(REPLACE(C."CAMPAIGN PERCENTAGE",'%','') AS DECIMAL) AS "CAMPAIGN PERCENTAGE",
      PS21.ACTIVITY_MQLS_EXPECTED_EXPECTED_NUMBER_OF_MARKETING_QUALIFIED_LEADS,
      PS11.ACTIVITY_MQLS_ACTUAL_ACTUAL_NUMBER_OF_MARKETING_QULIFIED_LEADS,       
      PS21.ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_CLICKS,   
      PS21.ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS,    
      PS21.ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
      PS21.ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
      PS21.ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS,
      PS22.ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_CLICKS,   
      PS22.ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS, 
      PS22.ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
      PS22.ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
      PS22.ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS

FROM (
  SELECT *, 
 	 CASE WHEN CLAIMNUMBER IS NULL THEN 'NULL' ELSE CLAIMNUMBER END AS CLAIMNUMBER_LINK,
     CASE WHEN CLAIMDETAILID IS NULL THEN 'NULL' ELSE CLAIMDETAILID END AS CLAIMDETAILID_LINK 
  FROM -- BSM_ETL.MDF.MDP_PLANCLAIMHEADER
        {{ source('MDF_ETL', 'MDP_PLANCLAIMHEADER') }} ) PH
LEFT JOIN  (SELECT *,
            CASE WHEN CLAIMNUMBER IS NULL THEN 'NULL' ELSE CLAIMNUMBER END AS CLAIMNUMBER_LINK,
            CASE WHEN CLAIMDETAILID IS NULL THEN 'NULL' ELSE CLAIMDETAILID END AS CLAIMDETAILID_LINK 
            FROM -- BSM_ETL.MDF.MDP_CAMPAIGNS
                {{ source('MDF_ETL', 'MDP_CAMPAIGNS') }}
            ) C ON PH.PLANID=C.PLANID AND PH.PLANDETAILID=C.PLANDETAILID AND PH.CLAIMNUMBER_LINK=C.CLAIMNUMBER_LINK AND PH.CLAIMDETAILID_LINK=C.CLAIMDETAILID_LINK
LEFT JOIN (SELECT * FROM PIVOT_QUESTION WHERE SCENARIO='S1.1') PS11 ON PH.PLANID=PS11.PLANID AND PH.CLAIMNUMBER_LINK=PS11.CLAIMNUMBER
LEFT JOIN (SELECT * FROM PIVOT_QUESTION WHERE SCENARIO='S2.1') PS21 ON PH.PLANDETAILID=PS21.PLANDETAILID
LEFT JOIN (SELECT * FROM PIVOT_QUESTION WHERE SCENARIO='S2.2') PS22 ON PH.CLAIMDETAILID_LINK=PS22.CLAIMDETAILID
)



 -- getting the pivoted data from INITAL_SFTP_DATA cte
,PIVOTTED_DATA AS (

    SELECT DISTINCT 
    FUNDID,
    FUNDNAME,
    FUNDPERIOD,
    PLANID,
    PLANDETAILID,
    CLAIMNUMBER,
    CLAIMDETAILID,
    CUSTOMERID,
    CUSTOMERNAME,
    GROUPNAME,
    AREA,
    REGION,
    COUNTRY,
    SPONSOR,
    FUNDTYPE,
    FUNDCOUNTRYCODE,
    REIMBURSEMENTBY,
    PROMOTIONBY,
    REIMBURSEMENTMETHOD,
    PLANSTATUS,
    PLANSUBMISSIONDATE,
    PLANCHANGEDDATE,
    PLANAPPROVALDATE,
    MARKETINGACTIVITYCONTACT,
    MARKETINGACTIVITYCONTACTPHONE,
    MARKETINGACTIVITYCONTACTEMAIL,
    MARKETINGACTIVITYOTHEREMAILS,
    PLANSUBMITTERNAME,
    PLANSUBMITTEREMAIL,
    PLANINVESTMENTAMOUNTLC,
    PLANINVESTMENTAMOUNTCONVERTEDTOUSD,
    PLANREIMBURSEMENTAMOUNTLC,
    PLANREIMBURSEMENTAMOUNTCONVERTEDTOUSD,
    PLANAPPROVEDREIMBURSEMENTAMOUNTLC,
    PLANAPPROVEDREIMBURSEMENTAMOUNTCONVERTEDTOUSD,
    PAPAIDAMOUNTLC,
    PAPAIDAMOUNTUSD,
    PAPAYMENTDATE,
    PAPAYMENTID,
    ACTIVITYBEGINDATE,
    ACTIVITYENDDATE,
    QUARTEROFACTIVITYENDDATE,
    ACTIVITY,
    SUBACTIVITY,
    CAMPAIGN,
    PLANPROMOTIONID,
    PUBLICATIONNAME,
    PLANDESCRIPTION,
    CLAIMDESCRIPTION,
    PLANAPPROVER,
    PLANEXTERNALCOMMENTS,
    PLANINTERNALCOMMENTS,
    CLAIMAUDITSTATUS,
    CLAIMVOIDDATE,
    CLAIMCONTACT,
    CLAIMCONTACTPHONE,
    CLAIMCONTACTEMAIL,
    CLAIMOTHEREMAILS,
    CLAIMSUBMITTERNAME,
    CLAIMSUBMITTEREMAIL,
    CLAIMSUBMITTEDDATE,
    TRANSACTIONHOLDREVIEWER,
    "HOLD/DENY REASON",
    HELDDATE,
    TRANSACTIONAPPROVER,
    TRANSACTIONDATE,
    PAYMENTREGISTERCREATED,
    PAYMENTREGISTERID,
    PAYMENTREGISTERAPPROVER,
    PAYMENTREGISTERAPPROVALDATE,
    PAYMENTREGISTERCHECKRUNDATE,
    PAYMENTDATESUBMITTED,
    CLAIMPAIDDATE,
    CLAIMAPPROVALDATE,
    CLAIMINVESTMENTAMOUNTLC,
    CLAIMINVESTMENTAMOUNTCONVERTEDTOUSD,
    CLAIMREIMBURSEMENTAMOUNTLC,
    CLAIMREIMBURSEMENTAMOUNTCONVERTEDTOUSD,
    CLAIMPAIDAMOUNTLC,
    CLAIMPAIDAMOUNTCONVERTEDTOUSD,
    CLAIMHELDAMOUNTLC,
    CLAIMHELDAMOUNTCONVERTEDTOUSD,
    CLAIMDENIEDAMOUNTLC,
    CLAIMDENIEDAMOUNTCONVERTEDTOUSD,
    CLAIMPROMOTIONID,
    CLAIMBYDATE,
    CLAIMAGE,
    CLAIMAGERANGE,
    LASTDATECLAIMUPDATED,
    CLAIMPAIDYEAR,
    CLAIMPAIDMONTH,
    CLAIMPAIDQUARTER,
    PLANSUBMITTEDYEAR,
    PLANSUBMITTEDMONTH,
    PLANSUBMITTEDQUARTER,
    CLAIMEXTERNALCOMMENTS,
    CLAIMINTERNALCOMMENTS,
    PRIMARYEMAIL,
    REPORTCREATEDATE,
    CLAIMNUMBER_LINK,
    CLAIMDETAILID_LINK,
    "CAMPAIGN NAME",
    "CAMPAIGN PERCENTAGE",
    ACTIVITY_MQLS_EXPECTED_EXPECTED_NUMBER_OF_MARKETING_QUALIFIED_LEADS,
    ACTIVITY_MQLS_ACTUAL_ACTUAL_NUMBER_OF_MARKETING_QULIFIED_LEADS,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_CLICKS,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_CLICKS,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE,
    ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS,
	ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS
FROM 
    INITAL_SFTP_DATA

)


 -- final select 
    SELECT A.*, B."ACTIVITY ANSWER" AS PRIMARY_TARGET_GEO FROM PIVOTTED_DATA A
    LEFT JOIN
    (
            SELECT DISTINCT PLANID,PLANDETAILID,
                CASE 
                    WHEN CLAIMNUMBER IS NULL THEN 'NULL' 
                    ELSE CLAIMNUMBER END AS CLAIMNUMBER,"ACTIVITY ANSWER" 
            FROM 
            -- "BSM_ETL.MDF.MDP_ACTIVITY_QUESTIONS"
            {{ source('MDF_ETL', 'MDP_ACTIVITY_QUESTIONS') }}
            WHERE QUESTIONID = '1'
    ) B ON A.PLANID=B.PLANID AND A.CLAIMNUMBER_LINK=B.CLAIMNUMBER


