-- =============================================================================
-- LAYER  : Silver — Staging Dimension
-- MODEL  : dim_clm_account_attributions
-- NOTES  : Account attribution dimension (AOV bands, geography, industry)
--          Replaces common/DIM_CLM_ACCOUNT_ATTRIBUTIONS.sql
--          ACCOUNT_SFDC_RAW hardcoded ref replaced with source('adp','ACCOUNT_SFDC_RAW')
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('ffm') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_CJO_READONLY",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST"
    ]
  )
}}



WITH SFDC_ACCOUNT AS
(
  SELECT DISTINCT ACCOUNT_CSN__C AS ACCOUNT_CSN
    , PARENT_ACCOUNT_CSN__C AS PARENT_ACCOUNT_CSN
    , COUNTRY_PICKLIST__C AS COUNTRY
    , NAMED_ACCOUNT_GROUP__C AS NAMED_ACCOUNT_GROUP
    , PARENT_INDUSTRY_GROUP__C AS PARENT_INDUSTRY_GROUP
    , INDUSTRY_GROUP__C AS INDUSTRY_GROUP
    , PARENT_INDUSTRY_SEGMENT__C AS PARENT_INDUSTRY_SEGMENT
    , INDUSTRY_SEGMENT__C AS INDUSTRY_SEGMENT
    , INDUSTRY_SUB_SEGMENT__C AS INDUSTRY_SUB_SEGMENT
  FROM 
  --{{ var('ACCOUNT_SFDC_RAW') }}
  {{ source('adp', 'ACCOUNT_SFDC_RAW') }} 
  WHERE ACCOUNT_CSN__C IS NOT NULL
),

DIM_FUZZYSEARCH_COUNTRY AS
(
  SELECT DISTINCT ALPHA_2 AS ALPHA_2_COUNTRY_CODE
    , COUNTRY
    , REGION
    , GEO
    , FUZZY_SEARCH_CODE
  FROM {{ var('LOOKUP_COUNTRY_MAPPING') }}
),

AOV_Q1 AS (
    SELECT DISTINCT CHILD_CSN_YOY_AOV_BAND,
        BFM.CHILD_CSN_QOQ_AOV_BAND,
        BFM.PARENT_CSN_YOY_AOV_BAND,
        BFM.PARENT_CSN_QOQ_AOV_BAND,
        BFM.PERIOD,
        SUBSTR(BFM.PERIOD, 1,4)::INTEGER AS FY,
        SUBSTR(BFM.PERIOD, LENGTH(BFM.PERIOD), LENGTH(BFM.PERIOD))::INTEGER AS QTR,
        BFM.CORPORATE_CSN AS CHILD_ACCOUNT_CSN,
        BFM.CORPORATE_PARENT_ACCOUNT_CSN AS PARENT_ACCOUNT_CSN,
    FROM {{ var('BMT_FINANCE_METRICS') }} BFM
    GROUP BY ALL
    ORDER BY BFM.PERIOD DESC
),
 
AOV_Q2 AS (
    SELECT CHILD_CSN_YOY_AOV_BAND,
        CHILD_CSN_QOQ_AOV_BAND,
        PARENT_CSN_YOY_AOV_BAND,
        PARENT_CSN_QOQ_AOV_BAND,
        PERIOD,
        FY,
        QTR,
        CHILD_ACCOUNT_CSN,
        PARENT_ACCOUNT_CSN,
        ROW_NUMBER() OVER (PARTITION BY PARENT_ACCOUNT_CSN,FY ORDER BY FY, QTR DESC) AS ROW_NUM,
        DENSE_RANK() OVER (PARTITION BY CHILD_ACCOUNT_CSN ORDER BY FY DESC) AS RNK_NUM_FY
    FROM AOV_Q1
    QUALIFY ROW_NUM=1 AND RNK_NUM_FY=1
    ORDER BY PERIOD DESC
),

AOV_GROUP AS
(
  SELECT DISTINCT CHILD_ACCOUNT_CSN AS ACCOUNT_CSN,
    PARENT_ACCOUNT_CSN,
    CHILD_CSN_YOY_AOV_BAND AS CHILD_AOV_GROUP,
    PARENT_CSN_YOY_AOV_BAND AS PARENT_AOV_GROUP
  FROM AOV_Q2
),

TEST_CONTROL AS
(
  SELECT DISTINCT ACCOUNT_CSN__C
    , SEMI_RANDOM_DIGIT
  FROM {{ var('ILM_ACCOUNTS') }}
  WHERE SEMI_RANDOM_DIGIT= 1
)


SELECT DISTINCT ACC.ACCOUNT_CSN
  , ACC.PARENT_ACCOUNT_CSN
  , ACC.NAMED_ACCOUNT_GROUP
  , ACC.INDUSTRY_GROUP
  , ACC.PARENT_INDUSTRY_GROUP
  , ACC.INDUSTRY_SEGMENT
  , ACC.PARENT_INDUSTRY_SEGMENT
  , ACC.INDUSTRY_SUB_SEGMENT
  , ACC.COUNTRY
  , CNT.REGION
  , CNT.GEO
  , AOV.CHILD_AOV_GROUP
  , AOV.PARENT_AOV_GROUP
  , CASE WHEN TC.ACCOUNT_CSN__C IS NOT NULL THEN 'Control' ELSE 'Test' END AS TEST_CONTROL_FLAG

FROM SFDC_ACCOUNT ACC
LEFT JOIN DIM_FUZZYSEARCH_COUNTRY CNT
  ON UPPER(ACC.COUNTRY) = UPPER(CNT.FUZZY_SEARCH_CODE)
LEFT JOIN AOV_GROUP AOV
  ON ACC.PARENT_ACCOUNT_CSN = AOV.PARENT_ACCOUNT_CSN
  AND ACC.ACCOUNT_CSN = AOV.ACCOUNT_CSN
LEFT JOIN TEST_CONTROL TC
  ON ACC.ACCOUNT_CSN = TC.ACCOUNT_CSN__C

