-- =============================================================================
-- LAYER  : Gold — Business Facts
-- MODEL  : fact_sprout_profile_data
-- UPSTREAM: Silver bronze models (stg_sprout_*_profile_data) + dim_sprout_customer
--           + dim_sprout_date_hierarchy
-- NOTES  : Union of all platform profile metrics; replaces FACT_SPROUT_PROFILE_DATA.sql
-- =============================================================================

{% set db_properties = get_dbproperties('SPROUT_API_INGESTION') %}

{{ config(
    database = db_properties['database'],
    schema   = db_properties['schema'],
    materialized = 'table',
    tags = [var('TAG_SPROUT_API_INGESTION'), var('TAG_SPROUT_FACT_INGESTION')],
    post_hook = [
        "GRANT SELECT ON ALL TABLES IN SCHEMA PROD.SPROUT TO ROLE BSM_MOT_ANALYST; "
    ]
) }}

WITH DATE_TIME_HIERARCHY AS (SELECT * FROM {{ ref('dim_sprout_date_hierarchy') }}),
CUSTOMER_DATA AS (SELECT DISTINCT CUSTOMER_PROFILE_ID, NAME FROM {{ ref('dim_sprout_customer') }})

SELECT 'TWITTER' AS SOURCE, A.CUSTOMER_PROFILE_ID, CUST.NAME, REPORTING_PERIOD_DAY,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    SUM(NVL(IMPRESSIONS,0)) AS IMPRESSIONS, 0 AS POST_IMPRESSIONS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS_COUNT,
    SUM(NVL(SHARES_COUNT,0)) AS SHARES_COUNT, SUM(NVL(POST_LINK_CLICKS,0)) AS POST_LINK_CLICKS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, 0 AS VIDEO_VIEW_TIME, 0 AS VIDEO_VIEWS_UNIQUE,
    SUM(NVL(SHARES_COUNT,0)) AS REPOST, SUM(NVL(LIKES,0)) AS LIKES,
    SUM(NVL(POST_APP_ENGAGEMENTS,0)) AS APP_ENGAGEMENTS,
    0 AS WEBSITE_CLICKS, 0 AS POST_CLICKS, 0 AS FOLLOWERS, 0 AS NET_FOLLOWER_GROWTH,
    0 AS POST_SENT, 0 AS PROFILE_VIEWS, 0 AS PUBISHED_POST, 0 AS REACH
FROM {{ ref('stg_sprout_twitter_profile_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.REPORTING_PERIOD_DAY = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT 'FACEBOOK' AS SOURCE, A.CUSTOMER_PROFILE_ID, CUST.NAME, REPORTING_PERIOD_DAY,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    SUM(NVL(IMPRESSIONS,0)) AS IMPRESSIONS, SUM(NVL(POST_IMPRESSIONS,0)) AS POST_IMPRESSIONS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS_COUNT,
    SUM(NVL(SHARES_COUNT,0)) AS SHARES_COUNT, SUM(NVL(POST_LINK_CLICKS,0)) AS POST_LINK_CLICKS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, SUM(NVL(VIDEO_VIEW_TIME,0)) AS VIDEO_VIEW_TIME,
    SUM(NVL(VIDEO_VIEWS_UNIQUE,0)) AS VIDEO_VIEWS_UNIQUE,
    0 AS REPOST, 0 AS LIKES, 0 AS APP_ENGAGEMENTS, 0 AS WEBSITE_CLICKS, 0 AS POST_CLICKS,
    0 AS FOLLOWERS, 0 AS NET_FOLLOWER_GROWTH, 0 AS POST_SENT,
    SUM(NVL(PROFILE_VIEWS,0)) AS PROFILE_VIEWS, 0 AS PUBISHED_POST, 0 AS REACH
FROM {{ ref('stg_sprout_facebook_profile_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.REPORTING_PERIOD_DAY = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT 'INSTAGRAM' AS SOURCE, A.CUSTOMER_PROFILE_ID, CUST.NAME, REPORTING_PERIOD_DAY,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    SUM(NVL(IMPRESSIONS,0)) AS IMPRESSIONS, 0 AS POST_IMPRESSIONS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS_COUNT,
    SUM(NVL(SHARES_COUNT,0)) AS SHARES_COUNT, 0 AS POST_LINK_CLICKS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, 0 AS VIDEO_VIEW_TIME, 0 AS VIDEO_VIEWS_UNIQUE,
    0 AS REPOST, SUM(NVL(LIKES,0)) AS LIKES, 0 AS APP_ENGAGEMENTS,
    SUM(NVL(WEBSITE_CLICKS,0)) AS WEBSITE_CLICKS, 0 AS POST_CLICKS,
    SUM(NVL(LIFETIME_SNAPSHOT_FOLLOWERS_COUNT,0)) AS FOLLOWERS,
    SUM(NVL(NET_FOLLOWER_GROWTH,0)) AS NET_FOLLOWER_GROWTH, 0 AS POST_SENT,
    SUM(NVL(PROFILE_VIEWS_UNIQUE,0)) AS PROFILE_VIEWS,
    SUM(NVL(POSTS_SENT_BY_POST_TYPE,0)) AS PUBISHED_POST,
    SUM(NVL(IMPRESSIONS_UNIQUE,0)) AS REACH
FROM {{ ref('stg_sprout_instagram_profile_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.REPORTING_PERIOD_DAY = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT 'LINKEDIN' AS SOURCE, A.CUSTOMER_PROFILE_ID, CUST.NAME, REPORTING_PERIOD_DAY,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    SUM(NVL(IMPRESSIONS,0)) AS IMPRESSIONS, 0 AS POST_IMPRESSIONS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS_COUNT,
    SUM(NVL(SHARES_COUNT,0)) AS SHARES_COUNT, 0 AS POST_LINK_CLICKS,
    0 AS VIDEO_VIEWS, 0 AS VIDEO_VIEW_TIME, 0 AS VIDEO_VIEWS_UNIQUE,
    0 AS REPOST, 0 AS LIKES, 0 AS APP_ENGAGEMENTS, 0 AS WEBSITE_CLICKS,
    SUM(NVL(POST_CONTENT_CLICKS,0)) AS POST_CLICKS,
    SUM(NVL(FOLLOWERS_COUNT,0)) AS FOLLOWERS,
    SUM(NVL(NET_FOLLOWER_GROWTH,0)) AS NET_FOLLOWER_GROWTH,
    SUM(NVL(POSTS_SENT_COUNT,0)) AS POST_SENT, 0 AS PROFILE_VIEWS, 0 AS PUBISHED_POST,
    SUM(NVL(IMPRESSIONS_UNIQUE,0)) AS REACH
FROM {{ ref('stg_sprout_linkedin_profile_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.REPORTING_PERIOD_DAY = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT 'YOUTUBE' AS SOURCE, A.CUSTOMER_PROFILE_ID, CUST.NAME, REPORTING_PERIOD_DAY,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    0 AS IMPRESSIONS, 0 AS POST_IMPRESSIONS, 0 AS REACTIONS, 0 AS COMMENTS_COUNT,
    0 AS SHARES_COUNT, 0 AS POST_LINK_CLICKS, 0 AS VIDEO_VIEWS, 0 AS VIDEO_VIEW_TIME,
    0 AS VIDEO_VIEWS_UNIQUE, 0 AS REPOST, 0 AS LIKES, 0 AS APP_ENGAGEMENTS,
    0 AS WEBSITE_CLICKS, 0 AS POST_CLICKS,
    SUM(NVL(FOLLOWERS_COUNT,0)) AS FOLLOWERS,
    SUM(NVL(NET_FOLLOWER_GROWTH,0)) AS NET_FOLLOWER_GROWTH,
    SUM(NVL(POSTS_SENT_COUNT,0)) AS POST_SENT, 0 AS PROFILE_VIEWS, 0 AS PUBISHED_POST, 0 AS REACH
FROM {{ ref('stg_sprout_youtube_profile_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.REPORTING_PERIOD_DAY = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT 'TIKTOK' AS SOURCE, A.CUSTOMER_PROFILE_ID, CUST.NAME, REPORTING_PERIOD_DAY,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    0 AS IMPRESSIONS, 0 AS POST_IMPRESSIONS, 0 AS REACTIONS,
    SUM(NVL(COMMENTS_COUNT_TOTAL,0)) AS COMMENTS_COUNT,
    SUM(NVL(SHARES_COUNT_TOTAL,0)) AS SHARES_COUNT, 0 AS POST_LINK_CLICKS,
    SUM(NVL(VIDEO_VIEWS_TOTAL,0)) AS VIDEO_VIEWS, 0 AS VIDEO_VIEW_TIME,
    0 AS VIDEO_VIEWS_UNIQUE, 0 AS REPOST, SUM(NVL(LIKES_TOTAL,0)) AS LIKES,
    0 AS APP_ENGAGEMENTS, 0 AS WEBSITE_CLICKS, 0 AS POST_CLICKS,
    0 AS FOLLOWERS, 0 AS NET_FOLLOWER_GROWTH, 0 AS POST_SENT,
    SUM(NVL(PROFILE_VIEWS_TOTAL,0)) AS PROFILE_VIEWS,
    SUM(NVL(POSTS_SENT_BY_POST_TYPE,0)) AS PUBISHED_POST, 0 AS REACH
FROM {{ ref('stg_sprout_tiktok_profile_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.REPORTING_PERIOD_DAY = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL
