-- =============================================================================
-- LAYER  : Gold — Business Facts
-- MODEL  : fact_sprout_post_data
-- UPSTREAM: Silver bronze models (stg_sprout_*_post_data) + dim_sprout_customer
--           + dim_sprout_date_hierarchy
-- NOTES  : Union of all platform post metrics with fiscal calendar enrichment
--          Replaces old FACT_SPROUT_POST_DATA.sql
-- =============================================================================

{% set db_properties = get_dbproperties('SPROUT_API_INGESTION') %}

{{ config(
    database = db_properties['database'],
    schema   = db_properties['schema'],
    materialized = 'table',
    tags = [var('TAG_SPROUT_API_INGESTION'), var('TAG_SPROUT_FACT_INGESTION')],
    post_hook = [
        "GRANT SELECT ON ALL TABLES IN SCHEMA PROD.SPROUT TO ROLE BSM_MOT_ANALYST; "
    ]
) }}

WITH DATE_TIME_HIERARCHY AS (
    SELECT * FROM {{ ref('dim_sprout_date_hierarchy') }}
),

CUSTOMER_DATA AS (
    SELECT DISTINCT CUSTOMER_PROFILE_ID, NAME
    FROM {{ ref('dim_sprout_customer') }}
)

SELECT A.CUSTOMER_PROFILE_ID, CUST.NAME, CREATED_TIME,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    POST_TYPE, NETWORK, LONG_URL, SHORT_URL, HASHTAGS, TAGS,
    SUM(NVL(POST_CONTENT_CLICKS,0)+NVL(POST_CONTENT_CLICKS_OTHER,0)+NVL(POST_DETAIL_EXPAND_CLICKS,0)
        +NVL(POST_HASHTAG_CLICKS,0)+NVL(POST_LINK_CLICKS,0)+NVL(POST_MEDIA_CLICKS,0)
        +NVL(POST_PROFILE_CLICKS,0))                     AS CLICKS,
    SUM(NVL(REACTIONS,0))                                AS REACTIONS,
    SUM(NVL(SHARES_COUNT,0))                             AS SHARES,
    SUM(NVL(LIKES,0))                                    AS LIKES,
    SUM(NVL(COMMENTS_COUNT,0))                           AS COMMENTS,
    SUM(NVL(VIDEO_VIEWS,0))                              AS VIDEO_VIEWS,
    SUM(NVL(IMPRESSIONS,0))                              AS IMPRESSIONS,
    0 AS DISLIKES, 0 AS SAVES
FROM {{ ref('stg_sprout_twitter_post_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.CREATED_TIME::DATE = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT A.CUSTOMER_PROFILE_ID, CUST.NAME, CREATED_TIME,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    POST_TYPE, NETWORK, LONG_URL, SHORT_URL, HASHTAGS, TAGS,
    SUM(NVL(POST_CONTENT_CLICKS,0)+NVL(POST_CONTENT_CLICKS_OTHER,0)+NVL(POST_LINK_CLICKS,0)
        +NVL(POST_OTHER_CLICKS_UNIQUE,0)+NVL(POST_PHOTO_VIEW_CLICKS,0)+NVL(POST_VIDEO_PLAY_CLICKS,0)) AS CLICKS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(SHARES_COUNT,0)) AS SHARES,
    SUM(NVL(LIKES,0)) AS LIKES, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, SUM(NVL(IMPRESSIONS,0)) AS IMPRESSIONS,
    0 AS DISLIKES, 0 AS SAVES
FROM {{ ref('stg_sprout_facebook_post_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.CREATED_TIME::DATE = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT A.CUSTOMER_PROFILE_ID, CUST.NAME, CREATED_TIME,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    POST_TYPE, NETWORK, LONG_URL, SHORT_URL, HASHTAGS, TAGS,
    SUM(NVL(LINK_IN_BIO_CLICKS,0)) AS CLICKS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(SHARES_COUNT,0)) AS SHARES,
    SUM(NVL(LIKES,0)) AS LIKES, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, SUM(NVL(IMPRESSIONS,0)) AS IMPRESSIONS,
    0 AS DISLIKES, SUM(NVL(SAVES,0)) AS SAVES
FROM {{ ref('stg_sprout_instagram_post_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.CREATED_TIME::DATE = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT A.CUSTOMER_PROFILE_ID, CUST.NAME, CREATED_TIME,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    POST_TYPE, NETWORK, LONG_URL, SHORT_URL, HASHTAGS, TAGS,
    SUM(NVL(POST_CONTENT_CLICKS,0)) AS CLICKS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(SHARES_COUNT,0)) AS SHARES,
    SUM(NVL(LIKES,0)) AS LIKES, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, SUM(NVL(IMPRESSIONS,0)) AS IMPRESSIONS,
    0 AS DISLIKES, 0 AS SAVES
FROM {{ ref('stg_sprout_linkedin_post_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.CREATED_TIME::DATE = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT A.CUSTOMER_PROFILE_ID, CUST.NAME, CREATED_TIME,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    POST_TYPE, NETWORK, LONG_URL, SHORT_URL, HASHTAGS, TAGS,
    SUM(NVL(CARD_CLICKS,0)+NVL(CARD_TEASER_CLICKS,0)) AS CLICKS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(SHARES_COUNT,0)) AS SHARES,
    SUM(NVL(LIKES,0)) AS LIKES, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, SUM(NVL(CARD_IMPRESSIONS,0)) AS IMPRESSIONS,
    SUM(NVL(DISLIKES,0)) AS DISLIKES, 0 AS SAVES
FROM {{ ref('stg_sprout_youtube_post_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.CREATED_TIME::DATE = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL

UNION

SELECT A.CUSTOMER_PROFILE_ID, CUST.NAME, CREATED_TIME,
    FISCAL_YEAR_WEEK_NUMBER, FISCAL_YEAR_MONTH_NUMBER, FISCAL_YEAR_MONTH_NAME,
    FISCAL_YEAR_QUARTER_NAME, FISCAL_YEAR_NUMBER,
    POST_TYPE, NETWORK, LONG_URL, SHORT_URL, HASHTAGS, TAGS,
    SUM(NVL(POST_CONTENT_CLICKS,0)) AS CLICKS,
    SUM(NVL(REACTIONS,0)) AS REACTIONS, SUM(NVL(SHARES_COUNT,0)) AS SHARES,
    SUM(NVL(LIKES,0)) AS LIKES, SUM(NVL(COMMENTS_COUNT,0)) AS COMMENTS,
    SUM(NVL(VIDEO_VIEWS,0)) AS VIDEO_VIEWS, SUM(NVL(VIDEO_VIEWS,0)) AS IMPRESSIONS,
    0 AS DISLIKES, 0 AS SAVES
FROM {{ ref('stg_sprout_tiktok_post_data') }} A
LEFT JOIN DATE_TIME_HIERARCHY B ON A.CREATED_TIME::DATE = B.CALENDAR_DATE
LEFT JOIN CUSTOMER_DATA CUST    ON A.CUSTOMER_PROFILE_ID = CUST.CUSTOMER_PROFILE_ID
GROUP BY ALL
