-- =============================================================================
-- LAYER  : Gold — Business Fact
-- MODEL  : fact_clm_avg_time_to_use
-- NOTES  : CLM gold fact; var() references preserved — convert to source() as sources.yml is expanded
-- =============================================================================

{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('ffm') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the Pre Hook configuration #}
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT DATE_TRUNC(MONTH, DATEADD(MONTH,-16,CURRENT_DATE()))); ",
        "SET END_DATE   = (SELECT CURRENT_DATE()-1); "
    ]
  )
}}

{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_CJO_READONLY",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST"
    ]
  )
}}



WITH PERSON AS
(
  SELECT DISTINCT OXYGEN_ID
    , ACCOUNT_CSN
  FROM {{ var('CORE_ENTERPRISE_DATA_SHARED.PERSON') }}
),

USAGE_SUS_DAILY AS
(
  SELECT DISTINCT A.OXYGEN_ID
    , COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.ACCOUNT_CSN) AS ACCOUNT_CSN
    , A.TENANT_ID
    , A.POOL_ID
    , A.SUBSCRIPTION_ID
    , A.OFFERING_PRODUCT_LINE_CODE
    , A.USAGE_DATE
  FROM {{ var('USAGE_SUS_DAILY') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE A.USAGE_DATE BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE)
),

USER_ASSIGNMENT_AUM AS
(
  SELECT DISTINCT USER_ID
    , TENANT_ID
    , POOL_ID
    , USER_ASSIGNMENTS_GRANTED_TIMESTAMP::DATE AS USER_ASSIGNMENTS_GRANTED_TIMESTAMP
  FROM {{ var('USER_ASSIGNMENT_AUM') }}
  WHERE USER_ASSIGNMENTS_GRANTED_TIMESTAMP::DATE BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE)
  AND REPLACE(POOL_ID,'1_','') = ENTITLEMENT_ID
)

SELECT DISTINCT ACCOUNT_CSN::VARCHAR AS ACCOUNT_CSN
  , TENANT_ID::VARCHAR AS TENANT_ID
  , POOL_ID
  , SUBSCRIPTION_ID
  , OFFERING_PRODUCT_LINE_CODE
  , AVG(DATEDIFF(DAY, USER_ASSIGNMENTS_GRANTED_TIMESTAMP::DATE, USAGE_DATE::DATE)) AS AVG_TIME_TO_USE_DAYS
FROM (
  SELECT DISTINCT USER_ID
    , ACCOUNT_CSN
    , TENANT_ID
    , POOL_ID
    , SUBSCRIPTION_ID
    , OFFERING_PRODUCT_LINE_CODE
    , USER_ASSIGNMENTS_GRANTED_TIMESTAMP
    , MIN(USAGE_DATE::DATE) AS USAGE_DATE
  FROM (
    SELECT DISTINCT A.USER_ID
      , COALESCE(B.ACCOUNT_CSN, PER.ACCOUNT_CSN) AS ACCOUNT_CSN
      , A.TENANT_ID
      , A.POOL_ID
      , B.SUBSCRIPTION_ID
      , B.OFFERING_PRODUCT_LINE_CODE
      , A.USER_ASSIGNMENTS_GRANTED_TIMESTAMP::DATE AS USER_ASSIGNMENTS_GRANTED_TIMESTAMP
      , B.USAGE_DATE::DATE AS USAGE_DATE
    FROM USER_ASSIGNMENT_AUM A
    LEFT JOIN USAGE_SUS_DAILY B
      ON A.USER_ID = B.OXYGEN_ID
      AND A.TENANT_ID = B.TENANT_ID
      AND A.POOL_ID = B.POOL_ID
    LEFT JOIN PERSON PER
      ON A.USER_ID = PER.OXYGEN_ID
    WHERE B.USAGE_DATE >= A.USER_ASSIGNMENTS_GRANTED_TIMESTAMP
  )
  GROUP BY ALL
)
WHERE OFFERING_PRODUCT_LINE_CODE NOT IN ('BIMCOLL', 'BLDUNLT', 'B36FP', 'QNTFY', 'ATOSPCS', 'BIM360C', 'BLD550', 'BM36PP', 'BM36DP', 'DOCS', 'COLLRP', 'BLD5K')
GROUP BY 1,2,3,4,5

