-- =============================================================================
-- LAYER  : Gold — Business Fact
-- MODEL  : fact_clm_active_users
-- NOTES  : CLM gold fact; var() references preserved — convert to source() as sources.yml is expanded
-- =============================================================================

{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('ffm') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_DUMMY')]) }}

{# Set the Pre Hook configuration #}
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT DATE_TRUNC(MONTH, DATEADD(MONTH,-16,CURRENT_DATE()))); ",
        "SET END_DATE   = (SELECT CURRENT_DATE()-1); "
    ]
  )
}}

{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_CJO_READONLY",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST"
    ]
  )
}}


WITH DATE_TIME_HIERARCHY AS
(
    SELECT DISTINCT DATE_KEY AS CALENDAR_DATE
      , WEEK_NUMBER_FISCAL_QUARTER
      , MONTH_NUMBER_IN_FISCAL_YEAR
      , MONTH_AND_FISCAL_YEAR_NAME
      , MONTH_AND_CURRENT_YEAR_NAME
      , FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
      , FISCAL_YEAR_NAME
    FROM {{ ref('DIM_CLM_DATETIME') }}
),

ASSIGNMENT_DAILY AS
(
  SELECT DISTINCT COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.ACCOUNT_CSN) AS ACCOUNT_CSN
    , A.TENANT_ID
    , A.POOL_ID
    , A.SUBSCRIPTION_ID
    , A.OFFERING_PRODUCT_LINE_CODE
  FROM {{ var('ASSIGNMENT_DAILY') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE ENTITLEMENT_START_DATE >= TO_DATE($START_DATE)
    AND ENTITLEMENT_END_DATE >= CURRENT_DATE
),

USAGE_SUS_DAILY AS
(
  SELECT DISTINCT COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.ACCOUNT_CSN) AS ACCOUNT_CSN
    , A.TENANT_ID
    , A.POOL_ID
    , A.SUBSCRIPTION_ID
    , A.OFFERING_PRODUCT_LINE_CODE
    , A.USAGE_DATE
    , A.OXYGEN_ID
  FROM {{ var('USAGE_SUS_DAILY') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE A.USAGE_DATE BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE)
),

ACTIVE_USERS AS
(
  SELECT DISTINCT A.ACCOUNT_CSN
    , A.TENANT_ID
    , A.POOL_ID
    , A.SUBSCRIPTION_ID
    , A.OFFERING_PRODUCT_LINE_CODE
    , A.USAGE_DATE
    , A.OXYGEN_ID
  FROM USAGE_SUS_DAILY A
  INNER JOIN ASSIGNMENT_DAILY B
    ON A.ACCOUNT_CSN = B.ACCOUNT_CSN
    AND A.TENANT_ID = B.TENANT_ID
    AND A.POOL_ID = B.POOL_ID
    AND A.SUBSCRIPTION_ID = B.SUBSCRIPTION_ID
    AND A.OFFERING_PRODUCT_LINE_CODE = B.OFFERING_PRODUCT_LINE_CODE
),

EDH_FINANCE AS
(
  SELECT DISTINCT COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.CORPORATE_CSN) AS CORPORATE_CSN
    , A.SAP_PRODUCT_LINE
    , A.CC_FBD_BSM_ORDER_ACTION
    , ROW_NUMBER() OVER(PARTITION BY COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.CORPORATE_CSN), A.SAP_PRODUCT_LINE ORDER BY A.TRANSACTION_DT DESC NULLS LAST) RNK
  FROM {{ var('FINMART_PRIVATE_DATA') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.CORPORATE_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.CORPORATE_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE UPPER(A.RECORD_TYPE) IN ('BILLING', 'BOOKING_BILLING')
    AND UPPER(A.CC_FBD_BIL_TERM_DAYS) <> 'NA'
    AND NOT (UPPER(A.SALES_ORDER_REASON) LIKE '%TEST ORDER%' OR UPPER(A.SALES_ORDER_REASON) LIKE '%TRIAL%')
    AND NOT (UPPER(A.PO_NBR) LIKE '%TEST%')
    AND (A.SETTLEMENT_END_DT >= CAST(A.TRANSACTION_DT AS DATE))
    AND A.CC_ACTIVE_END_DT >= A.TRANSACTION_DT
    AND A.TRANSACTION_DT >= TO_DATE($START_DATE)
  QUALIFY RNK = 1
),

PERSON AS
(
  SELECT DISTINCT PERSON_MDM_ID
    , OXYGEN_ID
  FROM {{ var('CORE_ENTERPRISE_DATA_SHARED.PERSON') }}
),

CONTACT_HISTORY AS
(
  SELECT DISTINCT CONTACT_UUID_CSN
    , JOURNEY_NAME
    , REGEXP_SUBSTR(SUBSTR(JOURNEY_NAME, 1, 7), '^[0-9]{7}$') AS TACTIC_ID
  FROM {{ var('CONTACT_HISTORY') }}
  WHERE TRY_TO_NUMBER(SUBSTRING(JOURNEY_NAME, 1, 7)) = TRUE
),

CMT_CAMPAIGN AS
(
  SELECT DISTINCT ALLOCADIA_ID__C AS ALLOCADIA_ID
    , MARKETING_EXECUTION_TEAM__C AS MARKETING_EXECUTION_TEAM
    , NAME AS CMT_CAMPAIGN_NAME 
  FROM {{ var('SFDC_SHARED.CAMPAIGN') }}
  WHERE MARKETING_EXECUTION_TEAM__C ='AGM-ILM'
),

CUSTOMER_PHASES AS
(
  SELECT DISTINCT PARENT_CSN
    , CUSTOMER_PHASE_START_DATE
    , CUSTOMER_PHASE_END_DATE
    , CUSTOMER_PHASE
  FROM {{ var('CUSTOMER_PHASES') }}
  WHERE CUSTOMER_PHASE_END_DATE >= CURRENT_DATE()
),

TEST_CONTROL AS
(
  SELECT DISTINCT COALESCE(D.ACCOUNT_CSN__C, E.ACCOUNT_CSN__C, A.ACCOUNT_CSN__C) AS ACCOUNT_CSN__C
    , SEMI_RANDOM_DIGIT
  FROM {{ var('ILM_ACCOUNTS') }} A
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN__C = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN__C = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE SEMI_RANDOM_DIGIT= 1
),

MAU AS
(
  SELECT DISTINCT USR.ACCOUNT_CSN
    , USR.TENANT_ID
    , USR.POOL_ID
    , COALESCE(USR.OFFERING_PRODUCT_LINE_CODE, '') AS PRODUCT_LINE_CODE
    , USR.SUBSCRIPTION_ID
    , USR.USAGE_DATE
    , E.CC_FBD_BSM_ORDER_ACTION AS SEAT_TYPE
    , F.CUSTOMER_PHASE
    , CMT.CMT_CAMPAIGN_NAME
    , CMT.MARKETING_EXECUTION_TEAM
    , CASE WHEN TC.ACCOUNT_CSN__C IS NOT NULL THEN 'Control' ELSE 'Test' END AS TEST_CONTROL_FLAG
    , CAL.MONTH_AND_FISCAL_YEAR_NAME
    , CAL.MONTH_AND_CURRENT_YEAR_NAME
    , USR.OXYGEN_ID
    
  FROM ACTIVE_USERS USR
  LEFT JOIN {{ ref('DIM_CLM_ACCOUNT_ATTRIBUTIONS') }} ACC
    ON USR.ACCOUNT_CSN = ACC.ACCOUNT_CSN
  LEFT JOIN EDH_FINANCE E
    ON USR.ACCOUNT_CSN = E.CORPORATE_CSN
    AND REPLACE(USR.POOL_ID, '1_','') = UPPER(E.SAP_PRODUCT_LINE)
  LEFT JOIN CUSTOMER_PHASES F
    ON ACC.PARENT_ACCOUNT_CSN  = F.PARENT_CSN
    AND USR.USAGE_DATE BETWEEN F.CUSTOMER_PHASE_START_DATE AND F.CUSTOMER_PHASE_END_DATE
  LEFT JOIN PERSON B
    ON USR.OXYGEN_ID = B.OXYGEN_ID
  LEFT JOIN CONTACT_HISTORY UCH
    ON B.PERSON_MDM_ID = UCH.CONTACT_UUID_CSN
  LEFT JOIN CMT_CAMPAIGN CMT
    ON UCH.TACTIC_ID = CMT.ALLOCADIA_ID
  LEFT JOIN TEST_CONTROL TC
    ON USR.ACCOUNT_CSN = TC.ACCOUNT_CSN__C
  LEFT JOIN DATE_TIME_HIERARCHY CAL
    ON USR.USAGE_DATE = CAL.CALENDAR_DATE

  WHERE CMT.CMT_CAMPAIGN_NAME IS NOT NULL
)

SELECT DISTINCT MONTH_AND_FISCAL_YEAR_NAME
  , MONTH_AND_CURRENT_YEAR_NAME
  , PRODUCT_LINE_CODE
  , ACCOUNT_CSN::VARCHAR AS ACCOUNT_CSN
  , CUSTOMER_PHASE
  , SEAT_TYPE
  , CMT_CAMPAIGN_NAME
  , TEST_CONTROL_FLAG
  , CASE 
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'ALL_NOT_NULL'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL THEN 'PRODUCT_LINE_CODE, ACCOUNT_CSN, CUSTOMER_PHASE, SEAT_TYPE Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'PRODUCT_LINE_CODE, ACCOUNT_CSN, CUSTOMER_PHASE, CMT_CAMPAIGN_NAME Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL AND SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'PRODUCT_LINE_CODE, ACCOUNT_CSN, SEAT_TYPE, CMT_CAMPAIGN_NAME Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'PRODUCT_LINE_CODE, CUSTOMER_PHASE, SEAT_TYPE, CMT_CAMPAIGN_NAME Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'ACCOUNT_CSN, CUSTOMER_PHASE, SEAT_TYPE, CMT_CAMPAIGN_NAME Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL THEN 'PRODUCT_LINE_CODE, ACCOUNT_CSN, CUSTOMER_PHASE Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL AND SEAT_TYPE IS NOT NULL THEN 'PRODUCT_LINE_CODE, ACCOUNT_CSN, SEAT_TYPE Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'PRODUCT_LINE_CODE, ACCOUNT_CSN, CMT_CAMPAIGN_NAME Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL THEN 'PRODUCT_LINE_CODE, CUSTOMER_PHASE, SEAT_TYPE Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'PRODUCT_LINE_CODE, CUSTOMER_PHASE, CMT_CAMPAIGN_NAME Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'PRODUCT_LINE_CODE, SEAT_TYPE, CMT_CAMPAIGN_NAME Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL THEN 'ACCOUNT_CSN, CUSTOMER_PHASE, SEAT_TYPE Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'ACCOUNT_CSN, CUSTOMER_PHASE, CMT_CAMPAIGN_NAME Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL AND SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'ACCOUNT_CSN, SEAT_TYPE, CMT_CAMPAIGN_NAME Not Null'
        WHEN CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'CUSTOMER_PHASE, SEAT_TYPE, CMT_CAMPAIGN_NAME Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND ACCOUNT_CSN IS NOT NULL THEN 'PRODUCT_LINE_CODE, ACCOUNT_CSN Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL THEN 'PRODUCT_LINE_CODE, CUSTOMER_PHASE Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND SEAT_TYPE IS NOT NULL THEN 'PRODUCT_LINE_CODE, SEAT_TYPE Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'PRODUCT_LINE_CODE, CMT_CAMPAIGN_NAME Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL AND CUSTOMER_PHASE IS NOT NULL THEN 'ACCOUNT_CSN, CUSTOMER_PHASE Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL AND SEAT_TYPE IS NOT NULL THEN 'ACCOUNT_CSN, SEAT_TYPE Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'ACCOUNT_CSN, CMT_CAMPAIGN_NAME Not Null'
        WHEN CUSTOMER_PHASE IS NOT NULL AND SEAT_TYPE IS NOT NULL THEN 'CUSTOMER_PHASE, SEAT_TYPE Not Null'
        WHEN CUSTOMER_PHASE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'CUSTOMER_PHASE, CMT_CAMPAIGN_NAME Not Null'
        WHEN SEAT_TYPE IS NOT NULL AND CMT_CAMPAIGN_NAME IS NOT NULL THEN 'SEAT_TYPE, CMT_CAMPAIGN_NAME Not Null'
        WHEN PRODUCT_LINE_CODE IS NOT NULL THEN 'PRODUCT_LINE_CODE Not Null'
        WHEN ACCOUNT_CSN IS NOT NULL THEN 'ACCOUNT_CSN Not Null'
        WHEN CUSTOMER_PHASE IS NOT NULL THEN 'CUSTOMER_PHASE Not Null'
        WHEN SEAT_TYPE IS NOT NULL THEN 'SEAT_TYPE Not Null'
        WHEN CMT_CAMPAIGN_NAME IS NOT NULL THEN 'CMT_CAMPAIGN_NAME Not Null'
        ELSE 'ALL_NULL'
    END AS NULL_VALUE_COMBINATIONS
  , COUNT(DISTINCT OXYGEN_ID) AS MAU
  
FROM MAU
WHERE CMT_CAMPAIGN_NAME != '6836613_Cross-Ind_KPI_reporting_data_test'
AND PRODUCT_LINE_CODE NOT IN ('BIMCOLL', 'BLDUNLT', 'B36FP', 'QNTFY', 'ATOSPCS', 'BIM360C', 'BLD550', 'BM36PP', 'BM36DP', 'DOCS', 'COLLRP', 'BLD5K')
GROUP BY CUBE (
  PRODUCT_LINE_CODE
  , ACCOUNT_CSN
  , CUSTOMER_PHASE
  , SEAT_TYPE
  , CMT_CAMPAIGN_NAME
)
, MONTH_AND_CURRENT_YEAR_NAME
, MONTH_AND_FISCAL_YEAR_NAME
, TEST_CONTROL_FLAG

