-- =============================================================================
-- LAYER  : Gold — Business Fact
-- MODEL  : fact_clm_renewal_rate
-- NOTES  : CLM gold fact; var() references preserved — convert to source() as sources.yml is expanded
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('ffm') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the Pre Hook configuration #}
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT FISCAL_QUARTER_BEGIN_DATE FROM {{ var('FINANCE_CALENDAR') }} WHERE DATE_KEY = DATE_TRUNC(MONTH, DATEADD(MONTH,-15,CURRENT_DATE()))); ",
        "SET END_DATE   = (SELECT CURRENT_DATE()-1);"
    ]
  )
}}


{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_CJO_READONLY",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST"
    ]
  )
}}


WITH RENEWAL_RATE_SOURCE AS
(
  SELECT DISTINCT   B.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS PERIOD
    , COALESCE(NVL(D.ACCOUNT_CSN__C::VARCHAR, ''), NVL(E.ACCOUNT_CSN__C::VARCHAR, ''), NVL(A.CORPORATE_CSN::VARCHAR, '')) AS ACCOUNT_CSN

    , A.AS_REPORTED_RENEWED_AOV_NET3_CC AS AS_REPORTED_RENEWED_AOV_NET3_CC
    , A.FC_ADJ_RENEWED_AOV_NET3_CC AS FC_ADJ_RENEWED_AOV_NET3_CC
    , A.AOV_UFR_NET3_CC AS AOV_UFR_NET3_CC

    , A.AS_REPORTED_RENEWED_AOV_NET4_CC AS AS_REPORTED_RENEWED_AOV_NET4_CC
    , A.FC_ADJ_RENEWED_AOV_NET4_CC AS FC_ADJ_RENEWED_AOV_NET4_CC
    , A.AOV_UFR_NET4_CC AS AOV_UFR_NET4_CC

    , A.AS_REPORTED_SEATS_RENEWED AS AS_REPORTED_SEATS_RENEWED
    , A.FC_ADJ_SEATS_RENEWED AS FC_ADJ_SEATS_RENEWED
    , A.SEATS_UFR

  FROM {{ var('BMT_FINANCE_METRICS') }} A
  JOIN {{ var('FINANCE_CALENDAR') }} B 
    ON A.SETTLEMENT_START_DT = B.DATE_KEY
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.CORPORATE_CSN = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.CORPORATE_CSN = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE 
    B.DATE_KEY BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE)
),


TEST_CONTROL AS
(
  SELECT DISTINCT COALESCE(NVL(D.ACCOUNT_CSN__C::VARCHAR, ''), NVL(E.ACCOUNT_CSN__C::VARCHAR, ''), NVL(A.ACCOUNT_CSN__C::VARCHAR, '')) AS ACCOUNT_CSN
  FROM {{ var('ILM_ACCOUNTS') }} A
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} D
    ON A.ACCOUNT_CSN__C = D.ACCOUNT_CSN__C
  LEFT JOIN {{ var('EDH_SHARED_HISTORY.ACCOUNT') }} C
    ON A.ACCOUNT_CSN__C = C.ACCOUNT_CSN
  LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} E
    ON C.SURVIVING_ACCOUNT_CSN = E.ACCOUNT_CSN__C
  WHERE SEMI_RANDOM_DIGIT= 1
)


SELECT DISTINCT  A.PERIOD
  , A.ACCOUNT_CSN::VARCHAR AS ACCOUNT_CSN
  , CASE WHEN TC.ACCOUNT_CSN IS NOT NULL THEN 'Control' ELSE 'Test' END AS TEST_CONTROL_FLAG

  , ROUND(DIV0((SUM (AS_REPORTED_RENEWED_AOV_NET3_CC) ), NULLIFZERO(SUM (AOV_UFR_NET3_CC))), 4) AS NON_ADJ_RR_NET3_CC
  , SUM (AS_REPORTED_RENEWED_AOV_NET3_CC)        AS NON_ADJ_AS_REPORTED_RENEWED_AOV_NET3_CC
  , SUM (AOV_UFR_NET3_CC)                        AS AOV_UFR_NET3_CC

  , ROUND(DIV0((SUM (AS_REPORTED_RENEWED_AOV_NET4_CC) ), NULLIFZERO(SUM (AOV_UFR_NET4_CC))), 4) AS NON_ADJ_RR_NET4_CC
  , SUM (AS_REPORTED_RENEWED_AOV_NET4_CC)        AS NON_ADJ_AS_REPORTED_RENEWED_AOV_NET4_CC
  , SUM (AOV_UFR_NET4_CC)                        AS AOV_UFR_NET4_CC

  , ROUND(DIV0((SUM (AS_REPORTED_SEATS_RENEWED) ), NULLIFZERO(SUM (SEATS_UFR))), 4) AS NON_ADJ_RR_SEATS
  , SUM (AS_REPORTED_SEATS_RENEWED)              AS NON_ADJ_AS_REPORTED_SEATS_RENEWED
  , SUM (SEATS_UFR)                              AS SEATS_UFR

  , ROUND(DIV0((SUM (FC_ADJ_RENEWED_AOV_NET3_CC) ), NULLIFZERO(SUM (AOV_UFR_NET3_CC))), 4) AS FC_ADJ_RR_NET3_CC
  , SUM (FC_ADJ_RENEWED_AOV_NET3_CC)             AS FC_ADJ_AS_REPORTED_RENEWED_AOV_NET3_CC

  , ROUND(DIV0((SUM (FC_ADJ_RENEWED_AOV_NET4_CC) ), NULLIFZERO(SUM (AOV_UFR_NET4_CC))), 4) AS FC_ADJ_RR_NET4_CC
  , SUM (FC_ADJ_RENEWED_AOV_NET4_CC)             AS FC_ADJ_AS_REPORTED_RENEWED_AOV_NET4_CC

  , ROUND(DIV0((SUM (FC_ADJ_SEATS_RENEWED) ), NULLIFZERO(SUM (SEATS_UFR))), 4)             AS FC_ADJ_RR_SEATS
  , SUM (FC_ADJ_SEATS_RENEWED)                   AS FC_ADJ_AS_REPORTED_SEATS_RENEWED

FROM RENEWAL_RATE_SOURCE A
LEFT JOIN TEST_CONTROL TC
  ON A.ACCOUNT_CSN = TC.ACCOUNT_CSN
WHERE NVL(A.ACCOUNT_CSN::VARCHAR, '') != ''
GROUP BY 1, 2, 3
HAVING NON_ADJ_RR_NET3_CC > 0
