-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : fact_ffm_sales_mpm_monthly_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Set the right tag
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

WITH DIM_CAL AS (
    SELECT
        DISTINCT
        MONTH_START_DATE,
        MONTH_NUMBER_IN_FISCAL_YEAR,
        PREVIOUS_MONTH_START_DATE,
        FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_QUARTER,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA,
        COMPLETED_WEEKS,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER
    FROM
        {{ ref('FFM_FIN_CALENDAR') }}
    WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
),
CREATED_ACV AS (
    SELECT
        GEO,
        COUNTRY,
        GDPR_FLAG,
        MARKETING_INDUSTRY,
        ACCOUNT_TIER,
        PRODUCT_INDUSTRY,
        PRODUCT_FAMILY,
        OPPORTUNITY_CHANNEL,
        FY_YEAR_QUARTER_CREATED AS FY_QUARTER,
        FY_MONTH_CREATED AS FY_MONTH,
        FY_QUARTER_WEEK_CREATED AS FY_QUARTER_WEEK,
        SUM(MS_CREATED_ACV) AS SALES_MS_CREATED_ACV
    FROM
        {{ ref('FFM_SALES_MPM_ACV') }}
    WHERE
        IFNULL(ACCOUNT_TIER, '') NOT IN ('Named Account Global', 'Named Account')
        AND NOT MS_CREATED_ACV = 0
    GROUP BY ALL
),
CLOSED_ACV AS (
    SELECT
        GEO,
        COUNTRY,
        GDPR_FLAG,
        MARKETING_INDUSTRY,
        ACCOUNT_TIER,
        PRODUCT_INDUSTRY,
        PRODUCT_FAMILY,
        OPPORTUNITY_CHANNEL,
        FY_YEAR_QUARTER_CLOSED AS FY_QUARTER,
        FY_MONTH_CLOSED AS FY_MONTH,
        FY_QUARTER_WEEK_CLOSED AS FY_QUARTER_WEEK,
        SUM(MS_NEW_CUSTOMER_ACV) AS SALES_NEW_CUSTOMER_ACV,
        SUM(MS_NEW_ACV) AS SALES_MS_NEW_ACV,
        COALESCE(SALES_MS_NEW_ACV, 0) - COALESCE(SALES_NEW_CUSTOMER_ACV, 0) AS SALES_EXPANSION_ACV,
        SUM(CASE WHEN PRODUCT_CATEGORIES = 'CORE_PRODUCT' THEN MS_NEW_ACV END) AS SALES_NEW_CORE_ACV,
        SUM(CASE WHEN PRODUCT_CATEGORIES = 'EMERGING_PRODUCT' THEN MS_NEW_ACV END) AS SALES_NEW_EMERGING_ACV
    FROM
        {{ ref('FFM_SALES_MPM_ACV') }}
    WHERE
        IFNULL(ACCOUNT_TIER, '') NOT IN ('Named Account Global', 'Named Account')
        AND NOT (MS_NEW_CUSTOMER_ACV = 0 AND MS_NEW_ACV = 0)
    GROUP BY ALL
),
SALES_UNION AS (
    SELECT
        GEO,
        COUNTRY,
        GDPR_FLAG,
        MARKETING_INDUSTRY,
        ACCOUNT_TIER,
        PRODUCT_INDUSTRY,
        PRODUCT_FAMILY,
        OPPORTUNITY_CHANNEL,
        FY_QUARTER,
        FY_MONTH,
        FY_QUARTER_WEEK,
        NULL AS SALES_NEW_CUSTOMER_ACV,
        NULL AS SALES_MS_NEW_ACV,
        NULL AS SALES_EXPANSION_ACV,
        NULL AS SALES_NEW_CORE_ACV,
        NULL AS SALES_NEW_EMERGING_ACV,
        SALES_MS_CREATED_ACV,
        'CREATED' AS METRIC
    FROM CREATED_ACV
    UNION ALL
    SELECT
        GEO,
        COUNTRY,
        GDPR_FLAG,
        MARKETING_INDUSTRY,
        ACCOUNT_TIER,
        PRODUCT_INDUSTRY,
        PRODUCT_FAMILY,
        OPPORTUNITY_CHANNEL,
        FY_QUARTER,
        FY_MONTH,
        FY_QUARTER_WEEK,
        SALES_NEW_CUSTOMER_ACV,
        SALES_MS_NEW_ACV,
        SALES_EXPANSION_ACV,
        SALES_NEW_CORE_ACV,
        SALES_NEW_EMERGING_ACV,
        NULL AS SALES_MS_CREATED_ACV,
        'CLOSED' AS METRIC
    FROM CLOSED_ACV
),
SALES_BASE AS (
    SELECT
        S.GEO,
        S.COUNTRY,
        S.GDPR_FLAG,
        S.MARKETING_INDUSTRY AS CAMPAIGN_INDUSTRY,
        S.ACCOUNT_TIER AS BUSINESS_TIER,
        S.PRODUCT_INDUSTRY,
        S.PRODUCT_FAMILY,
        S.OPPORTUNITY_CHANNEL AS SALES_CHANNEL,
        S.FY_QUARTER,
        A.MONTH_START_DATE,
        S.FY_QUARTER_WEEK,
        S.SALES_NEW_CUSTOMER_ACV,
        S.SALES_MS_NEW_ACV,
        S.SALES_EXPANSION_ACV,
        S.SALES_NEW_CORE_ACV,
        S.SALES_NEW_EMERGING_ACV,
        S.SALES_MS_CREATED_ACV,
        S.METRIC,
        A.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER
    FROM
        SALES_UNION S
        INNER JOIN DIM_CAL A
        ON A.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = S.FY_QUARTER
        AND A.MONTH_NUMBER_IN_FISCAL_YEAR = S.FY_MONTH
        AND S.FY_QUARTER_WEEK <= A.COMPLETED_WEEKS
),
-- Get last completed week of latest quarter
LAST_COMPLETED_WEEK AS (
    SELECT
        MAX(FY_QUARTER_WEEK) AS LAST_WEEK
    FROM
        SALES_BASE
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = 0
),
SALES_AGG AS (
    SELECT
        GEO,
        COUNTRY,
        GDPR_FLAG,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        PRODUCT_INDUSTRY,
        PRODUCT_FAMILY,
        SALES_CHANNEL,
        FY_QUARTER,
        MONTH_START_DATE,
        METRIC,
        SUM(SALES_NEW_CUSTOMER_ACV) AS SALES_NEW_CUSTOMER_ACV,
        SUM(SALES_MS_NEW_ACV) AS SALES_MS_NEW_ACV,
        SUM(SALES_EXPANSION_ACV) AS SALES_EXPANSION_ACV,
        SUM(SALES_NEW_CORE_ACV) AS SALES_NEW_CORE_ACV,
        SUM(SALES_NEW_EMERGING_ACV) AS SALES_NEW_EMERGING_ACV,
        SUM(SALES_MS_CREATED_ACV) AS SALES_MS_CREATED_ACV
    FROM
        SALES_BASE
    GROUP BY
        ALL
),
PQTD_PYQTD AS (
    SELECT
        GEO,
        COUNTRY,
        GDPR_FLAG,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        PRODUCT_INDUSTRY,
        PRODUCT_FAMILY,
        SALES_CHANNEL,
        FY_QUARTER,
        MONTH_START_DATE,
        METRIC,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        SUM(SALES_NEW_CUSTOMER_ACV) AS SALES_NEW_CUSTOMER_ACV,
        SUM(SALES_MS_NEW_ACV) AS SALES_MS_NEW_ACV,
        SUM(SALES_EXPANSION_ACV) AS SALES_EXPANSION_ACV,
        SUM(SALES_NEW_CORE_ACV) AS SALES_NEW_CORE_ACV,
        SUM(SALES_NEW_EMERGING_ACV) AS SALES_NEW_EMERGING_ACV,
        SUM(SALES_MS_CREATED_ACV) AS SALES_MS_CREATED_ACV
    FROM
        SALES_BASE
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER IN (-1, -4)
        AND FY_QUARTER_WEEK <= (SELECT LAST_WEEK FROM LAST_COMPLETED_WEEK) 
        -- Fetch Prev. QTR & Prev. Yr. QTR till last completed week of current quarter
    GROUP BY
        ALL
),
DIMENSIONS AS (
    SELECT
        DISTINCT GEO,
        COUNTRY,
        GDPR_FLAG,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        PRODUCT_INDUSTRY,
        PRODUCT_FAMILY,
        SALES_CHANNEL,
        METRIC
    FROM
        SALES_BASE
),
DIM_COMBINATIONS_QTRS AS (
    SELECT
        DISTINCT CAL.*,
        DIM.*
    FROM
        DIM_CAL CAL
        CROSS JOIN DIMENSIONS DIM
),
FINAL AS (
    SELECT
        'LOWER' AS FUNNEL,
        'SALES' AS METRIC_GROUP,
        DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.FISCAL_QUARTER_BEGIN_DATE,
        DIM.MONTH_START_DATE,
        DIM.PREVIOUS_MONTH_START_DATE,
        DIM.PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.PREVIOUS_FISCAL_YEAR_QUARTER,
        DIM.PREVIOUS_FISCAL_QUARTER_NAME,
        DIM.IS_CURRENT_QUARTER,
        IFF(COALESCE(BASE.METRIC, PQ.METRIC, PYQ.METRIC) = 'CLOSED', DIM.IS_RESTRICTED_DATA, 0) AS IS_RESTRICTED_DATA,
        DIM.COMPLETED_WEEKS,
        DIM.GEO,
        DIM.COUNTRY,
        DIM.GDPR_FLAG,
        DIM.CAMPAIGN_INDUSTRY,
        DIM.BUSINESS_TIER,
        DIM.PRODUCT_FAMILY,
        DIM.PRODUCT_INDUSTRY,
        DIM.SALES_CHANNEL,
        --Base metrics
        SUM(BASE.SALES_NEW_CUSTOMER_ACV) AS SALES_NEW_CUSTOMER_ACV,
        SUM(BASE.SALES_MS_NEW_ACV) AS SALES_MS_NEW_ACV,
        SUM(BASE.SALES_EXPANSION_ACV) AS SALES_EXPANSION_ACV,
        SUM(BASE.SALES_NEW_CORE_ACV) AS SALES_NEW_CORE_ACV,
        SUM(BASE.SALES_NEW_EMERGING_ACV) AS SALES_NEW_EMERGING_ACV,
        SUM(BASE.SALES_MS_CREATED_ACV) AS SALES_MS_CREATED_ACV,
        --PQTD metrics
        SUM(PQ.SALES_NEW_CUSTOMER_ACV) AS SALES_PQTD_NEW_CUSTOMER_ACV,
        SUM(PQ.SALES_MS_NEW_ACV) AS SALES_PQTD_MS_NEW_ACV,
        SUM(PQ.SALES_EXPANSION_ACV) AS SALES_PQTD_EXPANSION_ACV,
        SUM(PQ.SALES_NEW_CORE_ACV) AS SALES_PQTD_NEW_CORE_ACV,
        SUM(PQ.SALES_NEW_EMERGING_ACV) AS SALES_PQTD_NEW_EMERGING_ACV,
        SUM(PQ.SALES_MS_CREATED_ACV) AS SALES_PQTD_MS_CREATED_ACV,
        --PYQTD metrics
        SUM(PYQ.SALES_NEW_CUSTOMER_ACV) AS SALES_PYQTD_NEW_CUSTOMER_ACV,
        SUM(PYQ.SALES_MS_NEW_ACV) AS SALES_PYQTD_MS_NEW_ACV,
        SUM(PYQ.SALES_EXPANSION_ACV) AS SALES_PYQTD_EXPANSION_ACV,
        SUM(PYQ.SALES_NEW_CORE_ACV) AS SALES_PYQTD_NEW_CORE_ACV,
        SUM(PYQ.SALES_NEW_EMERGING_ACV) AS SALES_PYQTD_NEW_EMERGING_ACV,
        SUM(PYQ.SALES_MS_CREATED_ACV) AS SALES_PYQTD_MS_CREATED_ACV,
        CURRENT_TIMESTAMP AS RUN_TIMESTAMP
    FROM
        DIM_COMBINATIONS_QTRS DIM
        -- Join at all dimensions
        LEFT JOIN SALES_AGG BASE 
        ON BASE.FY_QUARTER = DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND BASE.MONTH_START_DATE = DIM.MONTH_START_DATE
        AND COALESCE(BASE.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(BASE.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(BASE.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(BASE.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(BASE.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(BASE.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(BASE.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(BASE.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(BASE.METRIC, '') = COALESCE(DIM.METRIC, '')
        -- Join Previous QTD data
        LEFT JOIN PQTD_PYQTD PQ 
        ON PQ.FY_QUARTER = DIM.PREVIOUS_FISCAL_QUARTER_NAME
        AND PQ.MONTH_START_DATE = DATEADD(MONTH, -3, DIM.MONTH_START_DATE)
        AND COALESCE(PQ.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(PQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(PQ.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(PQ.METRIC, '') = COALESCE(DIM.METRIC, '')
        AND PQ.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = -1
        -- Join Previous Year QTD data
        LEFT JOIN PQTD_PYQTD PYQ 
        ON PYQ.FY_QUARTER = DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND PYQ.MONTH_START_DATE = DATEADD(MONTH, -12, DIM.MONTH_START_DATE)
        AND COALESCE(PYQ.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(PYQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PYQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PYQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PYQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PYQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PYQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(PYQ.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(PYQ.METRIC, '') = COALESCE(DIM.METRIC, '')
        AND PYQ.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = -4
    GROUP BY ALL
)

SELECT *
FROM
    FINAL
WHERE
    NOT
    (
        COALESCE(SALES_NEW_CUSTOMER_ACV, 0) = 0
        AND COALESCE(SALES_MS_NEW_ACV, 0) = 0
        AND COALESCE(SALES_MS_CREATED_ACV, 0) = 0
        AND COALESCE(SALES_PQTD_NEW_CUSTOMER_ACV, 0) = 0
        AND COALESCE(SALES_PQTD_MS_NEW_ACV, 0) = 0
        AND COALESCE(SALES_PQTD_MS_CREATED_ACV, 0) = 0
        AND COALESCE(SALES_PYQTD_NEW_CUSTOMER_ACV, 0) = 0
        AND COALESCE(SALES_PYQTD_MS_NEW_ACV, 0) = 0
        AND COALESCE(SALES_PYQTD_MS_CREATED_ACV, 0) = 0
    )