-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : fact_ffm_total_acv_weekly_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the post pipeline configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}


WITH BASE AS (
    SELECT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        WEEK_START_DATE,
        WEEK_NUMBER_FISCAL_QUARTER,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        GEO,
        COUNTRY,
        GDPR_FLAG,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        SALES_CHANNEL,
        ORIGIN_SEGMENT,
        ACV_SOURCE,
        SUM(TOTAL_ACV) AS STORE_TOTAL_ACV,
        SUM(NEW_BUSINESS_ACV) AS STORE_NEW_BUSINESS_ACV,
        SUM(NEW_CUSTOMER_ACV) AS STORE_NEW_CUSTOMER_ACV,
        SUM(RENEWAL_ACV) AS STORE_RENEWAL_ACV,
        SUM(EXPANSION_ACV) AS STORE_EXPANSION_ACV
    FROM
        {{ ref('FACT_FFM_TOTAL_ACV_DAILY') }}
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6 --Limits from last 6 completed quarters till last completed week of current quarter
    GROUP BY
        ALL
),
DIMENSIONS AS (
    SELECT
        DISTINCT GEO,
        COUNTRY,
        GDPR_FLAG,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        ORIGIN_SEGMENT,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        SALES_CHANNEL,
        ACV_SOURCE
    FROM
        BASE
),
DIM_CAL AS (
    SELECT
        DISTINCT 
        WEEK_START_DATE,
        WEEK_NUMBER_FISCAL_QUARTER,
        FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_QUARTER,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA,
        COMPLETED_WEEKS
    FROM
        {{ ref('FFM_FIN_CALENDAR') }}
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
),
-- To populate weekly level combinations of all possible dimensions
DIM_COMBINATIONS_WEEK AS (
    SELECT
        DISTINCT CAL.*,
        DIM.*
    FROM
        DIM_CAL CAL
        CROSS JOIN DIMENSIONS DIM
),
FINAL AS (
    SELECT
        'LOWER' AS FUNNEL,
        'STORE' AS METRIC_GROUP,
        DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.FISCAL_QUARTER_BEGIN_DATE,
        DIM.WEEK_START_DATE,
        DIM.WEEK_NUMBER_FISCAL_QUARTER,
        DIM.PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.PREVIOUS_FISCAL_YEAR_QUARTER,
        DIM.PREVIOUS_FISCAL_QUARTER_NAME,
        DIM.IS_CURRENT_QUARTER,
        DIM.IS_RESTRICTED_DATA,
        DIM.COMPLETED_WEEKS,
        DIM.GEO,
        DIM.COUNTRY,
        DIM.GDPR_FLAG,
        DIM.CAMPAIGN_INDUSTRY,
        DIM.BUSINESS_TIER,
        DIM.ORIGIN_SEGMENT,
        DIM.PRODUCT_FAMILY,
        DIM.PRODUCT_INDUSTRY,
        DIM.SALES_CHANNEL,
        DIM.ACV_SOURCE,
        --Base metrics
        BASE.STORE_TOTAL_ACV AS STORE_TOTAL_ACV,
        BASE.STORE_NEW_BUSINESS_ACV AS STORE_NEW_BUSINESS_ACV,
        BASE.STORE_NEW_CUSTOMER_ACV AS STORE_NEW_CUSTOMER_ACV,
        BASE.STORE_RENEWAL_ACV AS STORE_RENEWAL_ACV,
        BASE.STORE_EXPANSION_ACV AS STORE_EXPANSION_ACV,
        -- QoQ metrics
        PQ.STORE_TOTAL_ACV AS QOQ_STORE_TOTAL_ACV,
        PQ.STORE_NEW_BUSINESS_ACV AS QOQ_STORE_NEW_BUSINESS_ACV,
        PQ.STORE_NEW_CUSTOMER_ACV AS QOQ_STORE_NEW_CUSTOMER_ACV,
        PQ.STORE_RENEWAL_ACV AS QOQ_STORE_RENEWAL_ACV,
        PQ.STORE_EXPANSION_ACV AS QOQ_STORE_EXPANSION_ACV,
        -- YoY metrics
        PYQ.STORE_TOTAL_ACV AS YOY_STORE_TOTAL_ACV,
        PYQ.STORE_NEW_BUSINESS_ACV AS YOY_STORE_NEW_BUSINESS_ACV,
        PYQ.STORE_NEW_CUSTOMER_ACV AS YOY_STORE_NEW_CUSTOMER_ACV,
        PYQ.STORE_RENEWAL_ACV AS YOY_STORE_RENEWAL_ACV,
        PYQ.STORE_EXPANSION_ACV AS YOY_STORE_EXPANSION_ACV,
        CURRENT_TIMESTAMP AS RUN_TIMESTAMP
    FROM
        DIM_COMBINATIONS_WEEK DIM
        -- Join at all dimensions
        LEFT JOIN BASE 
        ON BASE.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND BASE.WEEK_NUMBER_FISCAL_QUARTER = DIM.WEEK_NUMBER_FISCAL_QUARTER
        AND COALESCE(BASE.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(BASE.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(BASE.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(BASE.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(BASE.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(BASE.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(BASE.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(BASE.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(BASE.ORIGIN_SEGMENT, '') = COALESCE(DIM.ORIGIN_SEGMENT, '')
        AND COALESCE(BASE.ACV_SOURCE, '') = COALESCE(DIM.ACV_SOURCE, '')
        -- Self-join to fetch previous quarter data for QoQ metrics
        LEFT JOIN BASE PQ 
        ON PQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.PREVIOUS_FISCAL_QUARTER_NAME
        AND PQ.WEEK_NUMBER_FISCAL_QUARTER = DIM.WEEK_NUMBER_FISCAL_QUARTER
        AND COALESCE(PQ.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(PQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(PQ.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(PQ.ORIGIN_SEGMENT, '') = COALESCE(DIM.ORIGIN_SEGMENT, '')
        AND COALESCE(PQ.ACV_SOURCE, '') = COALESCE(DIM.ACV_SOURCE, '')
        -- Self-join to fetch previous year's quarter data for YoY metrics
        LEFT JOIN BASE PYQ 
        ON PYQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND PYQ.WEEK_NUMBER_FISCAL_QUARTER = DIM.WEEK_NUMBER_FISCAL_QUARTER
        AND COALESCE(PYQ.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(PYQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PYQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PYQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PYQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PYQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PYQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(PYQ.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(PYQ.ORIGIN_SEGMENT, '') = COALESCE(DIM.ORIGIN_SEGMENT, '')
        AND COALESCE(PYQ.ACV_SOURCE, '') = COALESCE(DIM.ACV_SOURCE, '')
)

-- Remove records with 0 in all metrics. This would remove unwanted records and reduce table size
SELECT * FROM
    FINAL
WHERE
    NOT
    (
        COALESCE(STORE_TOTAL_ACV, 0) = 0 AND COALESCE(QOQ_STORE_TOTAL_ACV, 0) = 0 AND COALESCE(YOY_STORE_TOTAL_ACV, 0) = 0 AND
        COALESCE(STORE_NEW_BUSINESS_ACV, 0) = 0 AND COALESCE(QOQ_STORE_NEW_BUSINESS_ACV, 0) = 0 AND COALESCE(YOY_STORE_NEW_BUSINESS_ACV, 0) = 0 AND 
        COALESCE(STORE_NEW_CUSTOMER_ACV, 0) = 0 AND COALESCE(QOQ_STORE_NEW_CUSTOMER_ACV, 0) = 0 AND COALESCE(YOY_STORE_NEW_CUSTOMER_ACV, 0) = 0 AND 
        COALESCE(STORE_RENEWAL_ACV, 0) = 0 AND COALESCE(QOQ_STORE_RENEWAL_ACV, 0) = 0 AND COALESCE(YOY_STORE_RENEWAL_ACV, 0) = 0 AND 
        COALESCE(STORE_EXPANSION_ACV, 0) = 0 AND COALESCE(QOQ_STORE_EXPANSION_ACV, 0) = 0 AND COALESCE(YOY_STORE_EXPANSION_ACV, 0) = 0
    )