-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: facts
-- MODEL  : fact_ffm_new_customers_vw
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('ffm_reporting') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the configuration #}
{{
    config(
        materialized='view'
    )
}}

{# Set prehook config #}
{{
  config(
    pre_hook = [
        "ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;"
    ]
  )
}}

-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_QA",
        "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_ENGINEERING"
    ]
  )
}}


WITH NEW_CUSTOMERS AS (
    SELECT
        DISTINCT 
        CUSTOMER_PARENT_CSN AS CUSTOMER_PHASE_PARENT_CSN,
        CUSTOMER_PHASE_END_DATE,
        CUSTOMER_PHASE_START_DATE,
        DATE_TRUNC('MONTH', CUSTOMER_PHASE_START_DATE) AS MONTH_START_DATE,
        START_FISCAL_YEAR_QUARTER AS CUSTOMER_PHASE_START_FISCAL_YEAR_QUARTER,
        CC_FBD_BSM_SALES_CH AS SALES_CHANNEL,
        NULLIF(CC_FBD_SF_BIL_TERM_SETL, 'N/A') AS SUBSCRIPTION_TERM,
        NAG AS BUSINESS_TIER,
        GEO,
        COUNTRY,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        CAMPAIGN_INDUSTRY,
        ORIGIN_SEGMENT,
        ALLOCADIA_ID,
        EVT_CHANNEL AS CHANNEL
    FROM
    {{ ref('FFM_CUSTOMERS_STAGE') }}
)

SELECT
    DISTINCT
    'LOWER' AS FUNNEL,
    'CUSTOMER' AS METRIC_GROUP,
    A.CUSTOMER_PHASE_START_FISCAL_YEAR_QUARTER AS FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
    C.FISCAL_QUARTER_BEGIN_DATE,
    C.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
    C.PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
    C.PREVIOUS_FISCAL_YEAR_QUARTER,
    C.PREVIOUS_FISCAL_QUARTER_NAME,
    C.MONTH_START_DATE,
    C.WEEK_NUMBER_FISCAL_QUARTER AS CUSTOMER_PHASE_START_WEEK_NUMBER,
    CONCAT(C.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, '_', LPAD(C.WEEK_NUMBER_FISCAL_QUARTER, 2, '0')) AS FYQUARTER_AND_FYWEEK,
    CONCAT(C.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, '_', LPAD(WEEK_NUMBER_FISCAL_QUARTER, 2, '0')) AS PRIOR_YEAR_FYQUARTER_AND_FYWEEK,
    C.IS_CURRENT_QUARTER,
    0 AS IS_RESTRICTED_DATA,
    C.COMPLETED_WEEKS,
    A.BUSINESS_TIER,
    A.GEO,
    A.COUNTRY,
    A.PRODUCT_FAMILY,
    A.PRODUCT_INDUSTRY,
    A.CAMPAIGN_INDUSTRY,
    A.SALES_CHANNEL,
    A.SUBSCRIPTION_TERM,
    A.ORIGIN_SEGMENT,
    A.CUSTOMER_PHASE_PARENT_CSN,
    A.CUSTOMER_PHASE_END_DATE,
    A.CUSTOMER_PHASE_START_DATE,
    A.ALLOCADIA_ID,
    A.CHANNEL,
    ABS(TO_NUMBER(MD5(COALESCE(A.GEO, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "Geography_Id",
    ABS(TO_NUMBER(MD5(UPPER(COALESCE(A.COUNTRY, 'Unknown'))), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "Country_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.BUSINESS_TIER, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "BusinessTier_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.PRODUCT_INDUSTRY, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "ProductIndustry_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.PRODUCT_FAMILY, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "ProductFamily_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.CAMPAIGN_INDUSTRY, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "CampaignIndustry_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.SALES_CHANNEL, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "SalesChannel_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.ORIGIN_SEGMENT, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "Origin_Segment_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.SUBSCRIPTION_TERM, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "SubscriptionTerm_Id",
    ABS(TO_NUMBER(MD5(COALESCE(A.CHANNEL, 'Unknown')), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')::BIGINT) % 10000000 AS "Channel_Id"
FROM
    NEW_CUSTOMERS A
INNER JOIN {{ ref('FFM_FIN_CALENDAR') }} C
ON C.DATE_KEY = A.CUSTOMER_PHASE_START_DATE
WHERE C.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6