-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : fact_ffm_total_acv_monthly_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the post pipeline configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}


WITH LAST_COMPLETED_WEEK AS (
    -- Get last completed week of latest quarter
    SELECT
        MAX(WEEK_NUMBER_FISCAL_QUARTER) AS LAST_WEEK
    FROM
        {{ ref('FACT_FFM_TOTAL_ACV_DAILY') }}
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = 0
),
BASE AS (
    SELECT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        MONTH_START_DATE,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        GEO,
        COUNTRY,
        GDPR_FLAG,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        SALES_CHANNEL,
        ORIGIN_SEGMENT,
        SUM(TOTAL_ACV) AS STORE_TOTAL_ACV,
        SUM(NEW_BUSINESS_ACV) AS STORE_NEW_BUSINESS_ACV,
        SUM(NEW_CUSTOMER_ACV) AS STORE_NEW_CUSTOMER_ACV,
        SUM(RENEWAL_ACV) AS STORE_RENEWAL_ACV,
        SUM(EXPANSION_ACV) AS STORE_EXPANSION_ACV
    FROM
        {{ ref('FACT_FFM_TOTAL_ACV_DAILY') }}
    WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6 --Limits from last 6 completed quarters till last completed week of current quarter
    GROUP BY
        ALL
),
PQTD_PYQTD AS (
    SELECT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        MONTH_START_DATE,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        GEO,
        COUNTRY,
        GDPR_FLAG,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        SALES_CHANNEL,
        ORIGIN_SEGMENT,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        SUM(TOTAL_ACV) AS STORE_TOTAL_ACV,
        SUM(NEW_BUSINESS_ACV) AS STORE_NEW_BUSINESS_ACV,
        SUM(NEW_CUSTOMER_ACV) AS STORE_NEW_CUSTOMER_ACV,
        SUM(RENEWAL_ACV) AS STORE_RENEWAL_ACV,
        SUM(EXPANSION_ACV) AS STORE_EXPANSION_ACV
    FROM
       {{ ref('FACT_FFM_TOTAL_ACV_DAILY') }}
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER IN (-1, -4)
        AND WEEK_NUMBER_FISCAL_QUARTER <= (SELECT LAST_WEEK FROM LAST_COMPLETED_WEEK) 
        -- Fetch Prev. QTR & Prev. Yr. QTR till last completed week of current quarter
    GROUP BY
        ALL
),
DIMENSIONS AS (
    SELECT
        DISTINCT GEO,
        COUNTRY,
        GDPR_FLAG,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        ORIGIN_SEGMENT,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        SALES_CHANNEL
    FROM
        BASE
),
DIM_CAL AS (
    SELECT
        DISTINCT MONTH_START_DATE,
        PREVIOUS_MONTH_START_DATE,
        FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_QUARTER,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA,
        COMPLETED_WEEKS
    FROM
        {{ ref('FFM_FIN_CALENDAR') }}
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
),
DIM_COMBINATIONS_QTRS AS (
    SELECT
        DISTINCT CAL.*,
        DIM.*
    FROM
        DIM_CAL CAL
        CROSS JOIN DIMENSIONS DIM
),
FINAL AS (
    SELECT
        'LOWER' AS FUNNEL,
        'STORE' AS METRIC_GROUP,
        DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.FISCAL_QUARTER_BEGIN_DATE,
        DIM.MONTH_START_DATE,
        DIM.PREVIOUS_MONTH_START_DATE,
        DIM.PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.PREVIOUS_FISCAL_YEAR_QUARTER,
        DIM.PREVIOUS_FISCAL_QUARTER_NAME,
        DIM.IS_CURRENT_QUARTER,
        DIM.IS_RESTRICTED_DATA,
        DIM.COMPLETED_WEEKS,
        DIM.GEO,
        DIM.COUNTRY,
        DIM.GDPR_FLAG,
        DIM.CAMPAIGN_INDUSTRY,
        DIM.BUSINESS_TIER,
        DIM.ORIGIN_SEGMENT,
        DIM.PRODUCT_FAMILY,
        DIM.PRODUCT_INDUSTRY,
        DIM.SALES_CHANNEL,
        --Base metrics
        BASE.STORE_TOTAL_ACV AS STORE_TOTAL_ACV,
        BASE.STORE_NEW_BUSINESS_ACV AS STORE_NEW_BUSINESS_ACV,
        BASE.STORE_NEW_CUSTOMER_ACV AS STORE_NEW_CUSTOMER_ACV,
        BASE.STORE_RENEWAL_ACV AS STORE_RENEWAL_ACV,
        BASE.STORE_EXPANSION_ACV AS STORE_EXPANSION_ACV,
        --PQTD metrics
        PQ.STORE_TOTAL_ACV AS PQTD_STORE_TOTAL_ACV,
        PQ.STORE_NEW_BUSINESS_ACV AS PQTD_STORE_NEW_BUSINESS_ACV,
        PQ.STORE_NEW_CUSTOMER_ACV AS PQTD_STORE_NEW_CUSTOMER_ACV,
        PQ.STORE_RENEWAL_ACV AS PQTD_STORE_RENEWAL_ACV,
        PQ.STORE_EXPANSION_ACV AS PQTD_STORE_EXPANSION_ACV,
        --PYQTD metrics
        PYQ.STORE_TOTAL_ACV AS PYQTD_STORE_TOTAL_ACV,
        PYQ.STORE_NEW_BUSINESS_ACV AS PYQTD_STORE_NEW_BUSINESS_ACV,
        PYQ.STORE_NEW_CUSTOMER_ACV AS PYQTD_STORE_NEW_CUSTOMER_ACV,
        PYQ.STORE_RENEWAL_ACV AS PYQTD_STORE_RENEWAL_ACV,
        PYQ.STORE_EXPANSION_ACV AS PYQTD_STORE_EXPANSION_ACV,
        CURRENT_TIMESTAMP AS RUN_TIMESTAMP
    FROM
        DIM_COMBINATIONS_QTRS DIM
        -- Join at all dimensions
        LEFT JOIN BASE 
        ON BASE.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND BASE.MONTH_START_DATE = DIM.MONTH_START_DATE
        AND COALESCE(BASE.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(BASE.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(BASE.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(BASE.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(BASE.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(BASE.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(BASE.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(BASE.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(BASE.ORIGIN_SEGMENT, '') = COALESCE(DIM.ORIGIN_SEGMENT, '')
        -- Join Previous QTD data
        LEFT JOIN PQTD_PYQTD PQ 
        ON PQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.PREVIOUS_FISCAL_QUARTER_NAME
        AND PQ.MONTH_START_DATE = DATEADD(MONTH, -3, DIM.MONTH_START_DATE)
        AND COALESCE(PQ.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(PQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(PQ.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(PQ.ORIGIN_SEGMENT, '') = COALESCE(DIM.ORIGIN_SEGMENT, '')
        AND PQ.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = -1
        -- Join Previous Year QTD data
        LEFT JOIN PQTD_PYQTD PYQ 
        ON PYQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND PYQ.MONTH_START_DATE = DATEADD(MONTH, -12, DIM.MONTH_START_DATE)
        AND COALESCE(PYQ.CAMPAIGN_INDUSTRY, '') = COALESCE(DIM.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(PYQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PYQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PYQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PYQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PYQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PYQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND COALESCE(PYQ.SALES_CHANNEL, '') = COALESCE(DIM.SALES_CHANNEL, '')
        AND COALESCE(PYQ.ORIGIN_SEGMENT, '') = COALESCE(DIM.ORIGIN_SEGMENT, '')
        AND PYQ.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = -4
)

SELECT * FROM
    FINAL
WHERE
    NOT
    (
        COALESCE(STORE_TOTAL_ACV, 0) = 0 AND COALESCE(PQTD_STORE_TOTAL_ACV, 0) = 0 AND COALESCE(PYQTD_STORE_TOTAL_ACV, 0) = 0 AND
        COALESCE(STORE_NEW_BUSINESS_ACV, 0) = 0 AND COALESCE(PQTD_STORE_NEW_BUSINESS_ACV, 0) = 0 AND COALESCE(PYQTD_STORE_NEW_BUSINESS_ACV, 0) = 0 AND 
        COALESCE(STORE_NEW_CUSTOMER_ACV, 0) = 0 AND COALESCE(PQTD_STORE_NEW_CUSTOMER_ACV, 0) = 0 AND COALESCE(PYQTD_STORE_NEW_CUSTOMER_ACV, 0) = 0 AND 
        COALESCE(STORE_RENEWAL_ACV, 0) = 0 AND COALESCE(PQTD_STORE_RENEWAL_ACV, 0) = 0 AND COALESCE(PYQTD_STORE_RENEWAL_ACV, 0) = 0 AND 
        COALESCE(STORE_EXPANSION_ACV, 0) = 0 AND COALESCE(PQTD_STORE_EXPANSION_ACV, 0) = 0 AND COALESCE(PYQTD_STORE_EXPANSION_ACV, 0) = 0
    )