-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : ffm_trials_to_orders_weekly_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the configuration #}
{{
     config(
         materialized='table'
     )
}}

 {{
    config(
     post_hook = [
         "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_ENGINEERING",
         "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_QA"
     ]
   )
 }}

WITH FIN_CAL AS (
    SELECT DISTINCT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        FISCAL_QUARTER_BEGIN_DATE,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        WEEK_NUMBER_FISCAL_QUARTER,
        IS_RESTRICTED_DATA,
        WEEK_START_DATE,
        DATE_KEY
    FROM {{ ref('FFM_FIN_CALENDAR') }}
    WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
),
TRIALS_ORDER_WITH_ADDED_DIM AS (
    SELECT
        TL.ECC_SALES_ORDER_NBR,
        TL.GEO,
        TL.COUNTRY,
        TL.GDPR_FLAG,
        TL.BUSINESS_TIER,
        TL.PRODUCT_FAMILY,
        TL.PRODUCT_INDUSTRY,
        FIN_CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        FIN_CAL.WEEK_NUMBER_FISCAL_QUARTER,
        FIN_CAL.WEEK_START_DATE,
        FIN_CAL.IS_CURRENT_QUARTER,
        FIN_CAL.IS_RESTRICTED_DATA,
        FIN_CAL.PREVIOUS_FISCAL_QUARTER_NAME,
        FIN_CAL.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
    FROM {{ ref('FFM_TRIAL_ORDER_CONVERSION_STAGE') }} TL
    INNER JOIN FIN_CAL
        ON FIN_CAL.DATE_KEY = TL.ORDER_DT
    WHERE TRIAL_CONVERTED_FLAG = TRUE
),
BASE_AGGREGATED AS (
    SELECT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, WEEK_NUMBER_FISCAL_QUARTER, WEEK_START_DATE, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, COUNTRY, GDPR_FLAG, BUSINESS_TIER, PRODUCT_FAMILY, PRODUCT_INDUSTRY, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        COUNT(DISTINCT ECC_SALES_ORDER_NBR) AS ORDER_NUMBERS,
        CONCAT(
            'WEEK-GEO',
            IFF(GROUPING(COUNTRY) = 0, '-CNTRY', ''),
            IFF(GROUPING(BUSINESS_TIER) = 0, '-B_TIER', ''),
            IFF(GROUPING(PRODUCT_FAMILY) = 0, '-PROD_FAM', ''),
            IFF(GROUPING(PRODUCT_INDUSTRY) = 0, '-PROD_IND', '')
        ) AS AGGREGATED_BY
    FROM TRIALS_ORDER_WITH_ADDED_DIM
    GROUP BY
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, WEEK_NUMBER_FISCAL_QUARTER, WEEK_START_DATE, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, GDPR_FLAG, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        CUBE(COUNTRY, BUSINESS_TIER, PRODUCT_FAMILY, PRODUCT_INDUSTRY)
),
DIMENSIONS AS (
    SELECT DISTINCT
        GEO,
        COUNTRY,
        GDPR_FLAG,
        BUSINESS_TIER,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        AGGREGATED_BY
    FROM BASE_AGGREGATED
),
DIM_CAL AS (
    SELECT DISTINCT
        WEEK_START_DATE,
        WEEK_NUMBER_FISCAL_QUARTER,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA
    FROM FIN_CAL
),
DIM_COMBINATIONS_WEEK AS (
    SELECT DISTINCT
        CAL.*,
        DIM.*
    FROM DIM_CAL CAL
    CROSS JOIN DIMENSIONS DIM
),
FINAL AS (
    SELECT
        'LOWER' AS FUNNEL,
        'TRIAL_TO_ORDER' AS METRIC_GROUP,
        DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.WEEK_NUMBER_FISCAL_QUARTER,
        DIM.WEEK_START_DATE,
        DIM.PREVIOUS_FISCAL_QUARTER_NAME,
        DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.GEO,
        DIM.COUNTRY,
        DIM.BUSINESS_TIER,
        DIM.PRODUCT_FAMILY,
        DIM.PRODUCT_INDUSTRY,
        DIM.IS_RESTRICTED_DATA,
        DIM.IS_CURRENT_QUARTER,
        BASE.ORDER_NUMBERS,
        PQ.ORDER_NUMBERS AS QOQ_ORDER_NUMBERS,
        PY.ORDER_NUMBERS AS YOY_ORDER_NUMBERS,
        DIM.AGGREGATED_BY AS ORDERS_AGGREGATED_BY,
        CURRENT_TIMESTAMP AS RUN_TIMESTAMP
    FROM DIM_COMBINATIONS_WEEK DIM
    LEFT JOIN BASE_AGGREGATED BASE
        ON DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = BASE.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND DIM.WEEK_NUMBER_FISCAL_QUARTER = BASE.WEEK_NUMBER_FISCAL_QUARTER
        AND DIM.AGGREGATED_BY = BASE.AGGREGATED_BY
        AND COALESCE(DIM.GEO, '') = COALESCE(BASE.GEO, '')
        AND COALESCE(DIM.COUNTRY, '') = COALESCE(BASE.COUNTRY, '')
        AND COALESCE(DIM.GDPR_FLAG, '') = COALESCE(BASE.GDPR_FLAG, '')
        AND COALESCE(DIM.BUSINESS_TIER, '') = COALESCE(BASE.BUSINESS_TIER, '')
        AND COALESCE(DIM.PRODUCT_FAMILY, '') = COALESCE(BASE.PRODUCT_FAMILY, '')
        AND COALESCE(DIM.PRODUCT_INDUSTRY, '') = COALESCE(BASE.PRODUCT_INDUSTRY, '')
    LEFT JOIN BASE_AGGREGATED PQ
        ON DIM.PREVIOUS_FISCAL_QUARTER_NAME = PQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND DIM.WEEK_NUMBER_FISCAL_QUARTER = PQ.WEEK_NUMBER_FISCAL_QUARTER
        AND DIM.AGGREGATED_BY = PQ.AGGREGATED_BY
        AND COALESCE(DIM.GEO, '') = COALESCE(PQ.GEO, '')
        AND COALESCE(DIM.COUNTRY, '') = COALESCE(PQ.COUNTRY, '')
        AND COALESCE(DIM.GDPR_FLAG, '') = COALESCE(PQ.GDPR_FLAG, '')
        AND COALESCE(DIM.BUSINESS_TIER, '') = COALESCE(PQ.BUSINESS_TIER, '')
        AND COALESCE(DIM.PRODUCT_FAMILY, '') = COALESCE(PQ.PRODUCT_FAMILY, '')
        AND COALESCE(DIM.PRODUCT_INDUSTRY, '') = COALESCE(PQ.PRODUCT_INDUSTRY, '')
    LEFT JOIN BASE_AGGREGATED PY
        ON DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = PY.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND DIM.WEEK_NUMBER_FISCAL_QUARTER = PY.WEEK_NUMBER_FISCAL_QUARTER
        AND DIM.AGGREGATED_BY = PY.AGGREGATED_BY
        AND COALESCE(DIM.GEO, '') = COALESCE(PY.GEO, '')
        AND COALESCE(DIM.COUNTRY, '') = COALESCE(PY.COUNTRY, '')
        AND COALESCE(DIM.GDPR_FLAG, '') = COALESCE(PY.GDPR_FLAG, '')
        AND COALESCE(DIM.BUSINESS_TIER, '') = COALESCE(PY.BUSINESS_TIER, '')
        AND COALESCE(DIM.PRODUCT_FAMILY, '') = COALESCE(PY.PRODUCT_FAMILY, '')
        AND COALESCE(DIM.PRODUCT_INDUSTRY, '') = COALESCE(PY.PRODUCT_INDUSTRY, '')
)

-- Remove records with null in all metrics. This would remove unwanted records and reduce table size
SELECT *
FROM FINAL
WHERE NOT (
    COALESCE(ORDER_NUMBERS, 0) = 0
    AND COALESCE(QOQ_ORDER_NUMBERS, 0) = 0
    AND COALESCE(YOY_ORDER_NUMBERS, 0) = 0
)