-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: upper_funnel
-- MODEL  : ffm_store_ecomm_traffic_weekly_preagg
-- =============================================================================
-- depends_on: {{ ref('FFM_FIN_CALENDAR') }}
{# This aggregated model is used for FFM Campaign & Paid Media Dashboard
  - Dynamically enumerates all 2^4 (16) subsets of the dimensions:
      PRODUCT_FAMILY (PROD_FAM)
      PRODUCT_INDUSTRY (PROD_IND)
      ALLOCADIA_ID (ALL_ID)
      LAST_TOUCH_CHANNEL (LTC)
  - AGGREGATED_BY lists only the dimensions RETAINED.
        ALL (static at Country level) => WEEK-GDPR-GEO-CNTRY
        Full 4 dims => WEEK-GDPR-GEO-CNTRY-PROD_FAM-PROD_IND-ALL_ID-LTC
#}

{% set db_properties = get_dbproperties('fullfunnel') %}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}
{{ config(materialized='incremental', incremental_strategy='delete+insert', unique_key=['FY_QUARTER','FY_WEEK','AGGREGATED_BY']) }}

{# Dimensions to include in rollup combinations #}
{% set dim = [
  {'col': 'PRODUCT_FAMILY', 'code': 'PROD_FAM'},
  {'col': 'PRODUCT_INDUSTRY', 'code': 'PROD_IND'},
  {'col': 'ALLOCADIA_ID', 'code': 'ALL_ID'},
  {'col': 'LAST_TOUCH_CHANNEL', 'code': 'LTC'}
] %}

{{
  config(
    pre_hook = [
        """{% if is_incremental() %}
            DELETE FROM {{ this }} -- Deletes dates older than previous 12 quarters
            WHERE FY_QUARTER IN (SELECT FISCAL_YEAR_AND_FISCAL_QUARTER_NAME 
                                    FROM {{ ref('FFM_FIN_CALENDAR') }} 
                                WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER < -6)
        {% endif %}"""
    ]
  )
}}

WITH CALENDAR AS (
  SELECT DISTINCT
    FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FY_QUARTER,
    WEEK_NUMBER_FISCAL_QUARTER AS FY_WEEK,
    WEEK_START_DATE,
    PREVIOUS_FISCAL_QUARTER_NAME AS PREVIOUS_FYQUARTER,
    PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS PREVIOUS_YEAR_FYQUARTER
  FROM {{ ref('FFM_FIN_CALENDAR') }}
  WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
    AND DATE_KEY < CURRENT_DATE
),
VISITS AS (
  SELECT *
  FROM {{ ref('FFM_STORE_ECOMM_TRAFFIC_VISIT_FACT') }}
  {% if is_incremental() %}
    WHERE FY_QUARTER || LPAD(FY_WEEK, 2, '0') > (
        SELECT COALESCE(MAX(FY_QUARTER || LPAD(FY_WEEK,2,'0')), '') FROM {{ this }}
    )
  {% else %}
    -- Full refresh: process last 6 quarters and current quarter till last completed week
    WHERE (FY_QUARTER, FY_WEEK) IN (
        SELECT DISTINCT 
            FY_QUARTER, FY_WEEK
        FROM CALENDAR
    )
  {% endif %}
),
AGGREGATED AS (
  {% set selects = [] %}
  {% for mask in range(0, 2 ** dim|length) %}
    {% set kept_cols = [] %}
    {% set kept_codes = [] %}
    {% for d in dim %}
      {% set bit = loop.index0 %}
      {% if (mask // (2 ** bit)) % 2 == 1 %}
        {% do kept_cols.append(d.col) %}
        {% do kept_codes.append(d.code) %}
      {% endif %}
    {% endfor %}
    {% set agg_code = 'WEEK-GDPR-GEO-CNTRY' + ('-' + ('-'.join(kept_codes)) if kept_codes|length > 0 else '') %}
    {% set select_sql %}
      SELECT
        V.FY_QUARTER,
        V.FY_WEEK,
        C.WEEK_START_DATE,
        C.PREVIOUS_FYQUARTER,
        C.PREVIOUS_YEAR_FYQUARTER,
        V.GDPR_FLAG,
        V.GEO,
        V.COUNTRY,
        {% for d in dim %}
          {% if d.col in kept_cols %}V.{{ d.col }}{% else %}NULL{% endif %} AS {{ d.col }}{% if not loop.last %},{% endif %}
        {% endfor %},
        COUNT(DISTINCT V.VISIT_ID) AS VISITS,
        COUNT(DISTINCT IFF(V.IS_NEW_TRAFFIC=1, V.VISITOR_ID, NULL)) AS NEW_VISITORS,
        COUNT(DISTINCT IFF(V.IS_RETURNING_TRAFFIC=1, V.VISITOR_ID, NULL)) AS RETURNING_VISITORS,
        COUNT(DISTINCT IFF(V.HAS_CART_ADD=1, V.VISIT_ID, NULL)) AS CART_ADD_VISITS,
        COUNT(DISTINCT IFF(V.IS_VIDEO_START=1, V.VISITOR_ID, NULL)) AS VIDEO_VIEWS_VISITORS,
        COUNT(DISTINCT IFF(V.IS_VIDEO_50_PERCENT=1, V.VISITOR_ID, NULL)) AS VIDEO_VIEWS_50_PERCENT_VISITORS,
        COUNT(DISTINCT IFF(V.IS_PROSPECT=1, V.VISIT_ID, NULL)) AS PROSPECTS,
        COUNT(DISTINCT IFF(V.IS_PRODUCT_PAGE_VISIT=1, V.VISIT_ID, NULL)) AS PRODUCT_PAGE_VISITS,
        COUNT(DISTINCT IFF(V.IS_BOUNCE_VISIT_SUM = 1, V.VISIT_ID, NULL)) AS BOUNCE_VISITS,
        '{{ agg_code }}' AS AGGREGATED_BY
      FROM VISITS V
      JOIN CALENDAR C
        ON C.FY_QUARTER = V.FY_QUARTER AND C.FY_WEEK = V.FY_WEEK
      GROUP BY
        V.FY_QUARTER, V.FY_WEEK, C.WEEK_START_DATE, C.PREVIOUS_FYQUARTER, C.PREVIOUS_YEAR_FYQUARTER, V.GDPR_FLAG, V.GEO, V.COUNTRY
        {% for col in kept_cols %}, V.{{ col }}{% endfor %}
    {% endset %}
    {% do selects.append(select_sql) %}
  {% endfor %}

  {{ selects | join('\nUNION ALL\n') }}
),
TRAFFIC_ORDERS AS (
  SELECT 
  AGG.*,
  ORDERS.FINMART_NEW_STORE_ORDERS
  FROM AGGREGATED AGG
  LEFT JOIN 
    {{ ref('FFM_FINMART_NEW_STORE_ORDERS') }} ORDERS
  ON 
  AGG.FY_QUARTER = ORDERS.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
  AND AGG.FY_WEEK = ORDERS.WEEK_NUMBER_FISCAL_QUARTER
  AND AGG.AGGREGATED_BY = ORDERS.AGGREGATED_BY
  AND COALESCE(AGG.GEO,'') = COALESCE(ORDERS.GEO,'') 
  AND COALESCE(AGG.COUNTRY,'') = COALESCE(ORDERS.COUNTRY,'')
  AND COALESCE(AGG.PRODUCT_FAMILY,'') = COALESCE(ORDERS.PRODUCT_FAMILY,'')
  AND COALESCE(AGG.PRODUCT_INDUSTRY,'') = COALESCE(ORDERS.PRODUCT_INDUSTRY,'')
  AND COALESCE(AGG.ALLOCADIA_ID,'') = COALESCE(ORDERS.ALLOCADIA_ID,'')
  AND COALESCE(AGG.LAST_TOUCH_CHANNEL,'') = COALESCE(ORDERS.LAST_TOUCH_CHANNEL,'')
) 


SELECT
  A.FY_QUARTER,
  A.FY_WEEK,
  A.WEEK_START_DATE,
  A.PREVIOUS_FYQUARTER,
  A.PREVIOUS_YEAR_FYQUARTER,
  A.GDPR_FLAG,
  A.GEO,
  A.COUNTRY,
  A.PRODUCT_FAMILY,
  A.PRODUCT_INDUSTRY,
  A.LAST_TOUCH_CHANNEL,
  A.ALLOCADIA_ID,
  A.VISITS,
  COALESCE(PW.VISITS, A.VISITS) AS QOQ_VISITS,
  COALESCE(PYW.VISITS, A.VISITS) AS YOY_VISITS,
  A.NEW_VISITORS,
  COALESCE(PW.NEW_VISITORS, A.NEW_VISITORS) AS QOQ_NEW_VISITORS,
  COALESCE(PYW.NEW_VISITORS, A.NEW_VISITORS) AS YOY_NEW_VISITORS,
  A.RETURNING_VISITORS,
  COALESCE(PW.RETURNING_VISITORS, A.RETURNING_VISITORS) AS QOQ_RETURNING_VISITORS,
  COALESCE(PYW.RETURNING_VISITORS, A.RETURNING_VISITORS) AS YOY_RETURNING_VISITORS,
  A.CART_ADD_VISITS,
  COALESCE(PW.CART_ADD_VISITS, A.CART_ADD_VISITS) AS QOQ_CART_ADD_VISITS,
  COALESCE(PYW.CART_ADD_VISITS, A.CART_ADD_VISITS) AS YOY_CART_ADD_VISITS,
  A.VIDEO_VIEWS_VISITORS,
  COALESCE(PW.VIDEO_VIEWS_VISITORS, A.VIDEO_VIEWS_VISITORS) AS QOQ_VIDEO_VIEWS_VISITORS,
  COALESCE(PYW.VIDEO_VIEWS_VISITORS, A.VIDEO_VIEWS_VISITORS) AS YOY_VIDEO_VIEWS_VISITORS,
  A.VIDEO_VIEWS_50_PERCENT_VISITORS,
  COALESCE(PW.VIDEO_VIEWS_50_PERCENT_VISITORS, A.VIDEO_VIEWS_50_PERCENT_VISITORS) AS QOQ_VIDEO_VIEWS_50_PERCENT_VISITORS,
  COALESCE(PYW.VIDEO_VIEWS_50_PERCENT_VISITORS, A.VIDEO_VIEWS_50_PERCENT_VISITORS) AS YOY_VIDEO_VIEWS_50_PERCENT_VISITORS,
  A.PROSPECTS,
  COALESCE(PW.PROSPECTS, A.PROSPECTS) AS QOQ_PROSPECTS,
  COALESCE(PYW.PROSPECTS, A.PROSPECTS) AS YOY_PROSPECTS,
  A.PRODUCT_PAGE_VISITS,
  COALESCE(PW.PRODUCT_PAGE_VISITS, A.PRODUCT_PAGE_VISITS) AS QOQ_PRODUCT_PAGE_VISITS,
  COALESCE(PYW.PRODUCT_PAGE_VISITS, A.PRODUCT_PAGE_VISITS) AS YOY_PRODUCT_PAGE_VISITS,
  A.BOUNCE_VISITS,
  COALESCE(PW.BOUNCE_VISITS, A.BOUNCE_VISITS) AS QOQ_BOUNCE_VISITS,
  COALESCE(PYW.BOUNCE_VISITS, A.BOUNCE_VISITS) AS YOY_BOUNCE_VISITS,
  A.FINMART_NEW_STORE_ORDERS,
  COALESCE(PW.FINMART_NEW_STORE_ORDERS, 0) AS QOQ_FINMART_NEW_STORE_ORDERS,
  COALESCE(PYW.FINMART_NEW_STORE_ORDERS, 0) AS YOY_FINMART_NEW_STORE_ORDERS,
  A.AGGREGATED_BY,
  CURRENT_TIMESTAMP AS RUN_TIMESTAMP
FROM TRAFFIC_ORDERS A

LEFT JOIN (
  {% if is_incremental() %}
    {{ this }}
  {% else %}
    TRAFFIC_ORDERS
  {% endif %}
) PW
  ON A.PREVIOUS_FYQUARTER = PW.FY_QUARTER
 AND A.FY_WEEK = PW.FY_WEEK
 AND A.AGGREGATED_BY = PW.AGGREGATED_BY
 AND COALESCE(A.GDPR_FLAG,'') = COALESCE(PW.GDPR_FLAG,'')
 AND COALESCE(A.GEO,'') = COALESCE(PW.GEO,'')
 AND COALESCE(A.COUNTRY,'') = COALESCE(PW.COUNTRY,'')
 AND COALESCE(A.PRODUCT_FAMILY,'') = COALESCE(PW.PRODUCT_FAMILY,'')
 AND COALESCE(A.PRODUCT_INDUSTRY,'') = COALESCE(PW.PRODUCT_INDUSTRY,'')
 AND COALESCE(A.LAST_TOUCH_CHANNEL,'') = COALESCE(PW.LAST_TOUCH_CHANNEL,'')
 AND COALESCE(A.ALLOCADIA_ID,'') = COALESCE(PW.ALLOCADIA_ID,'')
LEFT JOIN (
  {% if is_incremental() %}
    {{ this }}
  {% else %}
    TRAFFIC_ORDERS
  {% endif %}
) PYW
  ON A.PREVIOUS_YEAR_FYQUARTER = PYW.FY_QUARTER
 AND A.FY_WEEK = PYW.FY_WEEK
 AND A.AGGREGATED_BY = PYW.AGGREGATED_BY
 AND COALESCE(A.GDPR_FLAG,'') = COALESCE(PYW.GDPR_FLAG,'')
 AND COALESCE(A.GEO,'') = COALESCE(PYW.GEO,'')
 AND COALESCE(A.COUNTRY,'') = COALESCE(PYW.COUNTRY,'')
 AND COALESCE(A.PRODUCT_FAMILY,'') = COALESCE(PYW.PRODUCT_FAMILY,'')
 AND COALESCE(A.PRODUCT_INDUSTRY,'') = COALESCE(PYW.PRODUCT_INDUSTRY,'')
 AND COALESCE(A.LAST_TOUCH_CHANNEL,'') = COALESCE(PYW.LAST_TOUCH_CHANNEL,'')
 AND COALESCE(A.ALLOCADIA_ID,'') = COALESCE(PYW.ALLOCADIA_ID,'')
