-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : ffm_store_new_orders_weekly_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the configuration #}
{{
    config(
        materialized='table'
    )
}}

{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST"
    ]
  )
}}

WITH FIN_RAW AS (
    SELECT DISTINCT
        FIN.FIN_SRC_ID,
        FIN.FIN_ECC_SALES_ORDER_NBR,
        CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        CAL.WEEK_NUMBER_FISCAL_QUARTER,
        CAL.WEEK_START_DATE,
        CAL.PREVIOUS_FISCAL_QUARTER_NAME,
        CAL.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        CAL.IS_RESTRICTED_DATA,
        CAL.IS_CURRENT_QUARTER,
        FIN.FIN_CAMPAIGN_INDUSTRY AS CAMPAIGN_INDUSTRY,
        FIN.FIN_CORPORATE_NAMED_ACCOUNT_GROUP_NM AS BUSINESS_TIER,
        NULLIF(UPPER(FIN.FIN_CC_FBD_SF_WWS_GEO), 'CORP') AS GEO,
        FIN.FIN_CORPORATE_COUNTRY_NM AS COUNTRY,
        FIN.FIN_PRODUCT_FAMILY AS PRODUCT_FAMILY,
        FIN.FIN_PRODUCT_INDUSTRY AS PRODUCT_INDUSTRY,
        FIN.FIN_ORIGIN_SEGMENT AS ORIGIN_SEGMENT
    FROM
        {{ ref('FFM_LOWER_FUNNEL') }} FIN
    JOIN {{ ref('FFM_FIN_CALENDAR') }} CAL 
        ON FIN.FIN_TRANSACTION_DT = CAL.DATE_KEY
    WHERE CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6 --Limits from last 6 completed quarters till last completed week of current quarter
        AND UPPER(FIN.FIN_CC_FBD_BSM_SALES_CH) = 'ESTORE'
        AND (
            (FIN.ACV_SOURCE = 'Finmart Integrated' AND UPPER(FIN.FIN_CC_FBD_SF_FOX_RENEWAL_IND) = 'NEW') -- Fetch only Store New Orders from Finmart Integrated
            OR 
            (FIN.ACV_SOURCE ilike 'acs core%' AND (COALESCE(FIN.ACS_NEW_ACV,0) + COALESCE(FIN.ACS_EXPANSION_ACV, 0)) <> 0) -- Fetch only Store New Orders from ACS Core
        )
),
BASE_AGGREGATED AS (
    SELECT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, WEEK_NUMBER_FISCAL_QUARTER, WEEK_START_DATE, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, COUNTRY, CAMPAIGN_INDUSTRY, BUSINESS_TIER, ORIGIN_SEGMENT, PRODUCT_FAMILY, PRODUCT_INDUSTRY, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        COUNT(DISTINCT FIN_ECC_SALES_ORDER_NBR) AS STORE_NEW_ORDER_COUNT,
        CONCAT(
            'WEEK-GEO-CNTRY-C_IND-B_TIER',
            IFF(GROUPING(ORIGIN_SEGMENT) = 0, '-ORIGIN_SEG', ''),
            IFF(GROUPING(PRODUCT_FAMILY) = 0, '-PROD_FAM', ''),
            IFF(GROUPING(PRODUCT_INDUSTRY) = 0, '-PROD_IND', '')
        ) AS AGGREGATED_BY
    FROM
        FIN_RAW
    GROUP BY
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, WEEK_NUMBER_FISCAL_QUARTER, WEEK_START_DATE, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, COUNTRY, CAMPAIGN_INDUSTRY, BUSINESS_TIER, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        CUBE (ORIGIN_SEGMENT, PRODUCT_FAMILY, PRODUCT_INDUSTRY)
),
DIMENSIONS AS (
    SELECT
        DISTINCT 
        GEO,
        COUNTRY,
        CAMPAIGN_INDUSTRY,
        BUSINESS_TIER,
        ORIGIN_SEGMENT,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        AGGREGATED_BY
    FROM
        BASE_AGGREGATED
),
DIM_CAL AS (
    SELECT
        DISTINCT 
        WEEK_START_DATE,
        WEEK_NUMBER_FISCAL_QUARTER,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA
    FROM
        {{ ref('FFM_FIN_CALENDAR') }}
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
),
-- To populate weekly level combinations of all possible dimensions
DIM_COMBINATIONS_WEEK AS (
    SELECT
        DISTINCT CAL.*,
        DIM.*
    FROM
        DIM_CAL CAL
        CROSS JOIN DIMENSIONS DIM
),
FINAL AS (
    SELECT
        'LOWER' AS FUNNEL,
        'STORE_ORDERS' AS METRIC_GROUP,
        DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.WEEK_NUMBER_FISCAL_QUARTER,
        DIM.WEEK_START_DATE,
        DIM.PREVIOUS_FISCAL_QUARTER_NAME,
        DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.GEO,
        DIM.COUNTRY,
        DIM.CAMPAIGN_INDUSTRY,
        DIM.BUSINESS_TIER,
        DIM.ORIGIN_SEGMENT,
        DIM.PRODUCT_FAMILY,
        DIM.PRODUCT_INDUSTRY,
        DIM.IS_RESTRICTED_DATA,
        DIM.IS_CURRENT_QUARTER,
        BASE.STORE_NEW_ORDER_COUNT,
        PQ.STORE_NEW_ORDER_COUNT AS QOQ_STORE_NEW_ORDER_COUNT,
        PY.STORE_NEW_ORDER_COUNT AS YOY_STORE_NEW_ORDER_COUNT,
        DIM.AGGREGATED_BY AS ORDERS_AGGREGATED_BY,
        CURRENT_TIMESTAMP AS RUN_TIMESTAMP
    FROM DIM_COMBINATIONS_WEEK DIM
        -- Join at all dimensions
        LEFT JOIN BASE_AGGREGATED BASE --Join with base aggregated data
            ON DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = BASE.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
            AND DIM.WEEK_NUMBER_FISCAL_QUARTER = BASE.WEEK_NUMBER_FISCAL_QUARTER
            AND DIM.AGGREGATED_BY = BASE.AGGREGATED_BY
            AND COALESCE(DIM.GEO, '') = COALESCE(BASE.GEO, '')
            AND COALESCE(DIM.COUNTRY, '') = COALESCE(BASE.COUNTRY, '')
            AND COALESCE(DIM.CAMPAIGN_INDUSTRY, '') = COALESCE(BASE.CAMPAIGN_INDUSTRY, '')
            AND COALESCE(DIM.BUSINESS_TIER, '') = COALESCE(BASE.BUSINESS_TIER, '')
            AND COALESCE(DIM.ORIGIN_SEGMENT, '') = COALESCE(BASE.ORIGIN_SEGMENT, '')
            AND COALESCE(DIM.PRODUCT_FAMILY, '') = COALESCE(BASE.PRODUCT_FAMILY, '')
            AND COALESCE(DIM.PRODUCT_INDUSTRY, '') = COALESCE(BASE.PRODUCT_INDUSTRY, '')
        LEFT JOIN BASE_AGGREGATED PQ --Join with previous quarter to get QoQ
            ON DIM.PREVIOUS_FISCAL_QUARTER_NAME = PQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
            AND DIM.WEEK_NUMBER_FISCAL_QUARTER = PQ.WEEK_NUMBER_FISCAL_QUARTER
            AND DIM.AGGREGATED_BY = PQ.AGGREGATED_BY
            AND COALESCE(DIM.GEO, '') = COALESCE(PQ.GEO, '')
            AND COALESCE(DIM.COUNTRY, '') = COALESCE(PQ.COUNTRY, '')
            AND COALESCE(DIM.CAMPAIGN_INDUSTRY, '') = COALESCE(PQ.CAMPAIGN_INDUSTRY, '')
            AND COALESCE(DIM.BUSINESS_TIER, '') = COALESCE(PQ.BUSINESS_TIER, '')
            AND COALESCE(DIM.ORIGIN_SEGMENT, '') = COALESCE(PQ.ORIGIN_SEGMENT, '')
            AND COALESCE(DIM.PRODUCT_FAMILY, '') = COALESCE(PQ.PRODUCT_FAMILY, '')
            AND COALESCE(DIM.PRODUCT_INDUSTRY, '') = COALESCE(PQ.PRODUCT_INDUSTRY, '')
        LEFT JOIN BASE_AGGREGATED PY --Join with previous year quarter to get YoY
            ON DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = PY.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
            AND DIM.WEEK_NUMBER_FISCAL_QUARTER = PY.WEEK_NUMBER_FISCAL_QUARTER
            AND DIM.AGGREGATED_BY = PY.AGGREGATED_BY
            AND COALESCE(DIM.GEO, '') = COALESCE(PY.GEO, '')
            AND COALESCE(DIM.COUNTRY, '') = COALESCE(PY.COUNTRY, '')
            AND COALESCE(DIM.CAMPAIGN_INDUSTRY, '') = COALESCE(PY.CAMPAIGN_INDUSTRY, '')
            AND COALESCE(DIM.BUSINESS_TIER, '') = COALESCE(PY.BUSINESS_TIER, '')
            AND COALESCE(DIM.ORIGIN_SEGMENT, '') = COALESCE(PY.ORIGIN_SEGMENT, '')
            AND COALESCE(DIM.PRODUCT_FAMILY, '') = COALESCE(PY.PRODUCT_FAMILY, '')
            AND COALESCE(DIM.PRODUCT_INDUSTRY, '') = COALESCE(PY.PRODUCT_INDUSTRY, '')
)

-- Remove records with null in all metrics. This would remove unwanted records and reduce table size
SELECT *
FROM FINAL
WHERE NOT
    (
        STORE_NEW_ORDER_COUNT IS NULL
        AND QOQ_STORE_NEW_ORDER_COUNT IS NULL
        AND YOY_STORE_NEW_ORDER_COUNT IS NULL
    )