-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : ffm_trials_to_orders_monthly_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the configuration #}
{{
     config(
         materialized='table'
     )
}}

 {{
       config(
     post_hook = [
         "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_ENGINEERING",
         "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_QA"
     ]
   )
 }}

WITH TRIALS_ORDER AS
(
    SELECT ECC_SALES_ORDER_NBR,
            CC_FBM_TOTAL_ACV_NET3_CC,
            OXYGEN_ID,
            --product
            PRODUCT_FAMILY,
            PRODUCT_INDUSTRY,
            ORDER_DT,
         --   TRIAL_CONVERTED_FLAG,
            GEO,
            COUNTRY,
            GDPR_FLAG,
           -- TERM,
            SALES_CHANNEL,
            BUSINESS_TIER,
            FYQUARTER,
            FYWEEK,
            FROM {{ ref('FFM_TRIAL_ORDER_CONVERSION_STAGE') }}
            WHERE TRIAL_CONVERTED_FLAG = TRUE

),
TRIALS_ORDER_WITH_ADDED_DIM AS
(
    SELECT ECC_SALES_ORDER_NBR,
            CC_FBM_TOTAL_ACV_NET3_CC,
            OXYGEN_ID,

            --PRODUCT
            PRODUCT_FAMILY,
            PRODUCT_INDUSTRY,
          --  ORDER_DT,
            GEO,
            COUNTRY,
            GDPR_FLAG,
           -- TERM,
            SALES_CHANNEL,
            BUSINESS_TIER,
            FYQUARTER,
            FYWEEK,

            FIN_CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, --PREVIOUS_MONTH_START_DATE
            FIN_CAL.IS_CURRENT_QUARTER AS IS_CURRENT_QUARTER ,
            FIN_CAL.COMPLETED_WEEKS AS COMPLETED_WEEKS,
            FIN_CAL.fiscal_quarter_begin_date AS FISCAL_QUARTER_BEGIN_DATE,
            FIN_CAL.previous_fiscal_quarter_begin_date AS PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
            FIN_CAL.PREVIOUS_FISCAL_YEAR_QUARTER AS PREVIOUS_FISCAL_YEAR_QUARTER,
            FIN_CAL.PREVIOUS_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_QUARTER_NAME,
            FIN_CAL.PREVIOUS_MONTH_START_DATE AS PREVIOUS_MONTH_START_DATE,
            FIN_CAL.MONTH_START_DATE AS MONTH_START_DATE,
            FIN_CAL.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
            FIN_CAL.IS_RESTRICTED_DATA AS IS_RESTRICTED_DATA,
            FIN_CAL.WEEK_NUMBER_FISCAL_QUARTER --MONTH_START_DATE

            FROM TRIALS_ORDER TL
            INNER JOIN (
             SELECT
                DISTINCT
                FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
                fiscal_quarter_begin_date,
                previous_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
                previous_fiscal_quarter_begin_date,
                previous_fiscal_year_quarter,
                PREVIOUS_FISCAL_QUARTER_NAME,
                PREVIOUS_MONTH_START_DATE,
                IS_CURRENT_QUARTER,
                COMPLETED_WEEKS,
                MONTH_START_DATE,
                WEEK_NUMBER_FISCAL_QUARTER,
                IS_RESTRICTED_DATA,
                DATE_KEY
            FROM
                {{ ref('FFM_FIN_CALENDAR') }}
                WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
                ) FIN_CAL
                ON FIN_CAL.DATE_KEY = TL.ORDER_DT
),
PQ_PY_QTR AS (
    SELECT FYQUARTER
    FROM
        (
            SELECT DISTINCT FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FYQUARTER
            FROM
                TRIALS_ORDER_WITH_ADDED_DIM
            ORDER BY 1 DESC
        )
    QUALIFY ROW_NUMBER() OVER(ORDER BY FYQUARTER DESC) IN (1, 2, 5) -- Fetch current, previous & previous year quarter
),
LAST_COMPLETED_WEEK AS (
    SELECT
        MAX(WEEK_NUMBER_FISCAL_QUARTER) AS LAST_WEEK
    FROM TRIALS_ORDER_WITH_ADDED_DIM
    WHERE FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = (SELECT MAX(FYQUARTER) FROM PQ_PY_QTR)
),
--select * from TRIALS_ORDER_WITH_ADDED_DIM
BASE_AGGREGATED AS
(
    SELECT FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
    GEO, COUNTRY,
    GDPR_FLAG,BUSINESS_TIER,PRODUCT_FAMILY, PRODUCT_INDUSTRY, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        COUNT(DISTINCT ECC_SALES_ORDER_NBR) AS ORDER_NUMBERS,
         CONCAT(
            'QTR-GEO',
            IFF(GROUPING(COUNTRY) = 0, '-CNTRY', ''),
            IFF(GROUPING(BUSINESS_TIER) = 0, '-B_TIER', ''),
            IFF(GROUPING(PRODUCT_FAMILY) = 0, '-PROD_FAM', ''),
            IFF(GROUPING(PRODUCT_INDUSTRY) = 0, '-PROD_IND', '')
        ) AS AGGREGATED_BY
    FROM
         TRIALS_ORDER_WITH_ADDED_DIM
        -- WHERE  TRIAL_CONVERTED_FLAG = TRUE
        GROUP BY
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO,
         GDPR_FLAG,IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        CUBE(COUNTRY,BUSINESS_TIER,PRODUCT_FAMILY,PRODUCT_INDUSTRY)
),
QTD_AGGREGATED AS
(
    SELECT FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, COUNTRY,
    GDPR_FLAG,BUSINESS_TIER,PRODUCT_FAMILY, PRODUCT_INDUSTRY, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        --COUNT(DISTINCT ECC_SALES_ORDER_NBR) AS ORDER_NUMBERS,
        COUNT(DISTINCT ECC_SALES_ORDER_NBR) AS ORDER_NUMBERS,
         CONCAT(
            'QTR-GEO',
            IFF(GROUPING(COUNTRY) = 0, '-CNTRY', ''),
            IFF(GROUPING(BUSINESS_TIER) = 0, '-B_TIER', ''),
            IFF(GROUPING(PRODUCT_FAMILY) = 0, '-PROD_FAM', ''),
            IFF(GROUPING(PRODUCT_INDUSTRY) = 0, '-PROD_IND', '')
        ) AS AGGREGATED_BY
    FROM
         TRIALS_ORDER_WITH_ADDED_DIM
        -- WHERE  TRIAL_CONVERTED_FLAG = TRUE
        WHERE FISCAL_YEAR_AND_FISCAL_QUARTER_NAME IN (SELECT FYQUARTER FROM PQ_PY_QTR)
        AND FYWEEK <= (SELECT LAST_WEEK FROM LAST_COMPLETED_WEEK)
        GROUP BY
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        GEO, GDPR_FLAG,IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        CUBE(COUNTRY,BUSINESS_TIER,PRODUCT_FAMILY,PRODUCT_INDUSTRY)--FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
)
SELECT
    'LOWER' AS FUNNEL,
     'TRIAL_TO_ORDER' AS METRIC_GROUP,
     A.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
     A.PREVIOUS_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_QUARTER_NAME,
     A.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
     A.GEO AS GEO,
     A.COUNTRY AS COUNTRY,
     A.GDPR_FLAG AS GDPR_FLAG,
     A.BUSINESS_TIER AS BUSINESS_TIER,
     A.PRODUCT_FAMILY AS PRODUCT_FAMILY,
     A.PRODUCT_INDUSTRY AS PRODUCT_INDUSTRY,
     A.IS_RESTRICTED_DATA AS IS_RESTRICTED_DATA,
     A.IS_CURRENT_QUARTER AS IS_CURRENT_QUARTER,
     A.ORDER_NUMBERS AS ORDER_NUMBERS,

     CASE WHEN A.IS_CURRENT_QUARTER = 1 THEN QTD.ORDER_NUMBERS ELSE PQ.ORDER_NUMBERS
     END AS QOQ_ORDER_NUMBERS,

     CASE WHEN A.IS_CURRENT_QUARTER = 1 THEN PQTD.ORDER_NUMBERS ELSE PY.ORDER_NUMBERS
     END AS YOY_ORDER_NUMBERS,

     A.AGGREGATED_BY AS ORDERS_AGGREGATED_BY,
     CURRENT_TIMESTAMP AS RUN_TIMESTAMP

 FROM BASE_AGGREGATED A
     LEFT JOIN BASE_AGGREGATED PQ --Join with previous quarter to get QoQ
        ON A.PREVIOUS_FISCAL_QUARTER_NAME = PQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = PQ.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(PQ.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(PQ.COUNTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(PQ.BUSINESS_TIER, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(PQ.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(PQ.PRODUCT_INDUSTRY, '')--GDPR_FLAG
        AND COALESCE(A.GDPR_FLAG, '') = COALESCE(PQ.GDPR_FLAG, '')

     LEFT JOIN BASE_AGGREGATED PY --Join with previous year quarter to get YoY
        ON A.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = PY.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = PY.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(PY.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(PY.COUNTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(PY.BUSINESS_TIER, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(PY.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(PY.PRODUCT_INDUSTRY, '')
        AND COALESCE(A.GDPR_FLAG, '') = COALESCE(PY.GDPR_FLAG, '')

     LEFT JOIN QTD_AGGREGATED QTD --Join with previous quarter to get QTD
        ON A.PREVIOUS_FISCAL_QUARTER_NAME = QTD.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = QTD.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(QTD.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(QTD.COUNTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(QTD.BUSINESS_TIER, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(QTD.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(QTD.PRODUCT_INDUSTRY, '')
        AND COALESCE(A.GDPR_FLAG, '') = COALESCE(QTD.GDPR_FLAG, '')

     LEFT JOIN QTD_AGGREGATED PQTD --Join with previous year quarter to get PQTD
        ON A.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = PQTD.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = PQTD.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(PQTD.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(PQTD.COUNTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(PQTD.BUSINESS_TIER, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(PQTD.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(PQTD.PRODUCT_INDUSTRY, '')
        AND COALESCE(A.GDPR_FLAG, '') = COALESCE(PQTD.GDPR_FLAG, '')