-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : ffm_lower_funnel
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

-- Set the start and end dates
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT CALENDAR_DATE FROM ADP_PUBLISH.COMMON_REFERENCE_DATA_OPTIMIZED.DATE_TIME_HIERARCHY WHERE FISCAL_QUARTER_VS_CURRENT_NUMBER=-12 AND  FISCAL_QUARTER_DAY_NUMBER=1);" ,
        "SET END_DATE   = (SELECT CURRENT_DATE()-1);"
    ]
  )
}}

-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

WITH SFDC_CURRENCY AS (
  SELECT
      CURRENCY_ISOCODE,
      CURRENCY_CONVERSIONRATE,
      CASE
          WHEN RID=1 THEN '1990-01-01 00:00:00.000+00:00'
          ELSE MODIFIEDDATE
      END AS CURRENCY_FROM_DATE,
      LEAD(MODIFIEDDATE) OVER (PARTITION BY CURRENCY_ISOCODE ORDER BY MODIFIEDDATE ASC) AS CURRENCY_TO_DATE
  FROM
  (
      SELECT
        isocode::VARCHAR AS CURRENCY_ISOCODE,
        conversionrate::FLOAT AS CURRENCY_CONVERSIONRATE,
        MIN(lastmodifieddate::TIMESTAMP) AS MODIFIEDDATE,
        ROW_NUMBER() OVER(PARTITION BY CURRENCY_ISOCODE ORDER BY MODIFIEDDATE ASC) AS RID
      FROM {{ var('CURRENCYTYPE_SFDC_RAW') }}
      GROUP BY 1,2
  )
),

-- SFDC recordtypeid
SFDC_RECORDTYPE AS (

  SELECT
    id::VARCHAR AS RECORDTYPE_ID
    ,name::VARCHAR AS RECORDTYPE_NAME
    ,lastmodifieddate::VARCHAR AS RECORDTYPE_LASTMODIFIED_DATE
    ,ROW_NUMBER() OVER(PARTITION BY id::VARCHAR ORDER BY lastmodifieddate::VARCHAR DESC NULLS LAST) AS RECORDTYPE_RID
  FROM {{ var('RECORDTYPE_SFDC_RAW') }}
  QUALIFY RECORDTYPE_RID=1

),

SFDC_LEAD AS (
  SELECT
    id::VARCHAR AS LEAD_ID
    ,isdeleted::VARCHAR AS LEAD_IS_DELETED
    ,lead_id__c::VARCHAR AS LEAD_ID__C
    ,lead_type__c::VARCHAR AS LEAD_TYPE__C
    ,is_mql_lead_type__c::VARCHAR AS LEAD_IS_MQL_LEAD_TYPE
    ,account__c::VARCHAR AS LEAD_ACCOUNT_ID
    ,convertedopportunityid::VARCHAR AS CONVERTEDOPPORTUNITYID
    ,status::VARCHAR AS LEAD_STATUS
    ,createddate::VARCHAR AS LEAD_CREATED_DATE
    ,lead_closed_date__c::VARCHAR AS LEAD_CLOSED_DATE
    ,mi_score__c::VARCHAR AS LEAD_CBR_SCORE
    ,lastmodifieddate::VARCHAR AS LEAD_LASTMODIFIED_DATE
    ,ROW_NUMBER() OVER(PARTITION BY CONVERTEDOPPORTUNITYID::VARCHAR ORDER BY lastmodifieddate::VARCHAR DESC NULLS LAST) AS LEAD_RID
  FROM {{ var('LEAD_SFDC_RAW') }}
  QUALIFY LEAD_RID=1
),

SFDC_OPPORTUNITY AS (
    SELECT
        id as OPPORTUNITY_ID,
        opportunity_id__c as OPPORTUNITY_GUID,
        end_customer_csn__c as OPPORTUNITY_ACCOUNT_CSN,
        A.LEAD_ID__C as OPPO_LEAD_ID__C,
        -- b.account_csn,
        -- b.account_name,
        CLOSEDATE AS OPPO_CLOSEDATE,
        ACCOUNTID AS OPPO_ACCOUNTID,
        STAGENAME AS OPPO_STAGENAME,
        CONTRACT_TERM__C AS OPPO_CONTRACT_TERM__C,
        RENEWAL_STATUS__C AS OPPO_RENEWAL_STATUS__C,
        LASTMODIFIEDDATE AS OPPO_LASTMODIFIEDDATE,
        OPPORTUNITY_NUMBER__C AS OPPO_OPPORTUNITY_NUMBER__C,
        RENEWAL_TERM__C AS OPPO_RENEWAL_TERM__C,
        OPPORTUNITY_CLASSIFICATION__C AS OPPO_OPPORTUNITY_CLASSIFICATION__C,
        END_DATE__C AS OPPO_END_DATE__C,
        TOTAL_SEAT_COUNT__C AS OPPO_TOTAL_SEAT_COUNT__C,
        CREATEDDATE AS OPPO_CREATEDDATE,
        ISCLOSED AS OPPO_ISCLOSED,
        CONTRACTTYPE__C AS OPPO_CONTRACTTYPE__C,
        AMOUNT AS OPPO_AMOUNT,
        PO_NUMBER__C AS OPPO_PO_NUMBER__C,
        CREATEDBYID AS OPPO_CREATEDBYID,
        OPPORTUNITY_TYPE__C AS OPPO_OPPORTUNITY_TYPE__C,
        OPPORTUNITY_AMOUNT__C AS OPPO_OPPORTUNITY_AMOUNT__C,
        OWNERID AS OPPO_OWNERID,
        ADSK_OPPORTUNITY_STATUS__C AS OPPO_ADSK_OPPORTUNITY_STATUS__C,
        RENEWAL_TYPE__C AS OPPO_RENEWAL_TYPE__C,
        END_CUSTOMER_CSN__C AS OPPO_END_CUSTOMER_CSN__C,
        CAMPAIGNID AS OPPO_CAMPAIGNID,
        END_CUSTOMER_GEO__C AS OPPO_END_CUSTOMER_GEO__C,
        LASTMODIFIEDBYID AS OPPO_LASTMODIFIEDBYID,
        PRODUCT__C AS OPPO_PRODUCT__C,
        LEADSOURCE AS OPPO_LEADSOURCE,
        PRICEBOOK2ID AS OPPO_PRICEBOOK2ID,
        -- NAMED_ACCOUNT_GROUP__C AS OPPO_NAMED_ACCOUNT_GROUP__C,
        NR.NAG_REPLACEMENT AS OPPO_NAMED_ACCOUNT_GROUP__C,
        SALES_REGION__C AS OPPO_SALES_REGION__C,
        PARENT_INDUSTRY_SEGMENT__C AS OPPO_PARENT_INDUSTRY_SEGMENT__C,
        ACTUAL_CLOSE_DATE__C AS OPPO_ACTUAL_CLOSE_DATE__C,
        REASON__C AS OPPO_REASON__C,
        OPPORTUNITY_AGE__C AS OPPO_OPPORTUNITY_AGE__C,
        PARTNER_ACCOUNT_CSN__C AS OPPO_PARTNER_ACCOUNT_CSN__C,
        PRIMARY_CONTACT_ID__C AS OPPO_PRIMARY_CONTACT_ID__C,
        primary_contact__c AS primary_contact__c,
        PARTNER_ACCOUNT__C AS OPPO_PARTNER_ACCOUNT__C,
        PARTNER_ACCOUNT_NAME__C AS OPPO_PARTNER_ACCOUNT_NAME__C,
        CONTACTID AS OPPO_CONTACTID,
        CURRENCYISOCODE AS OPPO_CURRENCYISOCODE,
        END_CUSTOMER_COUNTRY__C AS OPPO_END_CUSTOMER_COUNTRY__C,
        APRIMO_ACTIVITY_ID__C AS OPPO_APRIMO_ACTIVITY_ID__C,
        FULFILLMENT_CATEGORY__C AS OPPO_FULFILLMENT_CATEGORY__C,
        APRIMO_ACTIVITY_NAME__C AS OPP_APRIMO_ACTIVITY_NAME__C,
        FORECASTCATEGORY AS OPPO_FORECASTCATEGORY,
        OPPORTUNITY_SELF_PROSPECTING_SOURCE__C as OPPORTUNITY_SELF_PROSPECTING_SOURCE__C,
        NAME AS OPPO_NAME,
        RECORDTYPEID AS OPPO_RECORDTYPEID,
        ISWON AS OPPO_ISWON,
        CASE
            WHEN STAGENAME IN ('Close/Lost','Closed','Closed / Lost','Closed /Lost','Closed/Lost','Rejected','--None--') THEN 'Not Active'
            WHEN STAGENAME IN ('Stage 1','Stage 2','Stage 3','Stage 4','1-Prospecting','2-Qualifying','3-Solution Building','4-Proposal/Negotiation') THEN 'Open'
            WHEN STAGENAME IN ('Stage 5','5-Closed/Won','Won','Closed-Won') THEN 'Closed'
            ELSE STAGENAME
            END AS OPPO_PIPELINE_TYPE,
        CAST(ACV__C::VARCHAR AS DECIMAL(38,12)) AS OPPO_ACV__C,
        OPPO_ACV__C / NVL(CURR.CURRENCY_CONVERSIONRATE,1) AS OPPO_CONVERTED_ACV,
        C.LEAD_ID as LEAD_GUID,
        CASE
            WHEN C.CONVERTEDOPPORTUNITYID IS NOT NULL THEN 'Y'
            ELSE 'N'
        END AS LEADS_OPPORTUNITY_CONVERTED_FLAG,
        TO_DATE(TO_VARCHAR(DBT_UPDATED_TS,'yyyymmdd'),'YYYYMMDD')  AS OPPO_TABLE_LAST_REFRESH_DATE

    FROM {{ var('OPPORTUNITY_SFDC_RAW') }} A --BSD_PUBLISH.SFDC_SHARED.OPPORTUNITY
        LEFT JOIN SFDC_CURRENCY CURR ON A.CURRENCYISOCODE::VARCHAR = CURR.CURRENCY_ISOCODE AND CURR.CURRENCY_TO_DATE IS NULL
        LEFT JOIN SFDC_LEAD C on C.CONVERTEDOPPORTUNITYID = A.ID
        LEFT JOIN RAW.LOOKUPS.NAG_REPLACEMENT_MAPPING NR ON A.NAMED_ACCOUNT_GROUP__C = NR.NAG
    WHERE (
        OPPO_CREATEDDATE >=  $START_DATE
      OR OPPO_CLOSEDATE >= $START_DATE
    )
),

-- SFDC Opportunity line item
SFDC_OPPO_LINEITEM AS (
    SELECT
       opportunityid::VARCHAR AS OPPORTUNITYLINEITEM_OPPO_ID
      ,line_item_id__c::VARCHAR AS OPPORTUNITYLINEITEM_LINE_ITEM_ID
      ,line_license_type__c::VARCHAR AS OPPORTUNITYLINEITEM_LINE_LICENSE_TYPE
      ,line_item_action__C::VARCHAR AS OPPORTUNITYLINEITEM_LINE_ITEM_ACTION
      ,term__c::VARCHAR AS OPPORTUNITYLINEITEM_LINE_ITEM_TERM
      ,currencyisocode::VARCHAR AS OPPORTUNITYLINEITEM_CURRENCY_ISO_CODE
      ,PRODUCT2ID::VARCHAR AS OPPORTUNITYLINEITEM_PRODUCT2ID
      ,productcode::VARCHAR AS OPPORTUNITYLINEITEM_PRODUCTCODE
      ,product_type__c::VARCHAR AS OPPORTUNITYLINEITEM_PRODUCTTYPE
      ,seats_ref__c::NUMBER AS OPPORTUNITYLINEITEM_SEATS
      ,CAST(line_item_acv__c::VARCHAR AS DECIMAL(38,12)) AS OPPORTUNITYLINEITEM_LINE_ITEM_ACV
      ,CAST(totalprice::VARCHAR AS DECIMAL(38,12)) AS OPPORTUNITYLINEITEM_TOTALPRICE
      ,OPPORTUNITYLINEITEM_LINE_ITEM_ACV / NVL(B.CURRENCY_CONVERSIONRATE,1) AS OPPORTUNITY_CONVERTED_LINEITEM_ACV
      ,OPPORTUNITYLINEITEM_TOTALPRICE / NVL(B.CURRENCY_CONVERSIONRATE,1) AS OPPORTUNITYLINEITEM_CONVERTED_TOTAL_PRICE
      ,lastmodifieddate::VARCHAR AS OPPORTUNITYLINEITEM_LASTMODIFIED_DATE
    FROM {{ var('OPPORTUNITYLINEITEM_SFDC_RAW') }} A
    LEFT JOIN SFDC_CURRENCY B
    ON
      A.currencyisocode::VARCHAR=B.CURRENCY_ISOCODE AND B.CURRENCY_TO_DATE IS NULL
    WHERE NVL(UPPER(A.RENEWAL_STATUS__C),'') != 'TRANSITIONED'
),

--SFDC QUOTE
SFDC_QUOTE AS (
    SELECT
        ID AS QUOTE_ID,
        SBQQ__ACCOUNT__C AS QUOTE_ACCOUNT,
        ACCOUNT_NAME_TEXT__C AS QUOTE_ACCOUNT_NAME,
        ACCOUNT_COUNTRY__C AS QUOTE_CUSTOMER_COUNTRY,
        SBQQ__STATUS__C AS QUOTE_STATUS,
        QUOTEDDATE__C AS QUOTED_DATE,
        SBQQ__OPPORTUNITY2__C as QUOTE_OPPO_ID,
        OPPORTUNITY__C AS QUOTE_OPPO_NUMBER,
        AGENT_ACCOUNT_NAME__C AS QUOTE_AGENT_ACCOUNT_NAME,
        NAME AS QUOTE_NAME,
        CREATEDDATE AS QUOTE_CREATED_DATE,
        SALESPLATFORMCODE__C AS QUOTE_SALES_PLATFORM,
        SALESCHANNELTYPE__C AS QUOTE_SALES_CHANNEL,
        SBQQ__TYPE__C AS QUOTE_SBQQ__TYPE__C,
        ORDER_NUMBER__C AS QUOTE_ORDER_NUMBER__C,
        SBQQ__LINEITEMCOUNT__C AS QUOTE_SBQQ__LINEITEMCOUNT__C
        , CASE WHEN SBQQ__STATUS__C IN ('Expired', 'Draft', 'Cancelled', NULL) THEN 'Not Active'
                WHEN SBQQ__STATUS__C IN ('T&C Negotiation', 'Quoted', 'T&C Approved', 'Order Submitted', 'Under Review') THEN 'Open'
                WHEN SBQQ__STATUS__C = 'Ordered' THEN 'Closed'
                ELSE SBQQ__STATUS__C
                END AS PIPELINE_TYPE
        , CASE
            WHEN AGENT_ACCOUNT_NAME__C IS NOT NULL OR AGENT_CONTACT_NAME__C IS NOT NULL THEN 'TRUE'
            WHEN AGENT_ACCOUNT_NAME__C IS NOT NULL AND AGENT_CONTACT_NAME__C IS NULL AND SBQQ__SALESREP__C IS NOT NULL THEN 'BOTH'
            WHEN AGENT_ACCOUNT_NAME__C IS NULL AND AGENT_CONTACT_NAME__C IS NOT NULL AND SBQQ__SALESREP__C IS NOT NULL THEN 'BOTH'
            ELSE 'FALSE'
            END AS IS_PARTNER
    FROM {{var('SBQQ_QUOTE_C')}}
    WHERE QUOTE_CREATED_DATE BETWEEN $START_DATE AND $END_DATE
),

SFDC_QUOTE_WITH_LINEITEM AS (
    SELECT
        'SFDC_QUOTE' AS RECORD_SOURCE
        ,O.OPPORTUNITY_ID
        ,O.OPPORTUNITY_GUID
        ,O.OPPORTUNITY_ACCOUNT_CSN
        ,O.OPPO_LEAD_ID__C
        ,O.OPPO_CLOSEDATE
        ,O.OPPO_ACCOUNTID
        ,O.OPPO_STAGENAME
        ,O.OPPO_CONTRACT_TERM__C
        ,O.OPPO_RENEWAL_STATUS__C
        ,O.OPPO_LASTMODIFIEDDATE
        ,O.OPPO_OPPORTUNITY_NUMBER__C
        ,O.OPPO_RENEWAL_TERM__C
        ,O.OPPO_OPPORTUNITY_CLASSIFICATION__C
        ,O.OPPO_END_DATE__C
        ,O.OPPO_TOTAL_SEAT_COUNT__C
        ,O.OPPO_CREATEDDATE
        ,O.OPPO_ISCLOSED
        ,O.OPPO_CONTRACTTYPE__C
        ,O.OPPO_AMOUNT
        ,O.OPPO_PO_NUMBER__C
        ,O.OPPO_CREATEDBYID
        ,O.OPPO_OPPORTUNITY_TYPE__C
        ,O.OPPO_OPPORTUNITY_AMOUNT__C
        ,O.OPPO_OWNERID
        ,O.OPPO_ADSK_OPPORTUNITY_STATUS__C
        ,O.OPPO_RENEWAL_TYPE__C
        ,O.OPPO_END_CUSTOMER_CSN__C
        ,O.OPPO_CAMPAIGNID
        ,O.OPPO_END_CUSTOMER_GEO__C
        ,O.OPPO_LASTMODIFIEDBYID
        ,O.OPPO_PRODUCT__C
        ,O.OPPO_LEADSOURCE
        ,O.OPPO_PRICEBOOK2ID
        ,O.OPPO_NAMED_ACCOUNT_GROUP__C
        ,O.OPPO_SALES_REGION__C
        ,O.OPPO_PARENT_INDUSTRY_SEGMENT__C
        ,O.OPPO_ACTUAL_CLOSE_DATE__C
        ,O.OPPO_REASON__C
        ,O.OPPO_OPPORTUNITY_AGE__C
        ,O.OPPO_PARTNER_ACCOUNT_CSN__C
        ,O.OPPO_PRIMARY_CONTACT_ID__C
        ,O.primary_contact__c
        ,O.OPPO_PARTNER_ACCOUNT__C
        ,O.OPPO_PARTNER_ACCOUNT_NAME__C
        ,O.OPPO_CONTACTID
        ,O.OPPO_CURRENCYISOCODE
        ,O.OPPO_END_CUSTOMER_COUNTRY__C
        ,O.OPPO_APRIMO_ACTIVITY_ID__C
        ,O.OPPO_FULFILLMENT_CATEGORY__C
        ,O.OPP_APRIMO_ACTIVITY_NAME__C
        ,O.OPPO_FORECASTCATEGORY
        ,O.OPPORTUNITY_SELF_PROSPECTING_SOURCE__C
        ,O.OPPO_NAME
        ,O.OPPO_RECORDTYPEID AS QUOTE_OPPO_RECORD_TYPE
        ,O.OPPO_PIPELINE_TYPE
        ,CASE
                WHEN OPPO_FULFILLMENT_CATEGORY__C = 'Direct' THEN 'FALSE'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IN ('Agency','Indirect') AND u.name IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'TRUE'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IN('Agency','Indirect') AND u.name NOT IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'BOTH'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IN ('Agency','Indirect') THEN 'TRUE'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IS NULL THEN 'FALSE'
                WHEN U.NAME IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'TRUE'
                WHEN U.NAME NOT IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'FALSE'
                ELSE NULL
            END AS IS_Partner
        ,O.OPPO_ISWON
        ,O.OPPO_ACV__C
        ,O.OPPO_CONVERTED_ACV
        ,CASE
            WHEN O.OPPORTUNITY_ID IS NULL THEN TRUE
            WHEN O.OPPORTUNITY_ID IS NOT NULL THEN FALSE
            ELSE  O.OPPO_STAGENAME || Q.QUOTE_STATUS
         END MISSING_OPPO

        , CASE
            WHEN NOT(O.OPPO_STAGENAME ILIKE 'won') AND Q.QUOTE_STATUS = 'Ordered' THEN TRUE
            ELSE FALSE
         END OPEN_ORDERED
        ,O.OPPO_TABLE_LAST_REFRESH_DATE

        ,RT.RECORDTYPE_NAME AS OPPORTUNITY_RECORD_TYPE

        ,TRUE AS HAS_QUOTE
        ,Q.QUOTE_ID
        ,Q.QUOTE_ACCOUNT
        ,Q.QUOTE_ACCOUNT_NAME
        ,Q.QUOTE_CUSTOMER_COUNTRY
        ,Q.QUOTE_STATUS
        ,Q.QUOTED_DATE
        ,Q.QUOTE_OPPO_NUMBER
        ,Q.QUOTE_AGENT_ACCOUNT_NAME
        ,Q.QUOTE_NAME
        ,Q.QUOTE_CREATED_DATE
        ,Q.QUOTE_SALES_PLATFORM
        ,Q.QUOTE_SALES_CHANNEL
        ,Q.QUOTE_SBQQ__TYPE__C
        ,Q.QUOTE_ORDER_NUMBER__C
        ,Q.QUOTE_SBQQ__LINEITEMCOUNT__C

        ,NULL AS OPPORTUNITYLINEITEM_OPPO_ID
        ,NULL AS OPPORTUNITYLINEITEM_LINE_ITEM_ID
        ,NULL AS OPPORTUNITYLINEITEM_LINE_LICENSE_TYPE
        ,NULL AS OPPORTUNITYLINEITEM_LINE_ITEM_ACTION
        ,NULL AS OPPORTUNITYLINEITEM_LINE_ITEM_TERM
        ,NULL AS OPPORTUNITYLINEITEM_CURRENCY_ISO_CODE
        ,NULL AS OPPORTUNITYLINEITEM_PRODUCT2ID
        ,NULL AS OPPORTUNITYLINEITEM_PRODUCTCODE
        ,NULL AS OPPORTUNITYLINEITEM_PRODUCTTYPE
        ,NULL AS OPPORTUNITYLINEITEM_SEATS
        ,NULL AS OPPORTUNITYLINEITEM_LINE_ITEM_ACV
        ,NULL AS OPPORTUNITYLINEITEM_TOTALPRICE
        ,NULL AS OPPORTUNITY_CONVERTED_LINEITEM_ACV
        ,NULL AS OPPORTUNITYLINEITEM_CONVERTED_TOTAL_PRICE
        ,NULL AS OPPORTUNITYLINEITEM_LASTMODIFIED_DATE

        , QLI.ID QUOTE_LINE_ID
        , QLI.NAME AS QUOTE_LINE_NAME
        , QLI.Term__c AS QLI_TERM
        , QLI.TERM_DESCRIPTION__C QLI_TERM_DESCRIPTION
        , QLI.LineItemAction__c AS QLI_LICENCE_TYPE
        , QLI.PRODUCTMATERIALGROUP__C AS QLI_PRODUCT_GROUP
        , QLI.SBQQ__PRODUCTCODE__C AS QUOTE_SBQQ__PRODUCTCODE__C
        , CAST(QLI.NETAMOUNT__C::VARCHAR AS DECIMAL(38,12)) QLI_NETAMOUNT
        , (QLI_NETAMOUNT/NVL(CURR.CURRENCY_CONVERSIONRATE,1)) AS QLI_NETAMOUNT_CONVERTED
        , QLI_NETAMOUNT_CONVERTED * (CASE WHEN QLI.Term__c = 'A07' THEN 365
                WHEN QLI.Term__c = 'A02' THEN 12
                WHEN QLI.Term__c = 'A01' THEN 1
                WHEN QLI.Term__c = 'A06' THEN 1/3
                ELSE 1
                END) AS  QLI_CONVERTED_ACV

        ,REC.RECORDTYPE_NAME AS TRANSACTION_MODEL

        ,A.ACCOUNT_CSN__C AS SFDC_ACCOUNT_CSN
        ,A.NAME AS SFDC_ACCOUNT_NAME
        ,A.ACCOUNT_SEGMENT__C AS SFDC_ACCOUNT_SEGMENT
        ,A.INDUSTRY_GROUP__C AS SFDC_ACCOUNT_INDUSTRY_GROUP
        ,A.TYPE AS SFDC_ACCOUNT_TYPE
        ,A.GEO__C AS SFDC_ACCOUNT_GEO
        ,A.PARENT_ACCOUNT_CSN__C AS SFDC_PARENT_ACCOUNT_CSN

        ,P2.NAME AS SFDC_PRODUCT_LINE
        ,P2.OFFERINGID__C AS SFDC_OFFERING_ID
        ,P2.CONTRACT_TERM__C SFDC_CONTRACT_TERM_DESCRIPTION
        ,P2.MATERIAL_GROUP__C AS SFDC_PRODUCT_GROUP

    FROM SFDC_QUOTE Q
    LEFT JOIN {{ var('SBQQ_QUOTELINE_C') }} QLI ON Q.QUOTE_ID = QLI.SBQQ__QUOTE__C
    LEFT JOIN SFDC_OPPORTUNITY O ON O.OPPORTUNITY_ID = Q.QUOTE_OPPO_ID
    LEFT JOIN SFDC_CURRENCY CURR ON QLI.CURRENCYISOCODE::VARCHAR = CURR.CURRENCY_ISOCODE AND CURR.CURRENCY_TO_DATE IS NULL
    LEFT JOIN {{ var('ACCOUNT_SFDC_RAW') }} A ON Q.QUOTE_ACCOUNT = A.ID
    LEFT JOIN BSD_PUBLISH.SFDC_SHARED.PRODUCT2 P2 ON P2.ID = QLI.SBQQ__Product__c
    LEFT JOIN SFDC_RECORDTYPE REC on REC.RECORDTYPE_ID = P2.RECORDTYPEID
    LEFT JOIN SFDC_RECORDTYPE RT ON O.OPPO_RECORDTYPEID = RT.RECORDTYPE_ID
    LEFT JOIN BSD_PUBLISH.SFDC_SHARED.USER U ON U.ID = O.OPPO_OWNERID
),

--COMBINING OPPORTUNITY WITH OPPORTUNITY LINEITEM
SFDC_OPPO_WITH_LINEITEM AS (
    SELECT
        'SFDC_OPPORTUNITY' AS RECORD_SOURCE
        ,O.OPPORTUNITY_ID
        ,O.OPPORTUNITY_GUID
        ,O.OPPORTUNITY_ACCOUNT_CSN
        ,O.OPPO_LEAD_ID__C
        ,O.OPPO_CLOSEDATE
        ,O.OPPO_ACCOUNTID
        ,O.OPPO_STAGENAME
        ,O.OPPO_CONTRACT_TERM__C
        ,O.OPPO_RENEWAL_STATUS__C
        ,O.OPPO_LASTMODIFIEDDATE
        ,O.OPPO_OPPORTUNITY_NUMBER__C
        ,O.OPPO_RENEWAL_TERM__C
        ,O.OPPO_OPPORTUNITY_CLASSIFICATION__C
        ,O.OPPO_END_DATE__C
        ,O.OPPO_TOTAL_SEAT_COUNT__C
        ,O.OPPO_CREATEDDATE
        ,O.OPPO_ISCLOSED
        ,O.OPPO_CONTRACTTYPE__C
        ,O.OPPO_AMOUNT
        ,O.OPPO_PO_NUMBER__C
        ,O.OPPO_CREATEDBYID
        ,O.OPPO_OPPORTUNITY_TYPE__C
        ,O.OPPO_OPPORTUNITY_AMOUNT__C
        ,O.OPPO_OWNERID
        ,O.OPPO_ADSK_OPPORTUNITY_STATUS__C
        ,O.OPPO_RENEWAL_TYPE__C
        ,O.OPPO_END_CUSTOMER_CSN__C
        ,O.OPPO_CAMPAIGNID
        ,O.OPPO_END_CUSTOMER_GEO__C
        ,O.OPPO_LASTMODIFIEDBYID
        ,O.OPPO_PRODUCT__C
        ,O.OPPO_LEADSOURCE
        ,O.OPPO_PRICEBOOK2ID
        ,O.OPPO_NAMED_ACCOUNT_GROUP__C
        ,O.OPPO_SALES_REGION__C
        ,O.OPPO_PARENT_INDUSTRY_SEGMENT__C
        ,O.OPPO_ACTUAL_CLOSE_DATE__C
        ,O.OPPO_REASON__C
        ,O.OPPO_OPPORTUNITY_AGE__C
        ,O.OPPO_PARTNER_ACCOUNT_CSN__C
        ,O.OPPO_PRIMARY_CONTACT_ID__C
        ,O.primary_contact__c
        ,O.OPPO_PARTNER_ACCOUNT__C
        ,O.OPPO_PARTNER_ACCOUNT_NAME__C
        ,O.OPPO_CONTACTID
        ,O.OPPO_CURRENCYISOCODE
        ,O.OPPO_END_CUSTOMER_COUNTRY__C
        ,O.OPPO_APRIMO_ACTIVITY_ID__C
        ,O.OPPO_FULFILLMENT_CATEGORY__C
        ,O.OPP_APRIMO_ACTIVITY_NAME__C
        ,O.OPPO_FORECASTCATEGORY
        ,O.OPPORTUNITY_SELF_PROSPECTING_SOURCE__C
        ,O.OPPO_NAME
        ,O.OPPO_RECORDTYPEID
        ,O.OPPO_PIPELINE_TYPE
        ,CASE
                WHEN OPPO_FULFILLMENT_CATEGORY__C = 'Direct' THEN 'FALSE'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IN ('Agency','Indirect') AND u.name IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'TRUE'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IN('Agency','Indirect') AND u.name NOT IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'BOTH'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IN ('Agency','Indirect') THEN 'TRUE'
                WHEN OPPO_FULFILLMENT_CATEGORY__C IS NULL THEN 'FALSE'
                WHEN U.NAME IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'TRUE'
                WHEN U.NAME NOT IN('Admin User','CM_ADSK2','CM_ADSK','AMER_USER','EMEA_USER','APAC_USER') THEN 'FALSE'
                ELSE NULL
            END AS IS_Partner
        ,O.OPPO_ISWON
        ,O.OPPO_ACV__C
        ,O.OPPO_CONVERTED_ACV
        ,NULL AS MISSING_OPPO
        ,NULL AS OPEN_ORDERED
        ,O.OPPO_TABLE_LAST_REFRESH_DATE

        ,RT.RECORDTYPE_NAME AS OPPORTUNITY_RECORD_TYPE

        ,CASE WHEN Q.QUOTE_OPPO_ID = O.OPPORTUNITY_ID THEN TRUE ELSE FALSE END AS HAS_QUOTE
        ,Q.QUOTE_ID
        ,Q.QUOTE_ACCOUNT
        ,Q.QUOTE_ACCOUNT_NAME
        ,Q.QUOTE_CUSTOMER_COUNTRY
        ,Q.QUOTE_STATUS
        ,Q.QUOTED_DATE
        ,Q.QUOTE_OPPO_NUMBER
        ,Q.QUOTE_AGENT_ACCOUNT_NAME
        ,Q.QUOTE_NAME
        ,Q.QUOTE_CREATED_DATE
        ,Q.QUOTE_SALES_PLATFORM
        ,Q.QUOTE_SALES_CHANNEL
        ,Q.QUOTE_SBQQ__TYPE__C
        ,Q.QUOTE_ORDER_NUMBER__C
        ,Q.QUOTE_SBQQ__LINEITEMCOUNT__C

        ,OLI.OPPORTUNITYLINEITEM_OPPO_ID
        ,OLI.OPPORTUNITYLINEITEM_LINE_ITEM_ID
        ,OLI.OPPORTUNITYLINEITEM_LINE_LICENSE_TYPE
        ,OLI.OPPORTUNITYLINEITEM_LINE_ITEM_ACTION
        ,OLI.OPPORTUNITYLINEITEM_LINE_ITEM_TERM
        ,OLI.OPPORTUNITYLINEITEM_CURRENCY_ISO_CODE
        ,OLI.OPPORTUNITYLINEITEM_PRODUCT2ID
        ,OLI.OPPORTUNITYLINEITEM_PRODUCTCODE
        ,OLI.OPPORTUNITYLINEITEM_PRODUCTTYPE
        ,OLI.OPPORTUNITYLINEITEM_SEATS
        ,OLI.OPPORTUNITYLINEITEM_LINE_ITEM_ACV
        ,OLI.OPPORTUNITYLINEITEM_TOTALPRICE
        ,OLI.OPPORTUNITY_CONVERTED_LINEITEM_ACV
        ,OLI.OPPORTUNITYLINEITEM_CONVERTED_TOTAL_PRICE
        ,OLI.OPPORTUNITYLINEITEM_LASTMODIFIED_DATE

        ,NULL AS QUOTE_LINE_ID
        ,NULL AS QUOTE_LINE_NAME
        ,NULL AS QLI_TERM
        ,NULL AS QLI_TERM_DESCRIPTION
        ,NULL AS QLI_LICENCE_TYPE
        ,NULL AS QLI_PRODUCT_GROUP
        ,NULL AS QUOTE_SBQQ__PRODUCTCODE__C
        ,NULL AS QLI_NETAMOUNT
        ,NULL AS QLI_NETAMOUNT_CONVERTED
        ,NULL AS QLI_CONVERTED_ACV

        ,REC.RECORDTYPE_NAME AS TRANSACTION_MODEL

        ,A.ACCOUNT_CSN__C AS SFDC_ACCOUNT_CSN
        ,A.NAME AS SFDC_ACCOUNT_NAME
        ,A.ACCOUNT_SEGMENT__C AS SFDC_ACCOUNT_SEGMENT
        ,A.INDUSTRY_GROUP__C AS SFDC_ACCOUNT_INDUSTRY_GROUP
        ,A.TYPE AS SFDC_ACCOUNT_TYPE
        ,A.GEO__C AS SFDC_ACCOUNT_GEO
        ,A.PARENT_ACCOUNT_CSN__C AS SFDC_PARENT_ACCOUNT_CSN

        ,P2.NAME AS SFDC_PRODUCT_LINE
        ,P2.OFFERINGID__C AS SFDC_OFFERING_ID
        ,P2.CONTRACT_TERM__C SFDC_CONTRACT_TERM_DESCRIPTION
        ,P2.MATERIAL_GROUP__C AS SFDC_PRODUCT_GROUP

    FROM SFDC_OPPORTUNITY O
        LEFT JOIN SFDC_OPPO_LINEITEM OLI ON O.OPPORTUNITY_ID = OLI.OPPORTUNITYLINEITEM_OPPO_ID
        --LEFT JOIN SFDC_CURRENCY AS CURR ON OLI.CURRENCYISOCODE = CURR.ISOCODE --AND CURR.ISACTIVE = 'TRUE'
        LEFT JOIN {{var('ACCOUNT_SFDC_RAW')}} A ON O.OPPO_ACCOUNTID = A.ID
        LEFT JOIN BSD_PUBLISH.SFDC_SHARED.PRODUCT2 P2 ON OLI.OPPORTUNITYLINEITEM_PRODUCT2ID = P2.ID
        LEFT JOIN SFDC_RECORDTYPE REC on REC.RECORDTYPE_ID = P2.RECORDTYPEID
        LEFT JOIN SFDC_RECORDTYPE RT ON O.OPPO_RECORDTYPEID = RT.RECORDTYPE_ID
        LEFT JOIN BSD_PUBLISH.SFDC_SHARED.USER U ON U.ID = O.OPPO_OWNERID
        LEFT JOIN (SELECT * FROM SFDC_QUOTE WHERE QUOTE_STATUS = 'Ordered') Q ON O.OPPORTUNITY_ID = Q.QUOTE_OPPO_ID

),

SFDC_QUOTE_OPPO_COMBINED AS (
    SELECT * FROM SFDC_QUOTE_WITH_LINEITEM
    UNION ALL
    SELECT * FROM SFDC_OPPO_WITH_LINEITEM
)


SELECT DISTINCT
         CASE
            WHEN FIN.SRC_ID IS NOT NULL AND A.QUOTE_NAME IS NOT NULL THEN 'FINMART_SFDC'
            WHEN FIN.SRC_ID IS NOT NULL AND A.QUOTE_NAME IS NULL THEN 'FINMART'
            ELSE A.RECORD_SOURCE
         END AS RECORD_SOURCE
        ,A.OPPORTUNITY_ID
        ,A.OPPORTUNITY_GUID
        ,A.OPPORTUNITY_ACCOUNT_CSN
        ,A.OPPO_LEAD_ID__C
        ,A.OPPO_CLOSEDATE
        ,A.OPPO_ACCOUNTID
        ,A.OPPO_STAGENAME
        ,A.OPPO_CONTRACT_TERM__C
        ,A.OPPO_RENEWAL_STATUS__C
        ,A.OPPO_LASTMODIFIEDDATE
        ,A.OPPO_OPPORTUNITY_NUMBER__C
        ,A.OPPO_RENEWAL_TERM__C
        ,A.OPPO_OPPORTUNITY_CLASSIFICATION__C
        ,A.OPPO_END_DATE__C
        ,A.OPPO_TOTAL_SEAT_COUNT__C
        ,A.OPPO_CREATEDDATE
        ,A.OPPO_ISCLOSED
        ,A.OPPO_CONTRACTTYPE__C
        ,A.OPPO_AMOUNT
        ,A.OPPO_PO_NUMBER__C
        ,A.OPPO_CREATEDBYID
        ,A.OPPO_OPPORTUNITY_TYPE__C
        ,A.OPPO_OPPORTUNITY_AMOUNT__C
        ,A.OPPO_OWNERID
        ,A.OPPO_ADSK_OPPORTUNITY_STATUS__C
        ,A.OPPO_RENEWAL_TYPE__C
        ,A.OPPO_END_CUSTOMER_CSN__C
        ,A.OPPO_CAMPAIGNID
        ,A.OPPO_END_CUSTOMER_GEO__C
        ,A.OPPO_LASTMODIFIEDBYID
        ,A.OPPO_PRODUCT__C
        ,A.OPPO_LEADSOURCE
        ,A.OPPO_PRICEBOOK2ID
        ,A.OPPO_NAMED_ACCOUNT_GROUP__C
        ,A.OPPO_SALES_REGION__C
        ,A.OPPO_PARENT_INDUSTRY_SEGMENT__C
        ,A.OPPO_ACTUAL_CLOSE_DATE__C
        ,A.OPPO_REASON__C
        ,A.OPPO_OPPORTUNITY_AGE__C
        ,A.OPPO_PARTNER_ACCOUNT_CSN__C
        ,A.OPPO_PRIMARY_CONTACT_ID__C
        ,A.primary_contact__c
        ,A.OPPO_PARTNER_ACCOUNT__C
        ,A.OPPO_PARTNER_ACCOUNT_NAME__C
        ,A.OPPO_CONTACTID
        ,A.OPPO_CURRENCYISOCODE
        ,A.OPPO_END_CUSTOMER_COUNTRY__C
        ,A.OPPO_APRIMO_ACTIVITY_ID__C
        ,A.OPPO_FULFILLMENT_CATEGORY__C
        ,A.OPP_APRIMO_ACTIVITY_NAME__C
        ,A.OPPO_FORECASTCATEGORY
        ,A.OPPORTUNITY_SELF_PROSPECTING_SOURCE__C
        ,A.OPPO_NAME
        ,A.OPPO_PIPELINE_TYPE
        ,A.IS_Partner
        ,A.OPPO_ISWON
        ,A.OPPO_ACV__C
        ,A.OPPO_CONVERTED_ACV
        ,A.MISSING_OPPO
        ,A.OPEN_ORDERED
        ,A.OPPO_TABLE_LAST_REFRESH_DATE

        ,MPM.MARKETING_CONTRIBUTION_TYPE
        ,MPM.CONV_ACV AS MPM_CONVERSION_ACV

        ,A.OPPORTUNITY_RECORD_TYPE

        ,A.HAS_QUOTE
        ,A.QUOTE_ID
        ,A.QUOTE_ACCOUNT
        ,A.QUOTE_ACCOUNT_NAME
        ,A.QUOTE_CUSTOMER_COUNTRY
        ,A.QUOTE_STATUS
        ,A.QUOTED_DATE
        ,A.QUOTE_OPPO_NUMBER
        ,A.QUOTE_AGENT_ACCOUNT_NAME
        ,A.QUOTE_NAME
        ,A.QUOTE_CREATED_DATE
        ,A.QUOTE_SALES_PLATFORM
        ,A.QUOTE_SALES_CHANNEL
        ,A.QUOTE_SBQQ__TYPE__C
        ,A.QUOTE_ORDER_NUMBER__C
        ,A.QUOTE_SBQQ__LINEITEMCOUNT__C

        ,A.OPPORTUNITYLINEITEM_OPPO_ID
        ,A.OPPORTUNITYLINEITEM_LINE_ITEM_ID
        ,A.OPPORTUNITYLINEITEM_LINE_LICENSE_TYPE
        ,A.OPPORTUNITYLINEITEM_LINE_ITEM_ACTION
        ,A.OPPORTUNITYLINEITEM_LINE_ITEM_TERM
        ,A.OPPORTUNITYLINEITEM_CURRENCY_ISO_CODE
        ,A.OPPORTUNITYLINEITEM_PRODUCT2ID
        ,A.OPPORTUNITYLINEITEM_PRODUCTCODE
        ,A.OPPORTUNITYLINEITEM_PRODUCTTYPE
        ,A.OPPORTUNITYLINEITEM_SEATS
        ,A.OPPORTUNITYLINEITEM_LINE_ITEM_ACV
        ,A.OPPORTUNITYLINEITEM_TOTALPRICE
        ,A.OPPORTUNITY_CONVERTED_LINEITEM_ACV
        ,A.OPPORTUNITYLINEITEM_CONVERTED_TOTAL_PRICE
        ,A.OPPORTUNITYLINEITEM_LASTMODIFIED_DATE

        ,A.QUOTE_LINE_ID
        ,A.QUOTE_LINE_NAME
        ,A.QLI_TERM
        ,A.QLI_TERM_DESCRIPTION
        ,A.QLI_LICENCE_TYPE
        ,A.QLI_PRODUCT_GROUP
        ,A.QUOTE_SBQQ__PRODUCTCODE__C
        ,A.QLI_NETAMOUNT
        ,A.QLI_NETAMOUNT_CONVERTED
        ,A.QLI_CONVERTED_ACV

        ,A.SFDC_ACCOUNT_CSN
        ,A.SFDC_ACCOUNT_NAME
        ,A.SFDC_ACCOUNT_SEGMENT
        ,A.SFDC_ACCOUNT_INDUSTRY_GROUP
        ,A.SFDC_ACCOUNT_TYPE
        ,A.SFDC_ACCOUNT_GEO
        ,A.SFDC_PARENT_ACCOUNT_CSN

        ,A.SFDC_PRODUCT_LINE
        ,A.SFDC_OFFERING_ID
        ,A.SFDC_CONTRACT_TERM_DESCRIPTION
        ,A.SFDC_PRODUCT_GROUP

        ,C.LEAD_ID as LEAD_GUID
        ,CASE
            WHEN C.CONVERTEDOPPORTUNITYID IS NOT NULL THEN 'Y'
            ELSE 'N'
         END AS LEADS_OPPORTUNITY_CONVERTED_FLAG
        ,FIN.SRC_ID AS FIN_SRC_ID
        ,FIN.PO_NBR AS FIN_PO_NBR
        ,FIN.BIC_ORDER_NBR AS FIN_BIC_ORDER_NBR
        ,FIN.COMBINED_SUBSCRIPTION_ID AS FIN_COMBINED_SUBSCRIPTION_ID
        ,FIN.OXYGEN_ID AS FIN_OXYGEN_ID
        ,FIN.ENRICHED_OXYGEN_ID AS FIN_ENRICHED_OXYGEN_ID
        ,FIN.CC_FBM_TOTAL_ACV_NET3_CC AS FIN_STORE_ACV
        ,FIN.CORPORATE_NAMED_ACCOUNT_GROUP_NM AS FIN_CORPORATE_NAMED_ACCOUNT_GROUP_NM
        ,FIN.CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM AS FIN_CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM
        --FIN.RECORD_TYPE as FIN_RECORD_TYPE,
        ,NULLIF(FIN.SAP_PRODUCT_LINE, '*') AS FIN_SAP_PRODUCT_LINE
        ,NULLIF(FIN.CC_FBD_SF_BIL_TERM_SETL, 'N/A') AS FIN_SUBSCRIPTION_TERM
        -- INVOICE_DOC_TYPE_DESC AS PURCHASE_TYPE,
        ,FIN.BILLED_QUANTITY AS FIN_BILLED_QUANTITY
        ,FIN.RETURN_ORDER_FLG AS FIN_RETURN_ORDER_FLG
        ,FIN.CC_FBM_SF_SUBS_SEATS_BILLED AS FIN_STORE_SEATS_COUNT
        ,FIN.CC_BILLED_BGT_USD_FUT AS FIN_STORE_BILLINGS
        ,FIN.CC_FBM_TOTAL_ACV_NET3_CC_FUT as FIN_CC_FBM_TOTAL_ACV_NET3_CC_FUT
        ,FIN.CC_FBM_TOTAL_ACV_NET3_CC AS FIN_CC_FBM_TOTAL_ACV_NET3_CC
        ,FIN.ACS_NEW_ACV
        ,FIN.ACS_NET_NEW_ACV
        ,FIN.ACS_EXPANSION_ACV
        ,FIN.ACS_RENEW_ACV
        ,FIN.ACS_INSTALLMENT_ACV
        ,FIN.CC_FBD_BSM_SALES_CH as FIN_CC_FBD_BSM_SALES_CH
        ,FIN.TRANSACTION_DT as FIN_TRANSACTION_DT
        ,FIN.FY_AND_FQ_NAME AS FIN_FY_AND_FQ_NAME
        ,FIN.WEEK_NUMBER_FISCAL_QUARTER AS FIN_WEEK_NUMBER_FISCAL_QUARTER
        ,FIN.SETTLEMENT_START_DT AS FIN_SETTLEMENT_START_DT
        ,FIN.SETTLEMENT_END_DT AS FIN_SETTLEMENT_END_DT
        ,FIN.CONTRCT_START_DT AS FIN_CONTRCT_START_DT
        ,FIN.CONTRCT_END_DT AS FIN_CONTRCT_END_DT
        ,FIN.CC_FBD_SF_WWS_GEO as FIN_CC_FBD_SF_WWS_GEO
        ,FIN.CORPORATE_COUNTRY_NM AS FIN_CORPORATE_COUNTRY_NM
        ,FIN.CORPORATE_COUNTRY_CD AS FIN_CORPORATE_COUNTRY_CD
        ,FIN.CORPORATE_CSN AS FIN_CORPORATE_CSN
        ,FIN.CORPORATE_ACCOUNT_NM AS FIN_CORPORATE_ACCOUNT_NM
        ,NULLIF(FIN.CC_FBD_SF_FOX_RENEWAL_IND, 'N/A') AS FIN_CC_FBD_SF_FOX_RENEWAL_IND
        ,FIN.CC_FBD_BSM_ESTORE_ORDER_ORIGIN AS FIN_CC_FBD_BSM_ESTORE_ORDER_ORIGIN
        ,FIN.ORIGIN_SEGMENT AS FIN_ORIGIN_SEGMENT
        ,FIN.CORPORATE_HIER_INDUSTRY_SEGMENT_NM AS FIN_CORPORATE_HIER_INDUSTRY_SEGMENT_NM
        ,FIN.PRODUCT_CLASS AS FIN_PRODUCT_CLASS
        ,FIN.CORPORATE_PARENT_ACCOUNT_CSN AS FIN_CORPORATE_PARENT_ACCOUNT_CSN
        ,FIN.CORPORATE_PARENT_COUNTRY_CD AS FIN_CORPORATE_PARENT_COUNTRY_CD
        ,FIN.CORPORATE_PARENT_COUNTRY_NM  AS FIN_CORPORATE_PARENT_COUNTRY_NM
        ,FIN.CORPORATE_PARENT_GEO_CD AS FIN_CORPORATE_PARENT_GEO_CD
        ,FIN.ECC_SALES_ORDER_NBR AS FIN_ECC_SALES_ORDER_NBR

        ,FIN.PARENT_SURVIVOR_CORPORATE_CSN AS FIN_PARENT_SURVIVOR_CORPORATE_CSN
        ,FIN.PARENT_SURVIVING_PARENTACCOUNT_CSN AS FIN_PARENT_SURVIVING_PARENTACCOUNT_CSN
        ,FIN.FINAL_CSN AS FIN_FINAL_CSN

        ,FIN.PRODUCT AS FIN_PRODUCT
        ,FIN.PRODUCT_FAMILY AS FIN_PRODUCT_FAMILY
        ,FIN.PRODUCT_INDUSTRY AS FIN_PRODUCT_INDUSTRY

        ,FIN.GDPR_FLAG AS FIN_GDPR_FLAG -- Added GDPR Flag from Country Lookup
        ,FIN.ABSM_FLAG AS FIN_ABSM_FLAG
        ,FIN.PARENT_GEO AS FIN_PARENT_GEO
        ,FIN.ALLOCADIA_ID AS FIN_ALLOCADIA_ID
        ,FIN.CAMPAIGN_INDUSTRY AS FIN_CAMPAIGN_INDUSTRY
        ,FIN.ACV_SOURCE
        ,FIN.CHILD_CAMPAIGN_NAME AS FIN_CHILD_CAMPAIGN_NAME
        ,FIN.PARENT_CAMPAIGN_NAME AS FIN_PARENT_CAMPAIGN_NAME
        ,FIN.TACTIC_OWNER AS FIN_TACTIC_OWNER
        ,FIN.EVT_CHANNEL AS LAST_TOUCH_CHANNEL
        ,F.CUSTOMER_PARENT_CSN
        ,F.CUSTOMER_PHASE
        ,F.CUSTOMER_PHASE_START_DATE
        ,F.CUSTOMER_PHASE_END_DATE
        ,F.START_FISCAL_YEAR_QUARTER AS CUSTOMER_PHASE_START_FISCAL_YEAR_QUARTER

 FROM
    SFDC_QUOTE_OPPO_COMBINED A
    LEFT JOIN SFDC_LEAD C on C.CONVERTEDOPPORTUNITYID = A.OPPORTUNITY_ID
    ---MPM JOIN TO GET MARKETING CONTRIBUTION TYPE----
    LEFT JOIN  (
                SELECT
                    OPPORTUNITY_ID
                    ,SUM(CONV_ACV) CONV_ACV
                    ,MAX(MARKETING_CONTRIBUTION_TYPE) MARKETING_CONTRIBUTION_TYPE
                FROM PROD.MPM_REPORTING.FACT_MPM_INSIGHTS_BI
                WHERE FACT_TYPE = 'CONVERSION_MTA'
                GROUP BY OPPORTUNITY_ID
                ) MPM
            ON A.OPPORTUNITY_ID = MPM.OPPORTUNITY_ID
    FULL JOIN {{ ref('FFM_TOTAL_ACV_STAGE') }} FIN on FIN.QUOTE_NBR = A.QUOTE_NAME AND FIN.QUOTE_LINE_ITEM_ID = A.QUOTE_LINE_NAME
    FULL JOIN
    {{ ref('FFM_CUSTOMERS_STAGE') }} F
        ON COALESCE(F.SRC_ID,CUSTOMER_PARENT_CSN) = COALESCE(FIN.SRC_ID,A.SFDC_PARENT_ACCOUNT_CSN)
         {# on F.CUSTOMER_PARENT_CSN = COALESCE(FIN.FINAL_CSN, A.SFDC_PARENT_ACCOUNT_CSN)
        AND
            --FIN.TRANSACTION_DT BETWEEN F.CUSTOMER_PHASE_START_DATE AND F.CUSTOMER_PHASE_END_DATE
            FIN.SETTLEMENT_START_DT >= F.CUSTOMER_PHASE_START_DATE
            AND FIN.SETTLEMENT_START_DT <= F.CUSTOMER_PHASE_END_DATE
            --FIN.CONTRCT_START_DT BETWEEN F.CUSTOMER_PHASE_START_DATE AND F.CUSTOMER_PHASE_END_DATE #}

    -- or f.parent_csn=bb.PARENT_ACCOUNT_CSN__C
    -- or f.parent_csn = bb.ACCOUNT_CSN__C
