-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: middle_funnel
-- MODEL  : ffm_trials_dl_act_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Set the right tag
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the configuration #}
{{
    config(
        materialized='table'
    )
}}

{# Set the post pipeline configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON VIEW {{ this }} TO ROLE BSM_QA"
    ]
  )
}}



WITH TRIALS AS (
    SELECT
        DISTINCT SUB_ID_DOWNLOAD,
        SUB_ID_ACTIVATION,
        ACTIVATION_OXYGEN_ID,
        TRAIL_DOWNLOAD_OXYGEN_ID,
        IS_VALID_ACTIVATION,
        IS_VALID_DOWNLOAD,
        TRIAL_GEO,
        TRIAL_GDPR_FLAG,
        TRIAL_NAMED_ACCOUNT_GROUP AS BUSINESS_TIER,
        TRIAL_COUNTRY,
        ACTIVATION_DATE,
        ENTITLEMENT_START_DATE,
        TRIAL_PRODUCT,
        TRIAL_PRODUCT_FAMILY,
        TRIAL_PRODUCT_INDUSTRY
    FROM
        {{ ref('FFM_MID_FUNNEL')}} TL
    WHERE
        TRAIL_DOWNLOAD_OXYGEN_ID IS NOT NULL
),
CALENDAR_WINDOW AS (
    SELECT
        DATE_KEY,
        WEEK_NUMBER_FISCAL_QUARTER,
        MONTH_START_DATE,
        PREVIOUS_MONTH_START_DATE,
        FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_QUARTER,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA,
        COMPLETED_WEEKS,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER
    FROM
        {{ ref('FFM_FIN_CALENDAR') }}
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6
),
TRIALS_DOWNLOAD_RAW AS (
    SELECT
        DISTINCT TL.SUB_ID_DOWNLOAD,
        TL.SUB_ID_ACTIVATION,
        TL.ACTIVATION_OXYGEN_ID,
        TL.TRAIL_DOWNLOAD_OXYGEN_ID,
        TL.IS_VALID_ACTIVATION,
        TL.IS_VALID_DOWNLOAD,
        TL.TRIAL_GEO,
        TL.TRIAL_GDPR_FLAG,
        TL.BUSINESS_TIER,
        TL.TRIAL_COUNTRY,
        TL.ACTIVATION_DATE,
        TL.TRIAL_PRODUCT,
        TL.TRIAL_PRODUCT_FAMILY,
        TL.TRIAL_PRODUCT_INDUSTRY,
        FIN_DL_CAL.WEEK_NUMBER_FISCAL_QUARTER AS WEEK_NUMBER_FISCAL_QUARTER,
        FIN_DL_CAL.MONTH_START_DATE AS MONTH_START_DATE,
        FIN_DL_CAL.PREVIOUS_MONTH_START_DATE AS PREVIOUS_MONTH_START_DATE,
        FIN_DL_CAL.FISCAL_QUARTER_BEGIN_DATE AS FISCAL_QUARTER_BEGIN_DATE,
        FIN_DL_CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        FIN_DL_CAL.PREVIOUS_FISCAL_QUARTER_BEGIN_DATE AS PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        FIN_DL_CAL.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        FIN_DL_CAL.PREVIOUS_FISCAL_YEAR_QUARTER AS PREVIOUS_FISCAL_YEAR_QUARTER,
        FIN_DL_CAL.PREVIOUS_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_QUARTER_NAME,
        FIN_DL_CAL.IS_CURRENT_QUARTER AS IS_CURRENT_QUARTER,
        FIN_DL_CAL.IS_RESTRICTED_DATA AS IS_RESTRICTED_DATA,
        FIN_DL_CAL.COMPLETED_WEEKS AS COMPLETED_WEEKS,
        FIN_DL_CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER AS FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
    FROM
        TRIALS TL
        JOIN CALENDAR_WINDOW FIN_DL_CAL ON TL.ENTITLEMENT_START_DATE = FIN_DL_CAL.DATE_KEY
),
TRIALS_ACTIVATION_RAW AS (
    SELECT
        DISTINCT TL.SUB_ID_DOWNLOAD,
        TL.SUB_ID_ACTIVATION,
        TL.ACTIVATION_OXYGEN_ID,
        TL.TRAIL_DOWNLOAD_OXYGEN_ID,
        TL.IS_VALID_ACTIVATION,
        TL.IS_VALID_DOWNLOAD,
        TL.TRIAL_GEO,
        TL.TRIAL_GDPR_FLAG,
        TL.BUSINESS_TIER,
        TL.TRIAL_COUNTRY,
        TL.ACTIVATION_DATE,
        TL.TRIAL_PRODUCT,
        TL.TRIAL_PRODUCT_FAMILY,
        TL.TRIAL_PRODUCT_INDUSTRY,
        FIN_ACT_CAL.WEEK_NUMBER_FISCAL_QUARTER AS WEEK_NUMBER_FISCAL_QUARTER,
        FIN_ACT_CAL.MONTH_START_DATE AS MONTH_START_DATE,
        FIN_ACT_CAL.PREVIOUS_MONTH_START_DATE AS PREVIOUS_MONTH_START_DATE,
        FIN_ACT_CAL.FISCAL_QUARTER_BEGIN_DATE AS FISCAL_QUARTER_BEGIN_DATE,
        FIN_ACT_CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        FIN_ACT_CAL.PREVIOUS_FISCAL_QUARTER_BEGIN_DATE AS PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        FIN_ACT_CAL.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        FIN_ACT_CAL.PREVIOUS_FISCAL_YEAR_QUARTER AS PREVIOUS_FISCAL_YEAR_QUARTER,
        FIN_ACT_CAL.PREVIOUS_FISCAL_QUARTER_NAME AS PREVIOUS_FISCAL_QUARTER_NAME,
        FIN_ACT_CAL.IS_CURRENT_QUARTER AS IS_CURRENT_QUARTER,
        FIN_ACT_CAL.IS_RESTRICTED_DATA AS IS_RESTRICTED_DATA,
        FIN_ACT_CAL.COMPLETED_WEEKS AS COMPLETED_WEEKS,
        FIN_ACT_CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER AS FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER
    FROM
        TRIALS TL
        JOIN CALENDAR_WINDOW FIN_ACT_CAL ON TL.ACTIVATION_DATE = FIN_ACT_CAL.DATE_KEY
),
UNION_ALL AS (
    SELECT
        DISTINCT SUB_ID_DOWNLOAD,
        SUB_ID_ACTIVATION,
        IS_VALID_ACTIVATION,
        IS_VALID_DOWNLOAD,
        TRIAL_GEO AS GEO,
        TRIAL_COUNTRY AS COUNTRY,
        TRIAL_GDPR_FLAG AS GDPR_FLAG,
        BUSINESS_TIER,
        TRIAL_PRODUCT AS PRODUCT,
        TRIAL_PRODUCT_FAMILY AS PRODUCT_FAMILY,
        TRIAL_PRODUCT_INDUSTRY AS PRODUCT_INDUSTRY,
        WEEK_NUMBER_FISCAL_QUARTER,
        MONTH_START_DATE,
        PREVIOUS_MONTH_START_DATE,
        FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_QUARTER,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA,
        COMPLETED_WEEKS,
        'TRIAL_DOWNLOAD' as METRIC_FLAG
    FROM
        TRIALS_DOWNLOAD_RAW
    UNION ALL
    SELECT
        DISTINCT SUB_ID_DOWNLOAD,
        SUB_ID_ACTIVATION,
        IS_VALID_ACTIVATION,
        IS_VALID_DOWNLOAD,
        TRIAL_GEO AS GEO,
        TRIAL_COUNTRY AS COUNTRY,
        TRIAL_GDPR_FLAG AS GDPR_FLAG,
        BUSINESS_TIER,
        TRIAL_PRODUCT AS PRODUCT,
        TRIAL_PRODUCT_FAMILY AS PRODUCT_FAMILY,
        TRIAL_PRODUCT_INDUSTRY AS PRODUCT_INDUSTRY,
        WEEK_NUMBER_FISCAL_QUARTER,
        MONTH_START_DATE,
        PREVIOUS_MONTH_START_DATE,
        FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_QUARTER,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA,
        COMPLETED_WEEKS,
        'TRIAL_ACTIVATION' as METRIC_FLAG
    FROM
        TRIALS_ACTIVATION_RAW
),
BASE AS (
    SELECT
        DISTINCT GEO,
        COUNTRY,
        GDPR_FLAG,
        BUSINESS_TIER,
        PRODUCT,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        MONTH_START_DATE,
        COUNT(
            DISTINCT CASE
                WHEN IS_VALID_DOWNLOAD = TRUE
                AND METRIC_FLAG = 'TRIAL_DOWNLOAD' THEN SUB_ID_DOWNLOAD
                ELSE NULL
            END
        ) AS TRIALS_DOWNLOAD,
        COUNT(
            DISTINCT CASE
                WHEN IS_VALID_DOWNLOAD = TRUE
                AND IS_VALID_ACTIVATION = TRUE
                AND METRIC_FLAG = 'TRIAL_ACTIVATION' THEN SUB_ID_ACTIVATION
                ELSE NULL
            END
        ) AS TRIALS_ACTIVATIONS
    FROM
        UNION_ALL
    GROUP BY
        ALL
),
PQTD_PYQTD AS (
    SELECT
        DISTINCT GEO,
        COUNTRY,
        GDPR_FLAG,
        BUSINESS_TIER,
        PRODUCT,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        MONTH_START_DATE,
        COUNT(
            DISTINCT CASE
                WHEN IS_VALID_DOWNLOAD = TRUE
                AND METRIC_FLAG = 'TRIAL_DOWNLOAD' THEN SUB_ID_DOWNLOAD
                ELSE NULL
            END
        ) AS TRIALS_DOWNLOAD,
        COUNT(
            DISTINCT CASE
                WHEN IS_VALID_DOWNLOAD = TRUE
                AND IS_VALID_ACTIVATION = TRUE
                AND METRIC_FLAG = 'TRIAL_ACTIVATION' THEN SUB_ID_ACTIVATION
                ELSE NULL
            END
        ) AS TRIALS_ACTIVATIONS
    FROM
        UNION_ALL
    WHERE
        FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER IN (-1, -4)
        AND WEEK_NUMBER_FISCAL_QUARTER <=(
            SELECT
                MAX(WEEK_NUMBER_FISCAL_QUARTER)
            FROM
                UNION_ALL
            WHERE
                FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = 0
        )
    GROUP BY
        ALL
),
DIMENSIONS AS (
    SELECT
        DISTINCT GEO,
        COUNTRY,
        GDPR_FLAG,
        BUSINESS_TIER,
        PRODUCT,
        PRODUCT_FAMILY,
        PRODUCT_INDUSTRY
    FROM
        BASE
),
DIM_CAL AS (
    SELECT
        DISTINCT MONTH_START_DATE,
        PREVIOUS_MONTH_START_DATE,
        FISCAL_QUARTER_BEGIN_DATE,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        PREVIOUS_FISCAL_YEAR_QUARTER,
        PREVIOUS_FISCAL_QUARTER_NAME,
        IS_CURRENT_QUARTER,
        IS_RESTRICTED_DATA,
        COMPLETED_WEEKS
    FROM
        CALENDAR_WINDOW
),
DIM_COMBINATIONS_QTRS AS (
    SELECT
        DISTINCT CAL.*,
        DIM.*
    FROM
        DIM_CAL CAL
        CROSS JOIN DIMENSIONS DIM
),
FINAL AS (
    SELECT
        'MIDDLE' AS FUNNEL,
        'TRIALS' AS METRIC_GROUP,
        DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.FISCAL_QUARTER_BEGIN_DATE,
        DIM.MONTH_START_DATE,
        DIM.PREVIOUS_MONTH_START_DATE,
        DIM.PREVIOUS_FISCAL_QUARTER_BEGIN_DATE,
        DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        DIM.PREVIOUS_FISCAL_YEAR_QUARTER,
        DIM.PREVIOUS_FISCAL_QUARTER_NAME,
        DIM.IS_CURRENT_QUARTER,
        DIM.IS_RESTRICTED_DATA,
        DIM.COMPLETED_WEEKS,
        DIM.GEO,
        DIM.COUNTRY,
        DIM.GDPR_FLAG,
        DIM.BUSINESS_TIER,
        DIM.PRODUCT,
        DIM.PRODUCT_FAMILY,
        DIM.PRODUCT_INDUSTRY,
        BASE.TRIALS_DOWNLOAD AS TRIALS_DOWNLOAD,
        BASE.TRIALS_ACTIVATIONS AS TRIALS_ACTIVATIONS,
        PQ.TRIALS_DOWNLOAD AS PQTD_TRIALS_DOWNLOAD,
        PQ.TRIALS_ACTIVATIONS AS PQTD_TRIALS_ACTIVATIONS,
        PYQ.TRIALS_DOWNLOAD AS PYQTD_TRIALS_DOWNLOAD,
        PYQ.TRIALS_ACTIVATIONS AS PYQTD_TRIALS_ACTIVATIONS
    FROM
        DIM_COMBINATIONS_QTRS DIM
        LEFT JOIN BASE ON BASE.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND BASE.MONTH_START_DATE = DIM.MONTH_START_DATE
        AND COALESCE(BASE.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(BASE.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(BASE.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(BASE.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(BASE.PRODUCT, '') = COALESCE(DIM.PRODUCT, '')
        AND COALESCE(BASE.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(BASE.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        LEFT JOIN PQTD_PYQTD PQ ON PQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.PREVIOUS_FISCAL_QUARTER_NAME
        AND PQ.MONTH_START_DATE = DATEADD(MONTH, -3, DIM.MONTH_START_DATE)
        AND COALESCE(PQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PQ.PRODUCT, '') = COALESCE(DIM.PRODUCT, '')
        AND COALESCE(PQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND PQ.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = -1
        LEFT JOIN PQTD_PYQTD PYQ ON PYQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = DIM.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND PYQ.MONTH_START_DATE = DATEADD(MONTH, -12, DIM.MONTH_START_DATE)
        AND COALESCE(PYQ.BUSINESS_TIER, '') = COALESCE(DIM.BUSINESS_TIER, '')
        AND COALESCE(PYQ.COUNTRY, '') = COALESCE(DIM.COUNTRY, '')
        AND COALESCE(PYQ.GEO, '') = COALESCE(DIM.GEO, '')
        AND COALESCE(PYQ.GDPR_FLAG, '') = COALESCE(DIM.GDPR_FLAG, '')
        AND COALESCE(PYQ.PRODUCT, '') = COALESCE(DIM.PRODUCT, '')
        AND COALESCE(PYQ.PRODUCT_FAMILY, '') = COALESCE(DIM.PRODUCT_FAMILY, '')
        AND COALESCE(PYQ.PRODUCT_INDUSTRY, '') = COALESCE(DIM.PRODUCT_INDUSTRY, '')
        AND PYQ.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = -4
)

SELECT
    *
FROM
    FINAL
WHERE
    NOT (
        TRIALS_DOWNLOAD = 0
        AND PQTD_TRIALS_DOWNLOAD = 0
        AND PYQTD_TRIALS_DOWNLOAD = 0
        AND TRIALS_ACTIVATIONS = 0
        AND PQTD_TRIALS_ACTIVATIONS
        AND PYQTD_TRIALS_ACTIVATIONS = 0
    )