-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : ffm_store_new_orders_monthly_agg
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the configuration #}
{{
    config(
        materialized='table'
    )
}}

{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST"
    ]
  )
}}

WITH FIN_RAW AS (
    SELECT DISTINCT
        FIN.FIN_SRC_ID,
        FIN.FIN_ECC_SALES_ORDER_NBR,
        CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        CAL.WEEK_NUMBER_FISCAL_QUARTER AS FYWEEK,
        CAL.PREVIOUS_FISCAL_QUARTER_NAME,
        CAL.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
        CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER,
        CAL.IS_RESTRICTED_DATA,
        CAL.IS_CURRENT_QUARTER,
        FIN.FIN_CAMPAIGN_INDUSTRY AS CAMPAIGN_INDUSTRY,
        FIN.FIN_CORPORATE_NAMED_ACCOUNT_GROUP_NM AS BUSINESS_TIER,
        NULLIF(UPPER(FIN.FIN_CC_FBD_SF_WWS_GEO), 'CORP') AS GEO,
        FIN.FIN_CORPORATE_COUNTRY_NM AS COUNTRY,
        FIN.FIN_GDPR_FLAG AS GDPR_FLAG,
        FIN.FIN_PRODUCT_FAMILY AS PRODUCT_FAMILY,
        FIN.FIN_PRODUCT_INDUSTRY AS PRODUCT_INDUSTRY,
        FIN.FIN_ORIGIN_SEGMENT AS ORIGIN_SEGMENT,
        FIN.FIN_CC_FBM_TOTAL_ACV_NET3_CC
    FROM
        {{ ref('FFM_LOWER_FUNNEL') }} FIN
    JOIN {{ ref('FFM_FIN_CALENDAR') }} CAL 
        ON FIN.FIN_TRANSACTION_DT = CAL.DATE_KEY
    WHERE CAL.FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER >= -6 --Limits from last 6 completed quarters till last completed week of current quarter
        AND FIN.FIN_CC_FBD_BSM_SALES_CH = 'eStore'
        AND (
            (FIN.ACV_SOURCE = 'Finmart Integrated' AND UPPER(FIN.FIN_CC_FBD_SF_FOX_RENEWAL_IND) = 'NEW') -- Fetch only Store New Orders from Finmart Integrated
            OR 
            (FIN.ACV_SOURCE ilike 'acs core%' AND (COALESCE(FIN.ACS_NEW_ACV,0) + COALESCE(FIN.ACS_EXPANSION_ACV, 0)) <> 0) -- Fetch only Store New Orders from ACS Core
        )
),
-- Get last completed week of latest quarter
LAST_COMPLETED_WEEK AS (
    SELECT
        MAX(FYWEEK) AS LAST_WEEK
    FROM FIN_RAW
    WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER = 0
),
BASE_AGGREGATED AS (
    SELECT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, COUNTRY, CAMPAIGN_INDUSTRY, BUSINESS_TIER, ORIGIN_SEGMENT, PRODUCT_FAMILY, PRODUCT_INDUSTRY, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        COUNT(DISTINCT FIN_ECC_SALES_ORDER_NBR) AS STORE_NEW_ORDER_COUNT,
        CONCAT(
            'QTR-GEO',
            IFF(GROUPING(COUNTRY) = 0, '-CNTRY', ''),
            IFF(GROUPING(CAMPAIGN_INDUSTRY) = 0, '-C_IND', ''),
            IFF(GROUPING(BUSINESS_TIER) = 0, '-B_TIER', ''),
            IFF(GROUPING(ORIGIN_SEGMENT) = 0, '-ORIGIN_SEG', ''),
            IFF(GROUPING(PRODUCT_FAMILY) = 0, '-PROD_FAM', ''),
            IFF(GROUPING(PRODUCT_INDUSTRY) = 0, '-PROD_IND', '')
        ) AS AGGREGATED_BY
    FROM
        FIN_RAW
    GROUP BY
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, IS_RESTRICTED_DATA, IS_CURRENT_QUARTER,
        CUBE (COUNTRY, CAMPAIGN_INDUSTRY, BUSINESS_TIER, ORIGIN_SEGMENT, PRODUCT_FAMILY, PRODUCT_INDUSTRY)
),
QTD_AGGREGATED AS (
    SELECT
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, COUNTRY, CAMPAIGN_INDUSTRY, BUSINESS_TIER, ORIGIN_SEGMENT, PRODUCT_FAMILY, PRODUCT_INDUSTRY, IS_RESTRICTED_DATA,
        COUNT(DISTINCT FIN_ECC_SALES_ORDER_NBR) AS STORE_NEW_ORDER_COUNT,
        CONCAT(
            'QTR-GEO',
            IFF(GROUPING(COUNTRY) = 0, '-CNTRY', ''),
            IFF(GROUPING(CAMPAIGN_INDUSTRY) = 0, '-C_IND', ''),
            IFF(GROUPING(BUSINESS_TIER) = 0, '-B_TIER', ''),
            IFF(GROUPING(ORIGIN_SEGMENT) = 0, '-ORIGIN_SEG', ''),
            IFF(GROUPING(PRODUCT_FAMILY) = 0, '-PROD_FAM', ''),
            IFF(GROUPING(PRODUCT_INDUSTRY) = 0, '-PROD_IND', '')
        ) AS AGGREGATED_BY
    FROM
        FIN_RAW
    WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER IN (0, -1, -4) -- Fetch current, previous & previous year quarter
        AND FYWEEK <= (SELECT LAST_WEEK FROM LAST_COMPLETED_WEEK)
    GROUP BY
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_QUARTER_NAME, PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME, GEO, IS_RESTRICTED_DATA,
        CUBE (COUNTRY, CAMPAIGN_INDUSTRY, BUSINESS_TIER, ORIGIN_SEGMENT, PRODUCT_FAMILY, PRODUCT_INDUSTRY)
)

SELECT
    'LOWER' AS FUNNEL,
    'STORE_ORDERS' AS METRIC_GROUP,
    A.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
    A.PREVIOUS_FISCAL_QUARTER_NAME,
    A.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME,
    A.GEO,
    A.COUNTRY,
    A.CAMPAIGN_INDUSTRY,
    A.BUSINESS_TIER,
    A.ORIGIN_SEGMENT,
    A.PRODUCT_FAMILY,
    A.PRODUCT_INDUSTRY,
    A.IS_RESTRICTED_DATA,
    A.STORE_NEW_ORDER_COUNT,
    A.IS_CURRENT_QUARTER,
    CASE
        WHEN A.IS_CURRENT_QUARTER = 1 THEN QTD.STORE_NEW_ORDER_COUNT
        ELSE PQ.STORE_NEW_ORDER_COUNT
    END AS QOQ_STORE_NEW_ORDER_COUNT,
    CASE
        WHEN A.IS_CURRENT_QUARTER = 1 THEN PQTD.STORE_NEW_ORDER_COUNT
        ELSE PY.STORE_NEW_ORDER_COUNT
    END AS YOY_STORE_NEW_ORDER_COUNT,
    A.AGGREGATED_BY AS ORDERS_AGGREGATED_BY,
    CURRENT_TIMESTAMP AS RUN_TIMESTAMP
FROM BASE_AGGREGATED A
    LEFT JOIN BASE_AGGREGATED PQ --Join with previous quarter to get QoQ
        ON A.PREVIOUS_FISCAL_QUARTER_NAME = PQ.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = PQ.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(PQ.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(PQ.COUNTRY, '')
        AND COALESCE(A.CAMPAIGN_INDUSTRY, '') = COALESCE(PQ.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(PQ.BUSINESS_TIER, '')
        AND COALESCE(A.ORIGIN_SEGMENT, '') = COALESCE(PQ.ORIGIN_SEGMENT, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(PQ.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(PQ.PRODUCT_INDUSTRY, '')
    LEFT JOIN BASE_AGGREGATED PY --Join with previous year quarter to get YoY
        ON A.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = PY.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = PY.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(PY.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(PY.COUNTRY, '')
        AND COALESCE(A.CAMPAIGN_INDUSTRY, '') = COALESCE(PY.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(PY.BUSINESS_TIER, '')
        AND COALESCE(A.ORIGIN_SEGMENT, '') = COALESCE(PY.ORIGIN_SEGMENT, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(PY.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(PY.PRODUCT_INDUSTRY, '')
    LEFT JOIN QTD_AGGREGATED QTD --Join with previous quarter to get QTD
        ON A.PREVIOUS_FISCAL_QUARTER_NAME = QTD.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = QTD.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(QTD.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(QTD.COUNTRY, '')
        AND COALESCE(A.CAMPAIGN_INDUSTRY, '') = COALESCE(QTD.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(QTD.BUSINESS_TIER, '')
        AND COALESCE(A.ORIGIN_SEGMENT, '') = COALESCE(QTD.ORIGIN_SEGMENT, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(QTD.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(QTD.PRODUCT_INDUSTRY, '')
    LEFT JOIN QTD_AGGREGATED PQTD --Join with previous year quarter to get PQTD
        ON A.PREVIOUS_FISCAL_YEAR_AND_FISCAL_QUARTER_NAME = PQTD.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        AND A.AGGREGATED_BY = PQTD.AGGREGATED_BY
        AND COALESCE(A.GEO, '') = COALESCE(PQTD.GEO, '')
        AND COALESCE(A.COUNTRY, '') = COALESCE(PQTD.COUNTRY, '')
        AND COALESCE(A.CAMPAIGN_INDUSTRY, '') = COALESCE(PQTD.CAMPAIGN_INDUSTRY, '')
        AND COALESCE(A.BUSINESS_TIER, '') = COALESCE(PQTD.BUSINESS_TIER, '')
        AND COALESCE(A.ORIGIN_SEGMENT, '') = COALESCE(PQTD.ORIGIN_SEGMENT, '')
        AND COALESCE(A.PRODUCT_FAMILY, '') = COALESCE(PQTD.PRODUCT_FAMILY, '')
        AND COALESCE(A.PRODUCT_INDUSTRY, '') = COALESCE(PQTD.PRODUCT_INDUSTRY, '')