-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: connected_marketing_funnel
-- MODEL  : ffm_marketing
-- =============================================================================
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

-- Set the start and end dates 
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT CALENDAR_DATE FROM ADP_PUBLISH.COMMON_REFERENCE_DATA_OPTIMIZED.DATE_TIME_HIERARCHY WHERE FISCAL_QUARTER_VS_CURRENT_NUMBER=-12 AND  FISCAL_QUARTER_DAY_NUMBER=1);" ,
        "SET END_DATE   = (SELECT CURRENT_DATE()-1);"
    ]
  )
}}


-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

with
PRODUCT_CD AS (
    SELECT
        TRIM(NULLIF(PRODUCT, 'N/A')) AS PRODUCT,
        TRIM(PRODUCT_CODE) AS PRODUCT_CODE,
        TRIM(NULLIF(SOLUTION_DIVISION, 'N/A')) AS PRODUCT_INDUSTRY,
        TRIM(NULLIF(PRODUCT_GROUPING, 'N/A')) AS PRODUCT_FAMILY,
        ROW_NUMBER() OVER(
            PARTITION BY PRODUCT_CODE
            ORDER BY
                UPDATED_DATE DESC NULLS LAST
        ) AS RN
    FROM
        {{ var('LOOKUPS.MPM_PRODUCT_LOOKUP') }}
    QUALIFY RN = 1
),
PRODUCT_NM AS (
    SELECT
        TRIM(NULLIF(PRODUCT, 'N/A')) AS PRODUCT,
        TRIM(NULLIF(SOLUTION_DIVISION, 'N/A')) AS PRODUCT_INDUSTRY,
        TRIM(NULLIF(PRODUCT_GROUPING, 'N/A')) AS PRODUCT_FAMILY,
        ROW_NUMBER() OVER(
            PARTITION BY PRODUCT
            ORDER BY
                UPDATED_DATE DESC NULLS LAST
        ) AS RN
    FROM
       {{ var('LOOKUPS.MPM_PRODUCT_LOOKUP') }}
    QUALIFY RN = 1
)

select distinct

a.*
-- b.OPPORTUNITY_GUID,
-- b.OPPORTUNITY_ID,
-- b.ACCOUNT_CSN,
-- b.ACCOUNT_NAME,
,B.OPPORTUNITY_ID AS QUOTE_OPPORTUNITY_ID
,B.OPPORTUNITY_ACCOUNT_CSN
,B.QUOTE_ID
,B.QUOTE_LINE_ID
--b.QUOTE_LINE_ITEM_ID,
,B.QUOTE_SALES_CHANNEL
,B.QUOTE_STATUS
--b.QUOTE_OPPO_ID,
,B.QUOTE_SBQQ__TYPE__C
,B.QUOTE_ORDER_NUMBER__C
,B.QUOTE_SBQQ__LINEITEMCOUNT__C
,B.QUOTED_DATE
,B.QLI_LICENCE_TYPE
,B.QUOTE_SBQQ__PRODUCTCODE__C
-- b.LEAD_GUID,
-- b.LEAD_ID,

,B.FIN_SRC_ID
,B.FIN_PO_NBR
,B.FIN_BIC_ORDER_NBR
,B.FIN_ECC_SALES_ORDER_NBR
,B.FIN_COMBINED_SUBSCRIPTION_ID
,B.FIN_OXYGEN_ID
,B.FIN_ENRICHED_OXYGEN_ID
,B.FIN_STORE_ACV
,B.FIN_CORPORATE_NAMED_ACCOUNT_GROUP_NM
,B.FIN_CORPORATE_PARENT_NAMED_ACCOUNT_GROUP_NM
--b.FIN_RECORD_TYPE,
,B.FIN_SAP_PRODUCT_LINE
,B.FIN_PRODUCT_CLASS
,B.FIN_SUBSCRIPTION_TERM
,B.FIN_BILLED_QUANTITY
,B.FIN_RETURN_ORDER_FLG
,B.FIN_STORE_SEATS_COUNT,
b.FIN_STORE_BILLINGS,
b.FIN_CC_FBM_TOTAL_ACV_NET3_CC_FUT,
b.FIN_CC_FBM_TOTAL_ACV_NET3_CC,
b.FIN_CC_FBD_BSM_SALES_CH,
b.FIN_TRANSACTION_DT,
b.FIN_CC_FBD_SF_WWS_GEO,
b.FIN_CORPORATE_COUNTRY_NM,
b.FIN_CORPORATE_COUNTRY_CD,
b.FIN_CORPORATE_CSN,
b.FIN_CORPORATE_PARENT_ACCOUNT_CSN
,B.FIN_CORPORATE_PARENT_COUNTRY_CD
,B.FIN_CORPORATE_PARENT_GEO_CD
,B.FIN_CORPORATE_ACCOUNT_NM
,B.FIN_CC_FBD_SF_FOX_RENEWAL_IND
,B.FIN_CC_FBD_BSM_ESTORE_ORDER_ORIGIN
,B.FIN_ORIGIN_SEGMENT
,B.FIN_CORPORATE_HIER_INDUSTRY_SEGMENT_NM
,B.FIN_SETTLEMENT_START_DT
,B.FIN_SETTLEMENT_END_DT,
b.FIN_CONTRCT_START_DT,
b.FIN_CONTRCT_END_DT,
b.ACS_NEW_ACV,
b.ACS_NET_NEW_ACV,
b.ACS_EXPANSION_ACV,
b.ACS_RENEW_ACV,
b.ACS_INSTALLMENT_ACV,
b.ACV_SOURCE,

CUST.PARENT_CSN AS CUSTOMER_PHASE_PARENT_CSN,
CUST.CUSTOMER_PHASE,
CUST.CUSTOMER_PHASE_START_DATE,
CUST.CUSTOMER_PHASE_END_DATE,
CUST.START_FISCAL_YEAR_QUARTER AS CUSTOMER_PHASE_START_FISCAL_YEAR_QUARTER,
b.LEADS_OPPORTUNITY_CONVERTED_FLAG,

b.OPPO_CLOSEDATE,
-- b.ACCOUNTID,
b.OPPO_STAGENAME,
b.oppo_CONTRACT_TERM__C,
b.oppo_RENEWAL_STATUS__C,
b.OPPO_LASTMODIFIEDDATE,
b.OPPO_OPPORTUNITY_NUMBER__C,
b.OPPO_RENEWAL_TERM__C,
b.OPPO_OPPORTUNITY_CLASSIFICATION__C,
b.OPPO_END_DATE__C,
b.OPPO_TOTAL_SEAT_COUNT__C,
b.OPPO_CREATEDDATE,
b.OPPO_ISCLOSED,
b.OPPO_CONTRACTTYPE__C,
b.OPPO_AMOUNT,
b.OPPO_PO_NUMBER__C,
b.OPPO_CREATEDBYID,
b.OPPO_OPPORTUNITY_TYPE__C,
b.OPPO_OPPORTUNITY_AMOUNT__C,
b.OPPO_OWNERID,
b.OPPO_ADSK_OPPORTUNITY_STATUS__C,
b.OPPO_RENEWAL_TYPE__C,
b.OPPO_END_CUSTOMER_CSN__C,
b.OPPO_LEAD_ID__C,
b.OPPO_CAMPAIGNID,
b.OPPO_ACV__C,
b.OPPO_END_CUSTOMER_GEO__C,
b.OPPO_LASTMODIFIEDBYID,
b.OPPO_PRODUCT__C,
b.OPPO_LEADSOURCE,
b.OPPO_PRICEBOOK2ID,
b.OPPO_NAMED_ACCOUNT_GROUP__C,
b.OPPO_SALES_REGION__C,
b.OPPO_PARENT_INDUSTRY_SEGMENT__C,
b.OPPO_ACTUAL_CLOSE_DATE__C,
b.OPPO_REASON__C,
b.OPPO_OPPORTUNITY_AGE__C,
b.OPPO_PARTNER_ACCOUNT_CSN__C,
b.OPPO_PRIMARY_CONTACT_ID__C,
b.primary_contact__c,
b.OPPO_CONTACTID ,
b.OPPO_END_CUSTOMER_COUNTRY__C,
b.OPPO_APRIMO_ACTIVITY_ID__C,
b.OPPO_FULFILLMENT_CATEGORY__C,
b.OPP_APRIMO_ACTIVITY_NAME__C,
b.OPPO_FORECASTCATEGORY,
b.OPPORTUNITY_SELF_PROSPECTING_SOURCE__C,
B.OPPO_PARTNER_ACCOUNT__C,
B.OPPO_CURRENCYISOCODE,
b.RECORD_SOURCE,
b.OPPO_ACCOUNTID,
b.OPPORTUNITYLINEITEM_PRODUCTCODE,
b.OPPORTUNITYLINEITEM_LINE_ITEM_TERM,
b.OPPORTUNITYLINEITEM_SEATS,
b.OPPORTUNITYLINEITEM_TOTALPRICE,
b.OPPORTUNITYLINEITEM_CONVERTED_TOTAL_PRICE,
 CASE
            WHEN UPPER(a.lead_productinfo__c) = 'ARCHITECTURE ENGINEERING & CONSTRUCTION COLLECTION' THEN 'ARCHITECTURE ENGINEERING CONSTRUCTION COLLECTION'
            WHEN REGEXP_LIKE (a.lead_productinfo__c, '[0-9]{1}.*')
            AND LENGTH(a.lead_productinfo__c) > 25 THEN RIGHT(
                UPPER(a.lead_productinfo__c),
                (LEN(UPPER(a.lead_productinfo__c)) -18)
            )
            ELSE UPPER(a.lead_productinfo__c) end as LEAD_PRODUCTINFO_CLEANED,c.product_family as lead_product_family,
            d.product_family as lead_product_family_2,
            d.PRODUCT_INDUSTRY as LEAD_PRODUCT_INDUSTRY,

            e.product_family as oppo_product_family,
            e.PRODUCT_INDUSTRY as OPPO_PRODUCT_INDUSTRY,
            F.PRODUCT AS FIN_PRODUCT,
            F.product_family as FIN_PRODUCT_FAMILY
            ,F.PRODUCT_INDUSTRY as FIN_PRODUCT_INDUSTRY
            ,B.SFDC_ACCOUNT_NAME AS ACCOUNT_NAME
            ,B.OPPO_NAME
            ,B.OPPO_TABLE_LAST_REFRESH_DATE
            ,CURRENT_TIMESTAMP AS TABLE_REFRESH_TIMESTAMP
from {{ ref('FFM_MID_FUNNEL') }} a
full join {{ ref('FFM_LOWER_FUNNEL') }} b
on a.OPPORTUNITY_ID=b.OPPORTUNITY_ID
left join PRODUCT_CD c
on lower(LEAD_PRODUCTINFO_CLEANED)=lower(c.PRODUCT_CODE)
left join PRODUCT_NM D
on lower(LEAD_PRODUCTINFO_CLEANED)=lower(d.PRODUCT)
left join PRODUCT_NM E
on lower(OPPO_PRODUCT__C)=lower(E.PRODUCT)
left join PRODUCT_CD F
on lower(FIN_SAP_PRODUCT_LINE)=lower(F.PRODUCT_CODE)
FULL join EIO_PUBLISH.CUSTOMER_SHARED.CUSTOMER_PHASES CUST
    on CUST.parent_csn = COALESCE(b.FIN_CORPORATE_PARENT_ACCOUNT_CSN, B.SFDC_PARENT_ACCOUNT_CSN, a.PARENT_CSN)
    AND (
            b.FIN_TRANSACTION_DT BETWEEN CUST.CUSTOMER_PHASE_START_DATE AND CUST.CUSTOMER_PHASE_END_DATE
            OR b.FIN_SETTLEMENT_START_DT BETWEEN CUST.CUSTOMER_PHASE_START_DATE AND CUST.CUSTOMER_PHASE_END_DATE OR
            b.FIN_CONTRCT_START_DT BETWEEN CUST.CUSTOMER_PHASE_START_DATE AND CUST.CUSTOMER_PHASE_END_DATE
        )