-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: lower_funnel
-- MODEL  : ffm_sales_mpm_acv_stage
-- =============================================================================
{% set db_properties=get_dbproperties('fullfunnel') %}

{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Set the right tag
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT CALENDAR_DATE FROM ADP_PUBLISH.COMMON_REFERENCE_DATA_OPTIMIZED.DATE_TIME_HIERARCHY WHERE FISCAL_QUARTER_VS_CURRENT_NUMBER=-12 AND FISCAL_QUARTER_DAY_NUMBER=1); " ,
        "SET END_DATE   = (SELECT CURRENT_DATE()-1);"
    ]
  )
}}

-- Set the post pipeline configuration
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_QA"
    ]
  )
}}

WITH DATE_HIERARCHY AS (
    SELECT
        DISTINCT DATE_KEY,
        WEEK_NUMBER_FISCAL_QUARTER AS FYQUARTER_WEEK,
        MONTH_NUMBER_IN_FISCAL_YEAR AS FYMONTH,
        FISCAL_YEAR_AND_FISCAL_QUARTER_NAME AS FYQUARTER,
        FISCAL_YEAR_NAME AS FYYEAR
    FROM
        {{ ref('LOOKUP_FINANCE_CALENDAR') }}
),

CUSTOMER_PHASE AS(
    SELECT DISTINCT
         PARENT_CSN,
         CUSTOMER_PHASE,
         CUSTOMER_PHASE_END_DATE,
         CUSTOMER_PHASE_START_DATE
    FROM {{ var('CUSTOMER_PHASES') }}
    WHERE CUSTOMER_PHASE_END_DATE >= $START_DATE
),

ODM_MAPPING AS (
SELECT
            OPL.OPPORTUNITYID AS OPPORTUNITYID
            , CASE WHEN OFFERINGID__C IS NOT NULL THEN TRUE::BOOLEAN ELSE FALSE::BOOLEAN END AS HAS_ODM_FLAG
            FROM {{ var('OPPORTUNITYLINEITEM_SFDC_RAW') }} OPL
                LEFT JOIN BSD_PUBLISH.SFDC_SHARED.PRODUCT2 OPLP2
                    ON OPLP2.ID = OPL.PRODUCT2ID
                GROUP BY ALL
),
DEDUP_ODM_FLAG AS
(
    SELECT OPPORTUNITYID , MAX(HAS_ODM_FLAG) AS HAS_ODM_FLAG
    FROM ODM_MAPPING
    GROUP BY OPPORTUNITYID
),

RAW AS(
  SELECT
      OPPORTUNITY_ID,
      OPPORTUNITY_CREATED_DATE,
      OPPORTUNITY_CLOSE_DATE,
      CONVERSION_TYPE,
      FACT_TYPE,
      ACCOUNT_CSN,
      MKT_REPORTING_GEO AS GEO,
      REGION,
      COUNTRY AS COUNTRY,
      PLAN_CAMPAIGN_INDUSTRY AS MARKETING_INDUSTRY,
      PLAN_MARKETING_TACTIC_ORGANIZATION AS MARKETING_TACTIC_ORG,
      ACCOUNT_TIER,
      FOCUS_ACCOUNT AS TERRITORY_FOCUS_ACCOUNTS,
      PLAN_PARENT_CAMPAIGN_NAME AS PARENT_CAMPAIGN,
      PLAN_CHILD_CAMPAIGN_NAME AS CHILD_CAMPAIGN,
      PLAN_CAMPAIGN_PACKAGE AS PACKAGE,
      PLAN_TACTIC_OWNER AS TACTIC_OWNER,
      PLAN_TACTIC_NAME AS TACTIC_NAME,
      PLAN_LINE_ITEM_ID AS TACTIC_ID,
      SALES_MANAGER,
      SALES_REP,
      NULLIF(PRODUCT_INDUSTRY, 'N/A') AS PRODUCT_INDUSTRY,
      NULLIF(PRODUCT_FAMILY, 'N/A') AS PRODUCT_FAMILY,
      PLAN_AUDIENCES,
      PLAN_PROGRAM AS PROGRAM,
      MARKETING_CONTRIBUTION_TYPE,
      MARKETING_CONTRIBUTION_TYPE_HISTORIC,
      STAGENAME,
      CASE WHEN PLAN_CAMPAIGN_INDUSTRY in('ACS', 'Ad Hoc', 'AEX', 'B&I', 'Convergence', 'Cross-Ind','Forge', 'Genuine', 'Not Selected', 'Operational','OTH', 'Unknown', '(blank)') THEN  'Unallocated'
          WHEN PLAN_CAMPAIGN_INDUSTRY IS NULL then 'SPACE'
          ELSE PLAN_CAMPAIGN_INDUSTRY
      END AS PLAN_CAMPAIGN_INDUSTRY_ADJ,
      CASE WHEN PLAN_CHILD_CAMPAIGN_NAME is NULL or PLAN_CHILD_CAMPAIGN_NAME = '(blank)' then 'FILLER' ELSE PLAN_CHILD_CAMPAIGN_NAME END AS PLAN_CHILD_CAMPAIGN_NAME_ADJ,
      CASE WHEN PLAN_CAMPAIGN_PACKAGE is NULL or PLAN_CAMPAIGN_PACKAGE = '(blank)' then 'HOLDER' ELSE PLAN_CAMPAIGN_PACKAGE END AS PLAN_CAMPAIGN_PACKAGE_ADJ,
      CONCAT_WS('', PLAN_CAMPAIGN_INDUSTRY_ADJ, PLAN_CHILD_CAMPAIGN_NAME_ADJ, PLAN_CAMPAIGN_PACKAGE_ADJ) as CAMP_IND_CHILD_PACKAGE_KEY,

      CASE
          WHEN OPPORTUNITY_RECORDTYPE = 'tredence_analytics Opportunity' AND HAS_ODM_FLAG=FALSE THEN 'New'
          WHEN OPPORTUNITY_RECORDTYPE='tredence_analytics Internal Renewal' THEN 'Renew'
          ELSE OPPORTUNITY_TYPE
      END AS OPPORTUNITY_TYPE,
      CASE
          WHEN OPPORTUNITY_RECORDTYPE IN ('tredence_analytics Internal Renewal') THEN 'Direct'
          WHEN OPPORTUNITY_RECORDTYPE= 'tredence_analytics Opportunity' AND HAS_ODM_FLAG= FALSE THEN 'Direct'
          ELSE OPPORTUNITY_CHANNEL
      END AS OPPORTUNITY_CHANNEL,
      OPPORTUNITY_RECORDTYPE,
      CASE
          WHEN OPPORTUNITY_RECORDTYPE IN ('Subscription Opportunity') THEN TRUE
          WHEN OPPORTUNITY_RECORDTYPE IN ('tredence_analytics Opportunity') AND Q.SBQQ__OPPORTUNITY2__C IS NOT NULL THEN TRUE
          ELSE FALSE
      END AS IS_NBE,
      SUM(CONV_ACV) AS CONV_ACV

  FROM {{ var('FACT_MPM_INSIGHTS_VW') }} A
  LEFT JOIN (SELECT DISTINCT SBQQ__OPPORTUNITY2__C FROM {{ var('SBQQ_QUOTE_C') }}
              WHERE QUOTE_STATUS__C = 'ORDERED') Q ON A.OPPORTUNITY_ID = Q.SBQQ__OPPORTUNITY2__C
  LEFT JOIN DEDUP_ODM_FLAG ODM ON ODM.OPPORTUNITYID = A.OPPORTUNITY_ID
  WHERE INTERNAL_USE__C = 'FALSE'
  AND (
        OPPORTUNITY_CLOSE_DATE BETWEEN $START_DATE AND $END_DATE OR
        OPPORTUNITY_CREATED_DATE BETWEEN $START_DATE AND $END_DATE
      )
  AND FACT_TYPE = 'CONVERSION_MTA'
  GROUP BY ALL
),

OFFER AS (
  SELECT OPPORTUNITYID,
         ARRAY_AGG(OFFERING_CODE) WITHIN GROUP (ORDER BY OFFERING_CODE ASC) AS OFFER_TYPE_DETAIL
  FROM (
          SELECT DISTINCT OPPORTUNITYID, O.OFFERING_ID,O.OFFERING_CODE
          FROM {{ var('OPPORTUNITYLINEITEM_SFDC_RAW') }} A
          LEFT JOIN BSD_PUBLISH.SFDC_SHARED.PRODUCT2 B ON A.PRODUCT2ID = B.ID
          LEFT JOIN {{ var('EDH_OFFERING') }} O ON B.OFFERINGID__C = O.OFFERING_ID
  )
  GROUP BY 1

),

DIM_FUZZYSEARCH_COUNTRY AS
(
    SELECT DISTINCT COUNTRY, GDPR_FLAG
    FROM {{ ref('DIM_FFM_COUNTRY_VW') }}
)

SELECT
      A.OPPORTUNITY_ID,
      A.OPPORTUNITY_CREATED_DATE,
      A.OPPORTUNITY_CLOSE_DATE,
      A.CONVERSION_TYPE,
      A.FACT_TYPE,
      A.ACCOUNT_CSN,
      ACC.CORPORATE_PARENT_ACCOUNT_CSN AS PARENT_ACCOUNT_CSN__C,
      CP.CUSTOMER_PHASE,
      CP.CUSTOMER_PHASE_END_DATE,
      CP.CUSTOMER_PHASE_START_DATE,
      A.GEO,
      A.REGION,
      A.COUNTRY,
      A.MARKETING_INDUSTRY,
      A.MARKETING_TACTIC_ORG,
      A.ACCOUNT_TIER,
      A.TERRITORY_FOCUS_ACCOUNTS,
      A.PARENT_CAMPAIGN,
      A.CHILD_CAMPAIGN,
      A.PACKAGE,
      A.TACTIC_OWNER,
      A.TACTIC_NAME,
      A.TACTIC_ID,
      A.SALES_MANAGER,
      A.SALES_REP,
      A.PRODUCT_INDUSTRY,
      A.PRODUCT_FAMILY,
      CASE
        WHEN UPPER(A.PRODUCT_FAMILY) = 'INNOVYZE' OR UPPER(A.PRODUCT_FAMILY) LIKE 'FUSION%' THEN 'EMERGING_PRODUCT'
        WHEN UPPER(A.PRODUCT_INDUSTRY) <> 'ACS' AND UPPER(A.PRODUCT_FAMILY) <> 'INNOVYZE' AND UPPER(A.PRODUCT_FAMILY) NOT LIKE 'FUSION%' THEN 'CORE_PRODUCT'
        ELSE 'OTHERS'
      END AS PRODUCT_CATEGORIES,
      A.PLAN_AUDIENCES,
      A.PROGRAM,
      A.MARKETING_CONTRIBUTION_TYPE,
      A.MARKETING_CONTRIBUTION_TYPE_HISTORIC,
      A.STAGENAME,
      A.PLAN_CAMPAIGN_INDUSTRY_ADJ,
      A.PLAN_CHILD_CAMPAIGN_NAME_ADJ,
      A.PLAN_CAMPAIGN_PACKAGE_ADJ,
      A.CAMP_IND_CHILD_PACKAGE_KEY,
      A.OPPORTUNITY_TYPE,
      NULLIF(A.OPPORTUNITY_CHANNEL, '*') AS OPPORTUNITY_CHANNEL,
      A.OPPORTUNITY_RECORDTYPE,
      A.IS_NBE,
      CRE.FYYEAR AS FY_YEAR_CREATED,
      CRE.FYQUARTER AS FY_YEAR_QUARTER_CREATED,
      CRE.FYMONTH AS FY_MONTH_CREATED,
      CRE.FYQUARTER_WEEK AS FY_QUARTER_WEEK_CREATED,
      CLO.FYYEAR AS FY_YEAR_CLOSED,
      CLO.FYQUARTER AS FY_YEAR_QUARTER_CLOSED,
      CLO.FYMONTH AS FY_MONTH_CLOSED,
      CLO.FYQUARTER_WEEK AS FY_QUARTER_WEEK_CLOSED,
      A.CONV_ACV,
      B.AUDIENCE_OR_PROGRAM,
      B.FINAL_REPORTING_BUCKET,
      O.OFFER_TYPE_DETAIL,
      C.GDPR_FLAG

FROM RAW A
LEFT JOIN {{ var('FF_LOOKUP_CAMPAIGN_MAPPING') }} B ON A.CAMP_IND_CHILD_PACKAGE_KEY = B.CAMPAIGN_IND_CHILD_PACKAGE
LEFT JOIN OFFER O ON A.OPPORTUNITY_ID = O.OPPORTUNITYID
LEFT JOIN {{ var('ACCOUNTS_WITH_CORPORATE_PARENTS') }} ACC ON A.ACCOUNT_CSN = ACC.ACCOUNT_CSN
LEFT JOIN CUSTOMER_PHASE CP
    ON ACC.CORPORATE_PARENT_ACCOUNT_CSN = CP.PARENT_CSN AND (A.OPPORTUNITY_CLOSE_DATE BETWEEN CP.CUSTOMER_PHASE_START_DATE AND CP.CUSTOMER_PHASE_END_DATE )
LEFT JOIN DATE_HIERARCHY CRE ON A.OPPORTUNITY_CREATED_DATE = CRE.DATE_KEY
LEFT JOIN DATE_HIERARCHY CLO ON A.OPPORTUNITY_CLOSE_DATE = CLO.DATE_KEY
LEFT JOIN DIM_FUZZYSEARCH_COUNTRY C ON UPPER(A.COUNTRY) = UPPER(C.COUNTRY)
