-- =============================================================================
-- LAYER  : Gold — Business Fact
-- SUBFOLDER: upper_funnel
-- MODEL  : ffm_store_traffic_stage
-- =============================================================================
-- depends_on: {{ ref('FFM_FIN_CALENDAR') }}
-- Set the database properties.
{# Get the right stack database properties. #}
{% set db_properties=get_dbproperties('fullfunnel') %}

{# Set the database properties. #}
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

{# Set the right tag #}
{{ config(tags=[var('TAG_FULL_FUNNEL_METRICS')]) }}

{# Set the configuration #}
{{
    config(
        materialized='incremental',
        incremental_strategy='delete+insert',
        unique_key='DT',
        on_schema_change='append_new_columns',
        cluster_by=['DT']
    )
}}

{# Set the Pre Hook configuration #}
{{
  config(
    pre_hook = [
        "SET START_DATE = (SELECT MAX(DT) FROM {{ this }}); " ,
        "SET END_DATE   = (SELECT CURRENT_DATE()-1); ",
        """{% if is_incremental() %}
            DELETE FROM {{ this }} -- Deletes dates older than previous 12 quarters
            WHERE DT IN (SELECT DATE_KEY 
                            FROM {{ ref('FFM_FIN_CALENDAR') }} 
                        WHERE FISCAL_QUARTERS_FROM_CURRENT_FISCAL_QUARTER < -12)
        {% endif %}"""
    ]
  )
}}



{# Set the Post Hook configuration #}
{{
  config(
    post_hook = [
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_ANALYST_MI",
        "GRANT REFERENCES, SELECT ON TABLE {{ this }} TO ROLE BSM_MOT_ANALYST",
        "UPDATE {{ this }} T SET T.BUSINESS_TIER = S.NAMED_ACCOUNT_GROUP
         FROM (
            SELECT a.ACCOUNT_CSN, a.NAMED_ACCOUNT_GROUP
            FROM {{ ref('ACCOUNTS_WITH_CORPORATE_PARENTS') }} a
            INNER JOIN (SELECT DISTINCT ACCOUNT_CSN FROM {{ this }} WHERE BUSINESS_TIER IS NULL AND ACCOUNT_CSN IS NOT NULL) u 
            ON a.ACCOUNT_CSN = u.ACCOUNT_CSN
            WHERE a.NAMED_ACCOUNT_GROUP IS NOT NULL
            QUALIFY ROW_NUMBER() OVER (PARTITION BY a.ACCOUNT_CSN ORDER BY a.LAST_MODIFIED_DATE DESC NULLS LAST) = 1
        ) S
        WHERE T.ACCOUNT_CSN = S.ACCOUNT_CSN AND T.BUSINESS_TIER IS NULL"
    ]
  )
}}


WITH DATE_TIME_HIERARCHY AS
(
    SELECT DATE_KEY AS CALENDAR_DATE
      , WEEK_NUMBER_FISCAL_QUARTER
      , MONTH_NUMBER_IN_FISCAL_YEAR
      , FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
      , FISCAL_YEAR_NAME
    FROM {{ ref('LOOKUP_FINANCE_CALENDAR') }}
),
ACCOUNTS_CORE_DATASET AS (
    SELECT ACCOUNT_CSN, NAMED_ACCOUNT_GROUP AS BUSINESS_TIER
    FROM 
        {{ var('ACCOUNTS_WITH_CORPORATE_PARENTS') }}
    WHERE ACCOUNT_CSN IS NOT NULL
    QUALIFY ROW_NUMBER() OVER(PARTITION BY ACCOUNT_CSN ORDER BY LAST_MODIFIED_DATE DESC NULLS LAST) = 1
),
MCVISID_TO_ACCOUNT_CSN AS (
    SELECT MCVISID, ACCOUNT_CSN
    FROM {{ var('POLARIS_ID_LOOKUP_MCVISID_TO_ACCOUNT_CSN') }}
    QUALIFY ROW_NUMBER() OVER(PARTITION BY MCVISID ORDER BY UPDATE_TIMESTAMP DESC NULLS LAST) = 1
),

CAMPAIGN_DETAILS AS
(
    SELECT DISTINCT CAMPAIGN_ID
        , CAMPAIGN_NAME
        ,SPD_ALLOCADIA_ID
        ,KEY
    FROM {{ var('CAMPAIGN_TAXONOMY_MASTER') }}
    WHERE ACTIVE_TO IS NULL
),

CAMPAIGN_NAME_LATEST AS
(
    SELECT CAMPAIGN_ID
        ,CAMPAIGN_NAME
        ,ROW_NUMBER() OVER(PARTITION BY CAMPAIGN_ID ORDER BY ACTIVE_FROM DESC NULLS LAST) RN
    FROM {{ var('CAMPAIGN_TAXONOMY_MASTER') }}
    WHERE ACTIVE_TO IS NULL
    QUALIFY RN = 1
),
ALLOCADIA AS
(
    SELECT LINE_ITEM_ID,CAMPAIGN_INDUSTRY
    FROM {{ var('ALLOCADIA_LINEITEM_MASTER') }} ALLOC
    WHERE ALLOC.ACTIVE_TO_DATE IS NULL
),
USTACK_DATA AS
(
    SELECT
        TRIM(REGEXP_REPLACE(USTACK.CONV_PURCHASE_ID, '[^[:digit:]]', ' ')) AS CONV_PURCHASE_ID
        ,USTACK.EVT_ALLOCADIA_ID
        ,ALID.CAMPAIGN_INDUSTRY
        ,EVT_CAMPAIGN_ID || '_' || IFNULL(EVT_PLACEMENT_ID, '') || '_' || IFNULL(EVT_ADSET_ID, '') AS SPD_KEY
        ,MAX(MIN_EVT_TIMESTAMP_UTC) EVT_TIMESTAMP
    FROM {{ var('FA_USER_STACK') }} USTACK
    LEFT JOIN ALLOCADIA ALID
    ON CAST(EVT_ALLOCADIA_ID AS VARCHAR)= CAST(ALID.LINE_ITEM_ID AS VARCHAR)
    WHERE
        CONV_CONVERSION_TYPE = 'eStorePurchase'
        AND CONV_DATE BETWEEN $START_DATE AND $END_DATE
        AND CONV_PURCHASE_ID IS NOT NULL
        AND CAMPAIGN_INDUSTRY IS NOT NULL
    GROUP BY ALL
),
--Get the latest touchpoint with non-null campaign industry
CAMPAIGN_INDUSTRY_LATEST AS
(
    SELECT
        CONV_PURCHASE_ID
        ,EVT_ALLOCADIA_ID
        ,CAMPAIGN_INDUSTRY
        ,SPD_KEY
        ,ROW_NUMBER() OVER(PARTITION BY CONV_PURCHASE_ID ORDER BY EVT_TIMESTAMP DESC NULLS LAST) RN
    FROM USTACK_DATA
    QUALIFY RN=1
),
ALLOCADIA_ID_REMAPPING_FOR_INDUSTRY AS
(
    SELECT
        A.CONV_PURCHASE_ID
        ,TAXO.SPD_ALLOCADIA_ID
        ,COALESCE(ALID1.CAMPAIGN_INDUSTRY,A.CAMPAIGN_INDUSTRY) CAMPAIGN_INDUSTRY
    FROM CAMPAIGN_INDUSTRY_LATEST A --43429
    LEFT JOIN (SELECT KEY,SPD_ALLOCADIA_ID FROM CAMPAIGN_DETAILS )TAXO
        ON A.SPD_KEY=TAXO.KEY
    LEFT JOIN ALLOCADIA ALID1
        ON CAST(SPD_ALLOCADIA_ID AS VARCHAR)= CAST(ALID1.LINE_ITEM_ID AS VARCHAR)
    QUALIFY ROW_NUMBER() OVER(PARTITION BY A.CONV_PURCHASE_ID ORDER BY TAXO.SPD_ALLOCADIA_ID DESC NULLS LAST) = 1
),
CVC_FINMART AS
(
    SELECT DISTINCT IFF(BIC_ORDER_NBR = '*', PO_NBR, BIC_ORDER_NBR) AS PO_NBR
        , CC_FBD_SF_FOX_RENEWAL_IND AS SF_INDICATOR
        , LAST_UPDATED_DT
        ,CASE WHEN SAP_PRODUCT_LINE <> '*' THEN SAP_PRODUCT_LINE END SAP_PRODUCT_LINE
        ,CASE WHEN UPPER(CORPORATE_NAMED_ACCOUNT_GROUP_NM) NOT IN ('UNKNOWN','*') THEN CORPORATE_NAMED_ACCOUNT_GROUP_NM END BUSINESS_TIER
        , ROW_NUMBER() OVER (PARTITION BY IFF(BIC_ORDER_NBR = '*', PO_NBR, BIC_ORDER_NBR) ORDER BY  LAST_UPDATED_DT DESC) RK
	FROM {{ source('FINMART_PRIVATE', 'CVC_FINMART') }}
	WHERE UPPER(RECORD_TYPE) IN ('BILLING', 'BOOKING_BILLING')
	 AND TRANSACTION_DT BETWEEN $START_DATE AND $END_DATE
	QUALIFY RK=1
),

DIM_FUZZYSEARCH_COUNTRY AS
(
    SELECT DISTINCT GEO, REGION, COUNTRY, GDPR_FLAG, COUNTRY_SEARCH_CODE
    FROM {{ ref('DIM_FFM_COUNTRY_VW') }}
),


WEB_ANALYTICS_ADOBE_ENRICHED AS
(
    SELECT ENRICHED.DT
        , CAL.WEEK_NUMBER_FISCAL_QUARTER
        , CAL.MONTH_NUMBER_IN_FISCAL_YEAR
        , CAL.FISCAL_YEAR_AND_FISCAL_QUARTER_NAME
        , CAL.FISCAL_YEAR_NAME
        , COALESCE(GEO_COUNTRY_CODE, '') AS GEO_COUNTRY_CODE
        , COALESCE(C.COUNTRY, '') AS COUNTRY_NAME
        , COALESCE(C.GEO, '') AS GEO
        , COALESCE(C.REGION, '') AS REGION_NAME
        , COALESCE(C.GDPR_FLAG, 'NON-GDPR') AS GDPR_FLAG
        , COALESCE(PRODUCT_LINE_ID, '') AS PRODUCT_LINE_ID
        , COALESCE(VA_CLOSER_ID, '') AS LAST_TOUCH_CHANNEL
        , COALESCE(VA_FINDER_ID, '') AS FIRST_TOUCH_CHANNEL
        , COALESCE(PAGE_NAME, '') AS PAGE_NAME
        , COALESCE(SITE_NAME, '') AS SITE_NAME
        , COALESCE(ORDER_ID_PLATFORM, '') AS ORDER_ID_PLATFORM
        , COALESCE(ENRICHED.ORDER_ID, '') AS PURCHASE_ID
        , TRIM(REGEXP_REPLACE(ENRICHED.ORDER_ID, '[^[:digit:]]', ' ')) AS ORDER_ID_TRIMMED
        , COALESCE(MOE_QUOTE_ID, '') AS MOE_QUOTE_ID
        , COALESCE(FLOW_STEP_DETAIL, '') AS FLOW_STEP_DETAIL
        , COALESCE(ORIGIN_PARAMETER, '') AS ORIGIN_PARAMETER
        , COALESCE(ORDER_PRODUCT_REVENUE, '') AS ORDER_PRODUCT_REVENUE
        , TRY_TO_NUMBER(IS_ORDER) AS IS_ORDER
        , COALESCE(ORDER_ID_DETAILS, '') AS ORDER_ID_DETAILS
        , COALESCE(REFERRER, '') AS REFERRER
        , COALESCE(EXCLUDE_SEGMENT_IND, '') AS EXCLUDE_SEGMENT_IND
        , COALESCE(VISIT_ID, '') AS VISIT_ID
        , VISITOR_ID
        , COALESCE(CUSTOMER_HIT_DATE_TIME_PST, '') AS CUSTOMER_HIT_DATE_TIME_PST
        , COALESCE(TACTIC_ID, '') AS TACTIC_ID
        , VIDEO_NAME
        , IS_PAGE_VIEW
        , IS_VIDEO_START
        , IS_VIDEO_25_PERCENT
        , IS_VIDEO_50_PERCENT
        , IS_VIDEO_75_PERCENT
        , IS_VIDEO_100_PERCENT
        , EVENT_TYPE
        , IS_FORM_SUBMIT_SUCCESS
        , IS_FORM_SUBMIT_ATTEMPT
        , LINK_DETAIL
        , IS_LINK_CLICK
        , POST_EVENT_LIST
        , CASE
            WHEN TRY_TO_DECIMAL(MOBILE_ID) = 0 THEN 'PC'
            WHEN TRY_TO_DECIMAL(MOBILE_ID) > 0 THEN 'MOBILE'
            WHEN (COALESCE(MOBILE_ID, '') IS NULL OR LENGTH(COALESCE(MOBILE_ID, '')) = 0 OR LOWER(COALESCE(MOBILE_ID, '')) LIKE '%unknown%') THEN 'UNKNOWN'
        END AS DEVICE_TYPE
        , TRY_TO_NUMBER(VISIT_NUMBER) AS VISIT_NUMBER
        , TRY_TO_NUMBER(IS_CART_ADD) AS IS_CART_ADD
        , SALES_PLATFORM
        , SALES_CHANNEL_TYPE
        , AGREEMENT_TYPE
        , ORDER_ORIGIN
        , FIN.SF_INDICATOR
        , FIN.SAP_PRODUCT_LINE AS SAP_PRODUCT_LINE
        , COALESCE(ALID.CAMPAIGN_INDUSTRY, IND.CAMPAIGN_INDUSTRY) AS CAMPAIGN_INDUSTRY
        , PROD.PRODUCT_FAMILY AS PRODUCT_FAMILY
        , PROD.PRODUCT_INDUSTRY AS PRODUCT_INDUSTRY
        , COALESCE(FIN.BUSINESS_TIER, ACCT.BUSINESS_TIER) AS BUSINESS_TIER
        , ENRICHED.MCVISID
        , MCVISID.ACCOUNT_CSN
        , COALESCE(ENRICHED.CAMPAIGN_ID, '') AS CAMPAIGN_ID
        , CAMP.CAMPAIGN_NAME
    FROM {{ ref('WEB_ADOBE_ANALYTICS_ENRICHED') }} ENRICHED
    LEFT JOIN DATE_TIME_HIERARCHY CAL
        ON ENRICHED.DT = CAL.CALENDAR_DATE
    LEFT JOIN CVC_FINMART FIN
        ON TRIM(REGEXP_REPLACE(ENRICHED.ORDER_ID, '[^[:digit:]]', ' ')) = TRIM(FIN.PO_NBR)
    LEFT JOIN DIM_FUZZYSEARCH_COUNTRY C
        ON LOWER(ENRICHED.GEO_COUNTRY_CODE) = LOWER(C.COUNTRY_SEARCH_CODE)
    LEFT JOIN MCVISID_TO_ACCOUNT_CSN MCVISID
        ON ENRICHED.MCVISID = MCVISID.MCVISID
    LEFT JOIN ACCOUNTS_CORE_DATASET ACCT
        ON MCVISID.ACCOUNT_CSN = ACCT.ACCOUNT_CSN
    LEFT JOIN CAMPAIGN_NAME_LATEST CAMP
        ON ENRICHED.CAMPAIGN_ID = CAMP.CAMPAIGN_ID
    LEFT JOIN ALLOCADIA_ID_REMAPPING_FOR_INDUSTRY IND
        ON TRIM(IND.CONV_PURCHASE_ID) = TRIM(REGEXP_REPLACE(ENRICHED.ORDER_ID, '[^[:digit:]]', ' '))
    LEFT JOIN {{ ref('LOOKUP_MPM_PRODUCT_CODE_TO_PRODUCT') }} PROD
        ON UPPER(ENRICHED.PRODUCT_LINE_ID) = UPPER(NVL(PROD.CODE,''))
    LEFT JOIN ALLOCADIA ALID
        ON CAST(ENRICHED.TACTIC_ID AS VARCHAR) = CAST(ALID.LINE_ITEM_ID AS VARCHAR)
    WHERE ENRICHED.DT > TO_DATE($START_DATE) AND ENRICHED.DT <= TO_DATE($END_DATE)
      AND ENRICHED.EXCLUDE_SEGMENT_IND = '0'
),

WEB_ANALYTICS_ADOBE_ENRICHED_WITH_SEGMENT AS
(
    SELECT *

        ,CASE
            WHEN (
                LOWER(PAGE_NAME) = 'tredence_analytics:en:404'
                AND REFERRER = 'https://knowledge.tredence_analytics.com/'
                AND DT BETWEEN '2023-01-24' AND '2023-03-07'
                ) THEN TRUE ELSE FALSE
        END AS v24_EXCL_404
        , CASE
            WHEN (
                MOE_QUOTE_ID LIKE ANY ('q-%', 'Q-%')
                AND LOWER(FLOW_STEP_DETAIL) LIKE 'odm order:%'
                AND DT >= '2023-05-01'
                ) THEN TRUE ELSE FALSE
        END AS EXCLUDE_NXM_CHANNEL
        , CASE
            WHEN (
                LOWER(ORIGIN_PARAMETER) LIKE '%moe%'
                OR LOWER(COALESCE(SF_INDICATOR, '')) = 'renew'
                OR (ORDER_PRODUCT_REVENUE = 0 AND (TRY_TO_NUMBER(IS_ORDER) = 1 AND (ORDER_ID_DETAILS IS NULL OR ORDER_ID_DETAILS = '')))
                OR COALESCE(ORDER_ID_PLATFORM, '') LIKE 'DE:%'
                ) THEN TRUE ELSE FALSE
        END AS EXCLUDE_MAX_MAYA
        , CASE
            WHEN (
                (
                    NOT(
                        PAGE_NAME LIKE ANY (
                            '%:support', '%:support:contact-support%', '%:support:technical%',
                            '%:support:account%', '%:support:download-install%','%:support:system-requirements%'
                        )
                    )
                )) THEN 'Without AKN'
            ELSE 'With AKN'
        END AS AKN_FLAG
        , CASE
            WHEN LOWER(PAGE_NAME) LIKE '%cart details%' OR TRY_TO_NUMBER(IS_CART_ADD) = 1
            THEN TRUE ELSE FALSE
        END AS IS_CART_ADD_VISIT
        , SYSDATE() AS DBT_LOAD_DATETIME
    FROM WEB_ANALYTICS_ADOBE_ENRICHED
)

SELECT *
FROM WEB_ANALYTICS_ADOBE_ENRICHED_WITH_SEGMENT
