-- airflow Dag which regulates this model: 
-- dir: mdp_360/mdp_i360_new_dag 
-- dag: mdp_i360_new_trg

-- Get the right stack database properties.
{% set db_properties=get_dbproperties('MDP_I360_NEW') %}


-- Set the database properties.
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Setting the Materialization.
{{ config(
        materialized='table'
) }}

-- set the right tags.
{{ config(tags=[var('TAG_MDP_I360_NEW'), var('TAG_MDP_I360_NEW_LEGACY_QV_DATA')
]) }}



WITH COMBINED_BUDGET AS (

    WITH NEW AS(
    SELECT DISTINCT YEAR, QUARTER, GEO, SUB_REGION, MATURITY, SUM(BUDGET_USD) AS BUDGET FROM(
    SELECT "FUND NAME" AS FUND_NAME, 
            'Q'||LEFT("FUND NAME",1) AS QUARTER,
            '20'||SUBSTRING("FUND NAME", 6, 2) AS YEAR,
            CASE WHEN GEO = 'JAPAN-GEO' THEN 'JAPAN' ELSE GEO END AS GEO,
            REPLACE(AREA, '-SR','') AS SUB_REGION,
            MATURITY,
            SUM("BUDGET USD") AS BUDGET_USD
    FROM -- "RAW"."MDF_LOOKUPS"."GLOBAL_MDF_BUDGET_CURRENT"
            {{ source('MDF_LOOKUPS', 'GLOBAL_MDF_BUDGET_CURRENT') }}
    GROUP BY "FUND NAME", GEO,AREA,MATURITY
    ) GROUP BY 1,2,3,4,5
    )

    SELECT YEAR, QUARTER, GEO, SUBREGION AS SUB_REGION, MATURITY, SUM("BUDGET AMOUNT") AS BUDGET
    FROM -- "RAW"."MDF_LOOKUPS"."GLOBAL_MDF_BUDGET"
            {{ source('MDF_LOOKUPS', 'GLOBAL_MDF_BUDGET') }}
    WHERE YEAR||QUARTER <= '2021Q1'
    GROUP BY 1,2,3,4,5
    HAVING YEAR||QUARTER <= '2021Q1'
    UNION
    SELECT YEAR, QUARTER, GEO, SUB_REGION, MATURITY, BUDGET FROM NEW

)

, FORMATTED_BUDGET AS (

    SELECT
    '' AS PARTNER_TYPE
    ,NULL AS CAMPAIGN_CHILD
    ,NULL AS SUM_OF_MDF_FUNDED
    ,CAST(YEAR AS VARCHAR(10))||QUARTER AS YEAR_QUARTER
    ,CASE WHEN QUARTER = 'Q1' THEN YEAR||'-02-01'
        WHEN QUARTER = 'Q2' THEN YEAR||'-05-01'
        WHEN QUARTER = 'Q3' THEN YEAR||'-08-01'
        WHEN QUARTER = 'Q4' THEN YEAR||'-11-01'
    END AS YEAR_QUARTER_DATE
    ,NULL AS MDP_GATE_QUARTER
    ,NULL AS PMM
    ,NULL AS PARTNER_MANAGER
    ,GEO
    ,MATURITY AS MATURITY
    ,SUB_REGION
    ,NULL AS COUNTRY
    ,'D' AS  GTM_TIER
    ,NULL AS TIER
    ,NULL AS PARTNER_NAME
    ,NULL AS CSN
    ,NULL AS CAMPAIGN_INDUSTRY
    ,NULL AS CAMPAIGN_PARENT
    ,NULL AS FR_NAME
    ,NULL AS FR_ACTIVITY_NAME
    ,NULL AS ACTIVITY_TYPE
    ,NULL AS ACTIVITY_NAME
    ,NULL AS ACTIVITY_BEGIN_DATE
    ,NULL AS SUM_OF_NBR_ATTENDEES
    ,NULL AS SUM_OF_NBR_OF_COMPLETED_TM_CALLS
    ,NULL AS SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS
    ,NULL AS SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS
    ,NULL AS MQLs
    ,NULL AS SUM_OF_EXPECTED_NBR_ATTENDEES
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS
    ,NULL AS C6_10_DAYS_TO_ROI_DEADLINE
    ,NULL AS LAST_5_DAYS_TO_ROI_DEADLINE
    ,NULL AS ROI_DEADLINE_OVER
    ,NULL AS ROI_COMPLETED
    ,NULL AS GEP_EVENT_ID
    ,NULL AS ACTIVITY_END_DATE
    ,NULL AS MARKETING_REGION
    ,NULL AS FOCUS_PARTNER
    ,NULL AS SPEND_TYPE
    ,'Budget' AS METRIC_NAME
    ,BUDGET AS SUM_OF_METRIC_VALUE
    ,NULL AS PLAN_STATUS
    ,NULL AS PLAN_APPROVER
    ,NULL AS PLAN_APPROVED_AMOUNT
    ,NULL AS TARGET_COUNTRY
    ,NULL AS ENGAGEMENT_COMPLETE
    ,NULL AS CLAIM_AUDIT_STATUS
    ,NULL AS CLAIM_BY_DATE
    ,NULL AS CLAIM_SUBMITTED_DATE
    ,NULL AS PLAN_SUBMISSION_DATE
    ,NULL AS SUBMISSION_GATE_COMPLIANT
    ,NULL AS CAMPAIGN
    ,NULL AS CAMPAIGN_TYPE
    ,NULL AS RR_STATUS
    ,NULL AS FR_APPROVED_AMOUNT_LC	
    ,NULL AS FR_DESCRIPTION	
    ,NULL AS REPORT_CREATE_DATE
    ,NULL AS RR_HOLD_REASON
    ,NULL AS RR_HOLD_DATE
    ,NULL AS RR_LAST_DATE_UPDATED
    ,NULL AS RR_EXTERNAL_COMMENTS
    ,NULL AS RR_INTERNAL_COMMENTS

    FROM -- $T{COMBINED_BUDGET}
    COMBINED_BUDGET
)

,CCI_REPORT_TRANSFORMATION AS (
    SELECT 
    cp."PARTNER TYPE" AS PARTNER_TYPE
    ,NULL AS CAMPAIGN_CHILD 
    ,MDF_FUNDED AS SUM_OF_MDF_FUNDED
    ,YEARQUARTER AS YEAR_QUARTER
    ,CASE WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q1' THEN LEFT(YEAR_QUARTER,4)||'-02-01' 
                WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q2' THEN LEFT(YEAR_QUARTER,4)||'-05-01' 
                WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q3' THEN LEFT(YEAR_QUARTER,4)||'-08-01' 
                WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q4' THEN LEFT(YEAR_QUARTER,4)||'-11-01' 
            END AS YEAR_QUARTER_DATE
    ,NULL AS MDP_GATE_QUARTER
    ,cp.CMM AS PMM
    ,PARTNER_MANAGER
    ,cp.GEO
    ,MATURITY
    ,cp."SUB REGION" AS SUB_REGION
    ,COUNTRY
    ,NULL AS GTM_TIER
    ,TIER
    ,cp."PARTNER NAME" AS PARTNER_NAME
    ,cci.CSN
    ,CAMPAIGN_INDUSTRY
    ,NULL AS CAMPAIGN_PARENT 
    ,FR_NAME
    ,NULL AS FR_ACTIVITY_NAME
    ,ACTIVITY_TYPE
    ,ACTIVITY_NAME
    ,START_DATE AS ACTIVITY_BEGIN_DATE
    ,_OF_ATTENDEES AS SUM_OF_NBR_ATTENDEES
    ,_OF_COMPLETED_TM_CALLS AS SUM_OF_NBR_OF_COMPLETED_TM_CALLS
    ,_OF_DIRECT_EMAIL_CLICKS AS SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS
    ,_OF_ONLINE_MEDIA_CLICKS AS SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS
    ,NULL AS MQLs
    ,NULL AS SUM_OF_EXPECTED_NBR_ATTENDEES
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS
    ,C_6_10_DAYS_TO_ROI_DEADLINE AS C6_10_DAYS_TO_ROI_DEADLINE
    ,LAST_5_DAYS_TO_ROI_DEADLINE AS LAST_5_DAYS_TO_ROI_DEADLINE
    ,ROI_DEADLINE_OVER AS ROI_DEADLINE_OVER
    ,ROI_COMPLETED AS ROI_COMPLETED
    ,GEP_EVENT_ID AS GEP_EVENT_ID
    ,END_DATE AS ACTIVITY_END_DATE
    ,MARKETING_REGION AS MARKETING_REGION
    ,FOCUS_PARTNERS_ONLY AS FOCUS_PARTNER
    ,SPEND_TYPE AS SPEND_TYPE
    ,'Spend' AS METRIC_NAME
    ,MDF_FUNDED AS SUM_OF_METRIC_VALUE
    ,NULL AS PLAN_STATUS
    ,NULL AS PLAN_APPROVER
    ,NULL AS PLAN_APPROVED_AMOUNT
    ,NULL AS TARGET_COUNTRY
    ,'No' AS ENGAGEMENT_COMPLETE
    ,NULL AS CLAIM_AUDIT_STATUS
    ,NULL AS CLAIM_BY_DATE
    ,NULL AS CLAIM_SUBMITTED_DATE
    ,NULL AS PLAN_SUBMISSION_DATE
    ,NULL AS SUBMISSION_GATE_COMPLIANT
    ,CAMPAIGN
    ,CAMPAIGN_TYPE
    ,NULL AS RR_STATUS
    ,NULL AS FR_APPROVED_AMOUNT_LC	
    ,NULL AS FR_DESCRIPTION	
    ,NULL AS REPORT_CREATE_DATE
    ,NULL AS RR_HOLD_REASON
    ,NULL AS RR_HOLD_DATE
    ,NULL AS RR_LAST_DATE_UPDATED
    ,NULL AS RR_EXTERNAL_COMMENTS
    ,NULL AS RR_INTERNAL_COMMENTS
    
    
    FROM -- "RAW"."QV_LEGACY"."CCI_REPORT" 
         {{ source('QV_LEGACY', 'CCI_REPORT') }}   cci
    LEFT JOIN 
        (
            SELECT * FROM 
            -- "RAW"."MDF_LOOKUPS"."MDP_CMM_PARTNER_LIST"
            {{ source('MDF_LOOKUPS', 'MDP_CMM_PARTNER_LIST') }}
            WHERE "YEAR QUARTER" = 'FY21 Q4') cp
        ON LPAD(CAST(cci.CSN AS VARCHAR(50)),10,'0') = LPAD(TRIM(CAST(REPLACE(cp.CSN,'.0','') AS VARCHAR)),10,'0')
    WHERE FR_NAME IS NOT NULL AND FR_NAME <>''
)

,MDF_ROI_ROLL_UP_TRANSFORMATION AS (

    SELECT
    cp."PARTNER TYPE" AS PARTNER_TYPE
    ,NULL AS CAMPAIGN_CHILD
    ,MDF_FUNDED AS SUM_OF_MDF_FUNDED
    ,YEAR_QUARTER
    ,CASE WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q1' THEN LEFT(YEAR_QUARTER,4)||'-02-01' 
        WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q2' THEN LEFT(YEAR_QUARTER,4)||'-05-01' 
        WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q3' THEN LEFT(YEAR_QUARTER,4)||'-08-01' 
        WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q4' THEN LEFT(YEAR_QUARTER,4)||'-11-01' 
    END AS YEAR_QUARTER_DATE
    ,NULL AS MDP_GATE_QUARTER
    ,cp.CMM AS PMM
    ,PARTNER_MANAGER
    ,cp.GEO
    ,MATURITY
    ,cp."SUB REGION" AS SUB_REGION
    ,COUNTRY
    ,NULL AS GTM_TIER
    ,TIER
    ,cp."PARTNER NAME" AS PARTNER_NAME
    ,rol.CSN
    ,CAMPAIGN_INDUSTRY
    ,NULL AS CAMPAIGN_PARENT 
    ,FR_NAME
    ,NULL AS FR_ACTIVITY_NAME
    ,ACTIVITY_TYPE
    ,ACTIVITY_NAME
    ,START_DATE AS ACTIVITY_BEGIN_DATE
    ,_OF_ATTENDEES AS SUM_OF_NBR_ATTENDEES
    ,_OF_COMPLETED_TM_CALLS AS SUM_OF_NBR_OF_COMPLETED_TM_CALLS
    ,_OF_DIRECT_EMAIL_CLICKS AS SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS
    ,_OF_ONLINE_MEDIA_CLICKS AS SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS
    ,NULL AS MQLs
    ,NULL AS SUM_OF_EXPECTED_NBR_ATTENDEES
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS
    ,_6_10_DAYS_TO_ROI_DEADLINE AS C6_10_DAYS_TO_ROI_DEADLINE
    ,LAST_5_DAYS_TO_ROI_DEADLINE AS LAST_5_DAYS_TO_ROI_DEADLINE
    ,ROI_DEADLINE_OVER AS ROI_DEADLINE_OVER
    ,ROI_COMPLETED AS ROI_COMPLETED
    ,GEP_EVENT_ID AS GEP_EVENT_ID
    ,END_DATE AS ACTIVITY_END_DATE
    ,MARKETING_REGION AS MARKETING_REGION
    ,FOCUS_PARTNERS_ONLY AS FOCUS_PARTNER
    ,NULL AS SPEND_TYPE
    ,'Spend' METRIC_NAME
    ,MDF_FUNDED AS SUM_OF_METRIC_VALUE
    ,NULL AS PLAN_STATUS
    ,NULL AS PLAN_APPROVER
    ,NULL AS PLAN_APPROVED_AMOUNT
    ,NULL AS TARGET_COUNTRY
    ,'No' AS ENGAGEMENT_COMPLETE
    ,NULL AS CLAIM_AUDIT_STATUS
    ,NULL AS CLAIM_BY_DATE
    ,NULL AS CLAIM_SUBMITTED_DATE
    ,NULL AS PLAN_SUBMISSION_DATE
    ,NULL AS SUBMISSION_GATE_COMPLIANT
    ,REPLACE(CAMPAIGN,'–','-') AS CAMPAIGN
    ,CAMPAIGN_TYPE
    ,NULL AS RR_STATUS
    ,NULL AS FR_APPROVED_AMOUNT_LC	
    ,NULL AS FR_DESCRIPTION	
    ,NULL AS REPORT_CREATE_DATE
    ,NULL AS RR_HOLD_REASON
    ,NULL AS RR_HOLD_DATE
    ,NULL AS RR_LAST_DATE_UPDATED
    ,NULL AS RR_EXTERNAL_COMMENTS
    ,NULL AS RR_INTERNAL_COMMENTS
    
    FROM -- "RAW"."QV_LEGACY"."MDF_ROI_ROLL_UP" 
            {{ source('QV_LEGACY', 'MDF_ROI_ROLL_UP') }} rol
    LEFT JOIN (SELECT * FROM "RAW"."MDF_LOOKUPS"."MDP_CMM_PARTNER_LIST" WHERE "YEAR QUARTER" = 'FY21 Q4') cp
        ON LPAD(CAST(rol.CSN AS VARCHAR(50)),10,'0') = LPAD(TRIM(CAST(REPLACE(cp.CSN,'.0','') AS VARCHAR)),10,'0')
    WHERE FR_NAME IS NOT NULL AND FR_NAME <>''

)


-- union of cci_report_transformation cte & mdf_roi_roll_up_transformation cte
,CCI_REPORT_TRNS_UNION_MDF_ROI_ROLL_UP_TRANS AS (

   (SELECT 
        "PARTNER_TYPE", 
        "CAMPAIGN_CHILD", 
        CAST("SUM_OF_MDF_FUNDED" AS NUMBER(18, 4)) AS "SUM_OF_MDF_FUNDED", 
        "YEAR_QUARTER", 
        "YEAR_QUARTER_DATE", 
        "MDP_GATE_QUARTER", 
        "PMM", 
        "PARTNER_MANAGER", 
        "GEO", 
        "MATURITY", 
        "SUB_REGION", 
        "COUNTRY", 
        "GTM_TIER", 
        "TIER", 
        "PARTNER_NAME", 
        "CSN", 
        "CAMPAIGN_INDUSTRY", 
        "CAMPAIGN_PARENT", 
        "FR_NAME", 
        "FR_ACTIVITY_NAME", 
        "ACTIVITY_TYPE", 
        "ACTIVITY_NAME", 
        "ACTIVITY_BEGIN_DATE", 
        CAST("SUM_OF_NBR_ATTENDEES" AS NUMBER(38, 2)) AS "SUM_OF_NBR_ATTENDEES", 
        CAST("SUM_OF_NBR_OF_COMPLETED_TM_CALLS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_COMPLETED_TM_CALLS", 
        "SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS", 
        CAST("SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS", 
        "MQLS", 
        "SUM_OF_EXPECTED_NBR_ATTENDEES", 
        "SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS", 
        "SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS", 
        "C6_10_DAYS_TO_ROI_DEADLINE", 
        "LAST_5_DAYS_TO_ROI_DEADLINE", 
        "ROI_DEADLINE_OVER", 
        "ROI_COMPLETED", 
        "GEP_EVENT_ID", 
        "ACTIVITY_END_DATE", 
        "MARKETING_REGION", 
        "FOCUS_PARTNER", 
        CAST("SPEND_TYPE" AS VARCHAR(256)) AS "SPEND_TYPE", 
        "METRIC_NAME", 
        CAST("SUM_OF_METRIC_VALUE" AS NUMBER(18, 4)) AS "SUM_OF_METRIC_VALUE", 
        "PLAN_STATUS", 
        "PLAN_APPROVER", 
        "PLAN_APPROVED_AMOUNT", 
        "TARGET_COUNTRY", 
        "ENGAGEMENT_COMPLETE", 
        "CLAIM_AUDIT_STATUS", 
        "CLAIM_BY_DATE", 
        "CLAIM_SUBMITTED_DATE", 
        "PLAN_SUBMISSION_DATE", 
        "SUBMISSION_GATE_COMPLIANT", 
        "CAMPAIGN", 
        "CAMPAIGN_TYPE", 
        "RR_STATUS", 
        "FR_APPROVED_AMOUNT_LC", 
        "FR_DESCRIPTION", 
        "REPORT_CREATE_DATE", 
        "RR_HOLD_REASON", 
        "RR_HOLD_DATE", 
        "RR_LAST_DATE_UPDATED", 
        "RR_EXTERNAL_COMMENTS", 
        "RR_INTERNAL_COMMENTS" 
 FROM --($T{SQL 2})
        MDF_ROI_ROLL_UP_TRANSFORMATION
 ) 

UNION ALL 

   (SELECT 
        "PARTNER_TYPE", 
        "CAMPAIGN_CHILD", 
        "SUM_OF_MDF_FUNDED", 
        "YEAR_QUARTER", 
        "YEAR_QUARTER_DATE", 
        "MDP_GATE_QUARTER", 
        "PMM", 
        "PARTNER_MANAGER", 
        "GEO", 
        "MATURITY", 
        "SUB_REGION", 
        "COUNTRY", 
        "GTM_TIER", 
        "TIER", 
        "PARTNER_NAME", 
        "CSN", 
        "CAMPAIGN_INDUSTRY", 
        "CAMPAIGN_PARENT", 
        "FR_NAME", 
        "FR_ACTIVITY_NAME", 
        "ACTIVITY_TYPE", 
        CAST("ACTIVITY_NAME" AS VARCHAR(512)) AS "ACTIVITY_NAME", 
        "ACTIVITY_BEGIN_DATE", 
        CAST("SUM_OF_NBR_ATTENDEES" AS NUMBER(38, 2)) AS "SUM_OF_NBR_ATTENDEES", 
        CAST("SUM_OF_NBR_OF_COMPLETED_TM_CALLS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_COMPLETED_TM_CALLS", 
        "SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS", 
        CAST("SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS", 
        "MQLS", 
        "SUM_OF_EXPECTED_NBR_ATTENDEES", 
        "SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS", 
        "SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS", 
        "C6_10_DAYS_TO_ROI_DEADLINE", 
        "LAST_5_DAYS_TO_ROI_DEADLINE", 
        "ROI_DEADLINE_OVER", 
        "ROI_COMPLETED", 
        "GEP_EVENT_ID", 
        "ACTIVITY_END_DATE", 
        "MARKETING_REGION", 
        "FOCUS_PARTNER", 
        "SPEND_TYPE", 
        "METRIC_NAME", 
        "SUM_OF_METRIC_VALUE", 
        "PLAN_STATUS", 
        "PLAN_APPROVER", 
        "PLAN_APPROVED_AMOUNT", 
        "TARGET_COUNTRY", 
        "ENGAGEMENT_COMPLETE", 
        "CLAIM_AUDIT_STATUS", 
        "CLAIM_BY_DATE", 
        "CLAIM_SUBMITTED_DATE", 
        "PLAN_SUBMISSION_DATE", 
        "SUBMISSION_GATE_COMPLIANT", 
        CAST("CAMPAIGN" AS VARCHAR) AS "CAMPAIGN", 
        "CAMPAIGN_TYPE", 
        "RR_STATUS", 
        "FR_APPROVED_AMOUNT_LC", 
        "FR_DESCRIPTION", 
        "REPORT_CREATE_DATE", 
        "RR_HOLD_REASON", 
        "RR_HOLD_DATE", 
        "RR_LAST_DATE_UPDATED", 
        "RR_EXTERNAL_COMMENTS", 
        "RR_INTERNAL_COMMENTS" 
 FROM -- ($T{SQL 1})
    CCI_REPORT_TRANSFORMATION
 ))






-- Transformaion on union(ed) result from cci_report_trns_union_mdf_roi_roll_up_trans cte
, UNION_TRANSFORMATION AS (
    SELECT 
    PARTNER_TYPE
    ,CAMPAIGN_CHILD 
    ,SUM_OF_MDF_FUNDED
    ,YEAR_QUARTER
    ,YEAR_QUARTER_DATE
    ,MDP_GATE_QUARTER
    ,NULL AS PMM
    ,PARTNER_MANAGER
    ,GEO
    ,MATURITY
    ,CASE WHEN regexp_substr(SUB_REGION, '-.*$') IS NOT NULL THEN REPLACE(SUB_REGION,regexp_substr(SUB_REGION, '-.*$'),'') 
            ELSE SUB_REGION END AS SUB_REGION
    ,A.COUNTRY
    ,COALESCE(GTM.GTM_TIER,'D') AS GTM_TIER
    ,TIER
    ,PARTNER_NAME
    ,CSN
    ,CAMPAIGN_INDUSTRY
    ,CAMPAIGN_PARENT 
    ,FR_NAME
    ,FR_ACTIVITY_NAME
    ,ACTIVITY_TYPE
    ,ACTIVITY_NAME
    ,ACTIVITY_BEGIN_DATE
    ,SUM_OF_NBR_ATTENDEES
    ,SUM_OF_NBR_OF_COMPLETED_TM_CALLS
    ,SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS
    ,SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS
    ,MQLs
    ,SUM_OF_EXPECTED_NBR_ATTENDEES
    ,SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS
    ,SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS
    ,C6_10_DAYS_TO_ROI_DEADLINE
    ,LAST_5_DAYS_TO_ROI_DEADLINE
    ,ROI_DEADLINE_OVER
    ,ROI_COMPLETED
    ,GEP_EVENT_ID
    ,ACTIVITY_END_DATE
    ,MARKETING_REGION
    ,NULL AS FOCUS_PARTNER
    ,SPEND_TYPE
    ,METRIC_NAME
    ,SUM_OF_METRIC_VALUE
    ,PLAN_STATUS
    ,PLAN_APPROVER
    ,PLAN_APPROVED_AMOUNT
    ,TARGET_COUNTRY
    ,ENGAGEMENT_COMPLETE
    ,CLAIM_AUDIT_STATUS
    ,CLAIM_BY_DATE
    ,CLAIM_SUBMITTED_DATE
    ,PLAN_SUBMISSION_DATE
    ,SUBMISSION_GATE_COMPLIANT
    ,CAMPAIGN
    ,CAMPAIGN_TYPE
    ,RR_STATUS
    ,FR_APPROVED_AMOUNT_LC	
    ,FR_DESCRIPTION	
    ,REPORT_CREATE_DATE
    ,RR_HOLD_REASON
    ,RR_HOLD_DATE
    ,RR_LAST_DATE_UPDATED
    ,RR_EXTERNAL_COMMENTS
    ,RR_INTERNAL_COMMENTS

    FROM (((SELECT 
    "PARTNER_TYPE", 
    "CAMPAIGN_CHILD", 
    CAST("SUM_OF_MDF_FUNDED" AS NUMBER(18, 4)) AS "SUM_OF_MDF_FUNDED", 
    "YEAR_QUARTER", 
    "YEAR_QUARTER_DATE", 
    "MDP_GATE_QUARTER", 
    "PMM", 
    "PARTNER_MANAGER", 
    "GEO", 
    "MATURITY", 
    "SUB_REGION", 
    "COUNTRY", 
    "GTM_TIER", 
    "TIER", 
    "PARTNER_NAME", 
    "CSN", 
    "CAMPAIGN_INDUSTRY", 
    "CAMPAIGN_PARENT", 
    "FR_NAME", 
    "FR_ACTIVITY_NAME", 
    "ACTIVITY_TYPE", 
    "ACTIVITY_NAME", 
    "ACTIVITY_BEGIN_DATE", 
    CAST("SUM_OF_NBR_ATTENDEES" AS NUMBER(38, 2)) AS "SUM_OF_NBR_ATTENDEES", 
    CAST("SUM_OF_NBR_OF_COMPLETED_TM_CALLS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_COMPLETED_TM_CALLS", 
    "SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS", 
    CAST("SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS", 
    "MQLS", 
    "SUM_OF_EXPECTED_NBR_ATTENDEES", 
    "SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS", 
    "SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS", 
    "C6_10_DAYS_TO_ROI_DEADLINE", 
    "LAST_5_DAYS_TO_ROI_DEADLINE", 
    "ROI_DEADLINE_OVER", 
    "ROI_COMPLETED", 
    "GEP_EVENT_ID", 
    "ACTIVITY_END_DATE", 
    "MARKETING_REGION", 
    "FOCUS_PARTNER", 
    CAST("SPEND_TYPE" AS VARCHAR(256)) AS "SPEND_TYPE", 
    "METRIC_NAME", 
    CAST("SUM_OF_METRIC_VALUE" AS NUMBER(18, 4)) AS "SUM_OF_METRIC_VALUE", 
    "PLAN_STATUS", 
    "PLAN_APPROVER", 
    "PLAN_APPROVED_AMOUNT", 
    "TARGET_COUNTRY", 
    "ENGAGEMENT_COMPLETE", 
    "CLAIM_AUDIT_STATUS", 
    "CLAIM_BY_DATE", 
    "CLAIM_SUBMITTED_DATE", 
    "PLAN_SUBMISSION_DATE", 
    "SUBMISSION_GATE_COMPLIANT", 
    "CAMPAIGN", 
    "CAMPAIGN_TYPE", 
    "RR_STATUS", 
    "FR_APPROVED_AMOUNT_LC", 
    "FR_DESCRIPTION", 
    "REPORT_CREATE_DATE", 
    "RR_HOLD_REASON", 
    "RR_HOLD_DATE", 
    "RR_LAST_DATE_UPDATED", 
    "RR_EXTERNAL_COMMENTS", 
    "RR_INTERNAL_COMMENTS" 
    FROM ((SELECT
    cp."PARTNER TYPE" AS PARTNER_TYPE
    ,NULL AS CAMPAIGN_CHILD
    ,MDF_FUNDED AS SUM_OF_MDF_FUNDED
    ,YEAR_QUARTER
    ,CASE WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q1' THEN LEFT(YEAR_QUARTER,4)||'-02-01' 
        WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q2' THEN LEFT(YEAR_QUARTER,4)||'-05-01' 
        WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q3' THEN LEFT(YEAR_QUARTER,4)||'-08-01' 
        WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q4' THEN LEFT(YEAR_QUARTER,4)||'-11-01' 
    END AS YEAR_QUARTER_DATE
    ,NULL AS MDP_GATE_QUARTER
    ,cp.CMM AS PMM
    ,PARTNER_MANAGER
    ,cp.GEO
    ,MATURITY
    ,cp."SUB REGION" AS SUB_REGION
    ,COUNTRY
    ,NULL AS GTM_TIER
    ,TIER
    ,cp."PARTNER NAME" AS PARTNER_NAME
    ,rol.CSN
    ,CAMPAIGN_INDUSTRY
    ,NULL AS CAMPAIGN_PARENT 
    ,FR_NAME
    ,NULL AS FR_ACTIVITY_NAME
    ,ACTIVITY_TYPE
    ,ACTIVITY_NAME
    ,START_DATE AS ACTIVITY_BEGIN_DATE
    ,_OF_ATTENDEES AS SUM_OF_NBR_ATTENDEES
    ,_OF_COMPLETED_TM_CALLS AS SUM_OF_NBR_OF_COMPLETED_TM_CALLS
    ,_OF_DIRECT_EMAIL_CLICKS AS SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS
    ,_OF_ONLINE_MEDIA_CLICKS AS SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS
    ,NULL AS MQLs
    ,NULL AS SUM_OF_EXPECTED_NBR_ATTENDEES
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS
    ,_6_10_DAYS_TO_ROI_DEADLINE AS C6_10_DAYS_TO_ROI_DEADLINE
    ,LAST_5_DAYS_TO_ROI_DEADLINE AS LAST_5_DAYS_TO_ROI_DEADLINE
    ,ROI_DEADLINE_OVER AS ROI_DEADLINE_OVER
    ,ROI_COMPLETED AS ROI_COMPLETED
    ,GEP_EVENT_ID AS GEP_EVENT_ID
    ,END_DATE AS ACTIVITY_END_DATE
    ,MARKETING_REGION AS MARKETING_REGION
    ,FOCUS_PARTNERS_ONLY AS FOCUS_PARTNER
    ,NULL AS SPEND_TYPE
    ,'Spend' METRIC_NAME
    ,MDF_FUNDED AS SUM_OF_METRIC_VALUE
    ,NULL AS PLAN_STATUS
    ,NULL AS PLAN_APPROVER
    ,NULL AS PLAN_APPROVED_AMOUNT
    ,NULL AS TARGET_COUNTRY
    ,'No' AS ENGAGEMENT_COMPLETE
    ,NULL AS CLAIM_AUDIT_STATUS
    ,NULL AS CLAIM_BY_DATE
    ,NULL AS CLAIM_SUBMITTED_DATE
    ,NULL AS PLAN_SUBMISSION_DATE
    ,NULL AS SUBMISSION_GATE_COMPLIANT
    ,REPLACE(CAMPAIGN,'–','-') AS CAMPAIGN
    ,CAMPAIGN_TYPE
    ,NULL AS RR_STATUS
    ,NULL AS FR_APPROVED_AMOUNT_LC	
    ,NULL AS FR_DESCRIPTION	
    ,NULL AS REPORT_CREATE_DATE
    ,NULL AS RR_HOLD_REASON
    ,NULL AS RR_HOLD_DATE
    ,NULL AS RR_LAST_DATE_UPDATED
    ,NULL AS RR_EXTERNAL_COMMENTS
    ,NULL AS RR_INTERNAL_COMMENTS
    
    FROM -- "RAW"."QV_LEGACY"."MDF_ROI_ROLL_UP"
            {{ source('QV_LEGACY', 'MDF_ROI_ROLL_UP') }} rol
    LEFT JOIN (
                SELECT * FROM
                -- "RAW"."MDF_LOOKUPS"."MDP_CMM_PARTNER_LIST" 
                {{ source('MDF_LOOKUPS', 'MDP_CMM_PARTNER_LIST') }}
                WHERE "YEAR QUARTER" = 'FY21 Q4') cp
        ON LPAD(CAST(rol.CSN AS VARCHAR(50)),10,'0') = LPAD(TRIM(CAST(REPLACE(cp.CSN,'.0','') AS VARCHAR)),10,'0')
        WHERE FR_NAME IS NOT NULL AND FR_NAME <>''
    ))) 


    UNION ALL 

    (SELECT 
    "PARTNER_TYPE", 
    "CAMPAIGN_CHILD", 
    "SUM_OF_MDF_FUNDED", 
    "YEAR_QUARTER", 
    "YEAR_QUARTER_DATE", 
    "MDP_GATE_QUARTER", 
    "PMM", 
    "PARTNER_MANAGER", 
    "GEO", 
    "MATURITY", 
    "SUB_REGION", 
    "COUNTRY", 
    "GTM_TIER", 
    "TIER", 
    "PARTNER_NAME", 
    "CSN", 
    "CAMPAIGN_INDUSTRY", 
    "CAMPAIGN_PARENT", 
    "FR_NAME", 
    "FR_ACTIVITY_NAME", 
    "ACTIVITY_TYPE", 
    CAST("ACTIVITY_NAME" AS VARCHAR(512)) AS "ACTIVITY_NAME", 
    "ACTIVITY_BEGIN_DATE", 
    CAST("SUM_OF_NBR_ATTENDEES" AS NUMBER(38, 2)) AS "SUM_OF_NBR_ATTENDEES", 
    CAST("SUM_OF_NBR_OF_COMPLETED_TM_CALLS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_COMPLETED_TM_CALLS", 
    "SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS", 
    CAST("SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS" AS NUMBER(38, 2)) AS "SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS", 
    "MQLS", 
    "SUM_OF_EXPECTED_NBR_ATTENDEES", 
    "SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS", 
    "SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS", 
    "C6_10_DAYS_TO_ROI_DEADLINE", 
    "LAST_5_DAYS_TO_ROI_DEADLINE", 
    "ROI_DEADLINE_OVER", 
    "ROI_COMPLETED", 
    "GEP_EVENT_ID", 
    "ACTIVITY_END_DATE", 
    "MARKETING_REGION", 
    "FOCUS_PARTNER", 
    "SPEND_TYPE", 
    "METRIC_NAME", 
    "SUM_OF_METRIC_VALUE", 
    "PLAN_STATUS", 
    "PLAN_APPROVER", 
    "PLAN_APPROVED_AMOUNT", 
    "TARGET_COUNTRY", 
    "ENGAGEMENT_COMPLETE", 
    "CLAIM_AUDIT_STATUS", 
    "CLAIM_BY_DATE", 
    "CLAIM_SUBMITTED_DATE", 
    "PLAN_SUBMISSION_DATE", 
    "SUBMISSION_GATE_COMPLIANT", 
    CAST("CAMPAIGN" AS VARCHAR) AS "CAMPAIGN", 
    "CAMPAIGN_TYPE", 
    "RR_STATUS", 
    "FR_APPROVED_AMOUNT_LC", 
    "FR_DESCRIPTION", 
    "REPORT_CREATE_DATE", 
    "RR_HOLD_REASON", 
    "RR_HOLD_DATE", 
    "RR_LAST_DATE_UPDATED", 
    "RR_EXTERNAL_COMMENTS", 
    "RR_INTERNAL_COMMENTS" 
    FROM 
    (( SELECT 
    cp."PARTNER TYPE" AS PARTNER_TYPE
    ,NULL AS CAMPAIGN_CHILD 
    ,MDF_FUNDED AS SUM_OF_MDF_FUNDED
    ,YEARQUARTER AS YEAR_QUARTER
    ,CASE WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q1' THEN LEFT(YEAR_QUARTER,4)||'-02-01' 
                WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q2' THEN LEFT(YEAR_QUARTER,4)||'-05-01' 
                WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q3' THEN LEFT(YEAR_QUARTER,4)||'-08-01' 
                WHEN YEAR_QUARTER IS NOT NULL AND RIGHT(YEAR_QUARTER,2) = 'Q4' THEN LEFT(YEAR_QUARTER,4)||'-11-01' 
            END AS YEAR_QUARTER_DATE
    ,NULL AS MDP_GATE_QUARTER
    ,cp.CMM AS PMM
    ,PARTNER_MANAGER
    ,cp.GEO
    ,MATURITY
    ,cp."SUB REGION" AS SUB_REGION
    ,COUNTRY
    ,NULL AS GTM_TIER
    ,TIER
    ,cp."PARTNER NAME" AS PARTNER_NAME
    ,cci.CSN
    ,CAMPAIGN_INDUSTRY
    ,NULL AS CAMPAIGN_PARENT 
    ,FR_NAME
    ,NULL AS FR_ACTIVITY_NAME
    ,ACTIVITY_TYPE
    ,ACTIVITY_NAME
    ,START_DATE AS ACTIVITY_BEGIN_DATE
    ,_OF_ATTENDEES AS SUM_OF_NBR_ATTENDEES
    ,_OF_COMPLETED_TM_CALLS AS SUM_OF_NBR_OF_COMPLETED_TM_CALLS
    ,_OF_DIRECT_EMAIL_CLICKS AS SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS
    ,_OF_ONLINE_MEDIA_CLICKS AS SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS
    ,NULL AS MQLs
    ,NULL AS SUM_OF_EXPECTED_NBR_ATTENDEES
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS
    ,NULL AS SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS
    ,C_6_10_DAYS_TO_ROI_DEADLINE AS C6_10_DAYS_TO_ROI_DEADLINE
    ,LAST_5_DAYS_TO_ROI_DEADLINE AS LAST_5_DAYS_TO_ROI_DEADLINE
    ,ROI_DEADLINE_OVER AS ROI_DEADLINE_OVER
    ,ROI_COMPLETED AS ROI_COMPLETED
    ,GEP_EVENT_ID AS GEP_EVENT_ID
    ,END_DATE AS ACTIVITY_END_DATE
    ,MARKETING_REGION AS MARKETING_REGION
    ,FOCUS_PARTNERS_ONLY AS FOCUS_PARTNER
    ,SPEND_TYPE AS SPEND_TYPE
    ,'Spend' AS METRIC_NAME
    ,MDF_FUNDED AS SUM_OF_METRIC_VALUE
    ,NULL AS PLAN_STATUS
    ,NULL AS PLAN_APPROVER
    ,NULL AS PLAN_APPROVED_AMOUNT
    ,NULL AS TARGET_COUNTRY
    ,'No' AS ENGAGEMENT_COMPLETE
    ,NULL AS CLAIM_AUDIT_STATUS
    ,NULL AS CLAIM_BY_DATE
    ,NULL AS CLAIM_SUBMITTED_DATE
    ,NULL AS PLAN_SUBMISSION_DATE
    ,NULL AS SUBMISSION_GATE_COMPLIANT
    ,CAMPAIGN
    ,CAMPAIGN_TYPE
    ,NULL AS RR_STATUS
    ,NULL AS FR_APPROVED_AMOUNT_LC	
    ,NULL AS FR_DESCRIPTION	
    ,NULL AS REPORT_CREATE_DATE
    ,NULL AS RR_HOLD_REASON
    ,NULL AS RR_HOLD_DATE
    ,NULL AS RR_LAST_DATE_UPDATED
    ,NULL AS RR_EXTERNAL_COMMENTS
    ,NULL AS RR_INTERNAL_COMMENTS
    
    
    FROM 
    -- "RAW"."QV_LEGACY"."CCI_REPORT" 
        {{ source('QV_LEGACY', 'CCI_REPORT') }} cci

    LEFT JOIN 
        (   SELECT * FROM 
            -- "RAW"."MDF_LOOKUPS"."MDP_CMM_PARTNER_LIST" 
            {{ source('MDF_LOOKUPS', 'MDP_CMM_PARTNER_LIST') }}
            WHERE "YEAR QUARTER" = 'FY21 Q4'
        ) cp
        ON LPAD(CAST(cci.CSN AS VARCHAR(50)),10,'0') = LPAD(TRIM(CAST(REPLACE(cp.CSN,'.0','') AS VARCHAR)),10,'0')
    WHERE FR_NAME IS NOT NULL AND FR_NAME <>''
    ))))) A
    LEFT JOIN 
    -- "RAW"."MDF_LOOKUPS"."GTM_TIERS" 
    {{ source('MDF_LOOKUPS', 'GTM_TIERS') }} GTM
    ON LOWER(A.COUNTRY) = LOWER(GTM.COUNTRY)
    WHERE (try_to_numeric(CSN) IS NOT NULL OR METRIC_NAME = 'Budget')


)



-- below are UNION(ing) FORMATTED_BUDGET cte result & UNION_TRANSFORMATION result
,FINAL_UNION AS(

    (SELECT 
    "PARTNER_TYPE", 
    "CAMPAIGN_CHILD", 
    CAST("SUM_OF_MDF_FUNDED" AS VARCHAR(18)) AS "SUM_OF_MDF_FUNDED", 
    CAST("YEAR_QUARTER" AS VARCHAR(2011)) AS "YEAR_QUARTER", 
    "YEAR_QUARTER_DATE", 
    "MDP_GATE_QUARTER", 
    "PMM", 
    "PARTNER_MANAGER", 
    "GEO", 
    CAST("MATURITY" AS VARCHAR(2000)) AS "MATURITY", 
    "SUB_REGION", 
    "COUNTRY", 
    "GTM_TIER", 
    "TIER", 
    "PARTNER_NAME", 
    "CSN", 
    "CAMPAIGN_INDUSTRY", 
    "CAMPAIGN_PARENT", 
    "FR_NAME", 
    "FR_ACTIVITY_NAME", 
    "ACTIVITY_TYPE", 
    "ACTIVITY_NAME", 
    CAST("ACTIVITY_BEGIN_DATE" AS VARCHAR(10)) AS "ACTIVITY_BEGIN_DATE", 
    CAST("SUM_OF_NBR_ATTENDEES" AS VARCHAR(38)) AS "SUM_OF_NBR_ATTENDEES", 
    CAST("SUM_OF_NBR_OF_COMPLETED_TM_CALLS" AS VARCHAR(38)) AS "SUM_OF_NBR_OF_COMPLETED_TM_CALLS", 
    CAST("SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS" AS VARCHAR(38)) AS "SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS", 
    CAST("SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS" AS VARCHAR(38)) AS "SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS", 
    "MQLS", 
    "SUM_OF_EXPECTED_NBR_ATTENDEES", 
    "SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS", 
    "SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS", 
    "C6_10_DAYS_TO_ROI_DEADLINE", 
    "LAST_5_DAYS_TO_ROI_DEADLINE", 
    "ROI_DEADLINE_OVER", 
    "ROI_COMPLETED", 
    "GEP_EVENT_ID", 
    CAST("ACTIVITY_END_DATE" AS VARCHAR(10)) AS "ACTIVITY_END_DATE", 
    "MARKETING_REGION", 
    "FOCUS_PARTNER", 
    "SPEND_TYPE", 
    CAST("METRIC_NAME" AS VARCHAR(6)) AS "METRIC_NAME", 
    CAST("SUM_OF_METRIC_VALUE" AS VARCHAR) AS "SUM_OF_METRIC_VALUE", 
    "PLAN_STATUS", 
    "PLAN_APPROVER", 
    "PLAN_APPROVED_AMOUNT", 
    "TARGET_COUNTRY", 
    "ENGAGEMENT_COMPLETE", 
    "CLAIM_AUDIT_STATUS", 
    "CLAIM_BY_DATE", 
    "CLAIM_SUBMITTED_DATE", 
    "PLAN_SUBMISSION_DATE", 
    "SUBMISSION_GATE_COMPLIANT", 
    "CAMPAIGN", 
    "CAMPAIGN_TYPE", 
    "RR_STATUS", 
    "FR_APPROVED_AMOUNT_LC", 
    "FR_DESCRIPTION", 
    "REPORT_CREATE_DATE", 
    "RR_HOLD_REASON", 
    "RR_HOLD_DATE", 
    "RR_LAST_DATE_UPDATED", 
    "RR_EXTERNAL_COMMENTS", 
    "RR_INTERNAL_COMMENTS" 
    FROM -- ($T{SQL 3})
        UNION_TRANSFORMATION
    ) 

    UNION ALL 

    (SELECT 
    CAST("PARTNER_TYPE" AS VARCHAR(2000)) AS "PARTNER_TYPE", 
    "CAMPAIGN_CHILD", 
    CAST("SUM_OF_MDF_FUNDED" AS VARCHAR(18)) AS "SUM_OF_MDF_FUNDED", 
    "YEAR_QUARTER", 
    "YEAR_QUARTER_DATE", 
    "MDP_GATE_QUARTER", 
    "PMM", 
    CAST("PARTNER_MANAGER" AS VARCHAR(256)) AS "PARTNER_MANAGER", 
    "GEO", 
    "MATURITY", 
    "SUB_REGION", 
    CAST("COUNTRY" AS VARCHAR(256)) AS "COUNTRY", 
    CAST("GTM_TIER" AS VARCHAR(2000)) AS "GTM_TIER", 
    CAST("TIER" AS VARCHAR(256)) AS "TIER", 
    CAST("PARTNER_NAME" AS VARCHAR(2000)) AS "PARTNER_NAME", 
    CAST("CSN" AS VARCHAR(256)) AS "CSN", 
    CAST("CAMPAIGN_INDUSTRY" AS VARCHAR(256)) AS "CAMPAIGN_INDUSTRY", 
    "CAMPAIGN_PARENT", 
    CAST("FR_NAME" AS VARCHAR(256)) AS "FR_NAME", 
    "FR_ACTIVITY_NAME", 
    CAST("ACTIVITY_TYPE" AS VARCHAR(256)) AS "ACTIVITY_TYPE", 
    CAST("ACTIVITY_NAME" AS VARCHAR(512)) AS "ACTIVITY_NAME", 
    CAST("ACTIVITY_BEGIN_DATE" AS VARCHAR(10)) AS "ACTIVITY_BEGIN_DATE", 
    CAST("SUM_OF_NBR_ATTENDEES" AS VARCHAR(38)) AS "SUM_OF_NBR_ATTENDEES", 
    CAST("SUM_OF_NBR_OF_COMPLETED_TM_CALLS" AS VARCHAR(38)) AS "SUM_OF_NBR_OF_COMPLETED_TM_CALLS", 
    CAST("SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS" AS VARCHAR(38)) AS "SUM_OF_NBR_OF_DIRECT_EMAIL_CLICKS", 
    CAST("SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS" AS VARCHAR(38)) AS "SUM_OF_NBR_OF_ONLINE_MEDIA_CLICKS", 
    "MQLS", 
    "SUM_OF_EXPECTED_NBR_ATTENDEES", 
    "SUM_OF_EXPECTED_NBR_OF_COMPLETED_TM_CALLS", 
    "SUM_OF_EXPECTED_NBR_OF_ONLINE_MEDIA_CLICKS", 
    CAST("C6_10_DAYS_TO_ROI_DEADLINE" AS VARCHAR(256)) AS "C6_10_DAYS_TO_ROI_DEADLINE", 
    CAST("LAST_5_DAYS_TO_ROI_DEADLINE" AS VARCHAR(256)) AS "LAST_5_DAYS_TO_ROI_DEADLINE", 
    CAST("ROI_DEADLINE_OVER" AS VARCHAR(256)) AS "ROI_DEADLINE_OVER", 
    CAST("ROI_COMPLETED" AS VARCHAR(256)) AS "ROI_COMPLETED", 
    CAST("GEP_EVENT_ID" AS VARCHAR(256)) AS "GEP_EVENT_ID", 
    CAST("ACTIVITY_END_DATE" AS VARCHAR(10)) AS "ACTIVITY_END_DATE", 
    CAST("MARKETING_REGION" AS VARCHAR(256)) AS "MARKETING_REGION", 
    "FOCUS_PARTNER", 
    CAST("SPEND_TYPE" AS VARCHAR(256)) AS "SPEND_TYPE", 
    "METRIC_NAME", 
    CAST("SUM_OF_METRIC_VALUE" AS VARCHAR) AS "SUM_OF_METRIC_VALUE", 
    "PLAN_STATUS", 
    "PLAN_APPROVER", 
    "PLAN_APPROVED_AMOUNT", 
    "TARGET_COUNTRY", 
    CAST("ENGAGEMENT_COMPLETE" AS VARCHAR(2)) AS "ENGAGEMENT_COMPLETE", 
    "CLAIM_AUDIT_STATUS", 
    "CLAIM_BY_DATE", 
    "CLAIM_SUBMITTED_DATE", 
    "PLAN_SUBMISSION_DATE", 
    "SUBMISSION_GATE_COMPLIANT", 
    "CAMPAIGN", 
    CAST("CAMPAIGN_TYPE" AS VARCHAR(256)) AS "CAMPAIGN_TYPE", 
    "RR_STATUS", 
    "FR_APPROVED_AMOUNT_LC", 
    "FR_DESCRIPTION", 
    "REPORT_CREATE_DATE", 
    "RR_HOLD_REASON", 
    "RR_HOLD_DATE", 
    "RR_LAST_DATE_UPDATED", 
    "RR_EXTERNAL_COMMENTS", 
    "RR_INTERNAL_COMMENTS" 
    FROM -- ($T{FORMATTED_BUDGET})
            FORMATTED_BUDGET
    )
)

SELECT * FROM FINAL_UNION


