-- airflow Dag which regulates this model: 
-- dir: mdp_360/mdp_i360_new_dag 
-- dag: mdp_i360_new_trg

-- Get the right stack database properties.
{% set db_properties=get_dbproperties('MDP_I360_NEW') %}


-- Set the database properties.
{{ config(database=db_properties['database'], schema=db_properties['schema']) }}

-- Setting the Materialization.
{{ config(
        materialized='table'
) }}

-- set the right tags.
{{ config(tags=[var('TAG_MDP_I360_NEW'),var('TAG_MDP_I360_NEW_RENAME_COLS')
]) }}





WITH RENAME_COLUMNS AS (

  SELECT 
  "FUNDNAME" AS "FUND_NAME", 
  "PLANID" AS "PLAN_ID", 
  "PLANDETAILID", 
  "CUSTOMERID" AS "CUSTOMER_ID", 
  "CUSTOMERNAME", 
  "AREA", 
  "REGION", 
  "COUNTRY", 
  "PLANSTATUS" AS "PLAN_STATUS", 
  "PLANAPPROVER" AS "PLAN_APPROVER", 
  "PLANAPPROVEDREIMBURSEMENTAMOUNTCONVERTEDTOUSD" AS "PLAN_APPROVED_REIMBURSEMENT_AMOUNT_CONVERTED_TO_USD", 
  "PLANAPPROVEDREIMBURSEMENTAMOUNTLC" AS "PLAN_APPROVED_REIMBURSEMENT_AMOUNT_LC", 
  "ACTIVITYBEGINDATE" AS "ACTIVITY_BEGIN_DATE", 
  "ACTIVITYENDDATE" AS "ACTIVITY_END_DATE", 
  "QUARTEROFACTIVITYENDDATE" AS "QUARTEROF_ACTIVITY_END_DATE", 
  "ACTIVITY", 
  "PUBLICATIONNAME" AS "PUBLICATION_NAME", 
  "PLANDESCRIPTION" AS "PLAN_DESCRIPTION", 
  "PLANSUBMITTEDYEAR" AS "PLAN_SUBMITTED_YEAR", 
  "PLANSUBMITTEDMONTH" AS "PLAN_SUBMITTED_MONTH", 
  "PLANSUBMITTEDQUARTER" AS "PLAN_SUBMITTED_QUARTER", 
  "PLANSUBMISSIONDATE" AS "PLAN_SUBMISSION_DATE", 
  "REPORTCREATEDATE" AS "REPORT_CREATE_DATE", 
  "CLAIMBYDATE" AS "CLAIM_BY_DATE", 
  "CLAIMSUBMITTEDDATE" AS "CLAIM_SUBMITTED_DATE", 
  "CLAIMAUDITSTATUS" AS "CLAIM_AUDIT_STATUS", 
  "PRIMARY_TARGET_GEO", 
  "CAMPAIGN", 
  "CAMPAIGN NAME" AS "CAMPAIGN_NAME", 
  "CAMPAIGN PERCENTAGE" AS "CAMPAIGN_PERCENTAGE", 
  "ACTIVITY_MQLS_EXPECTED_EXPECTED_NUMBER_OF_MARKETING_QUALIFIED_LEADS", 
  "ACTIVITY_MQLS_ACTUAL_ACTUAL_NUMBER_OF_MARKETING_QULIFIED_LEADS", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_CLICKS", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_CLICKS", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_COMPLETED_TELEMARKETING_CALLS", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_A_LIVE", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_EVENT_ATTENDEES_NUMBER_OF_PEOPLE_WHO_ATTENDED_AN_ONLINE", 
  "CLAIMNUMBER" AS "CLAIM_NUMBER", 
  "PLANINVESTMENTAMOUNTCONVERTEDTOUSD" AS "COMBINED_INVESTMENT", 
  "HOLD/DENY REASON" AS "RR_HOLD_REASON", 
  "HELDDATE" AS "RR_HOLD_DATE", 
  "LASTDATECLAIMUPDATED" AS "RR_LAST_DATE_UPDATED", 
  "CLAIMEXTERNALCOMMENTS" AS "RR_EXTERNAL_COMMENTS", 
  "CLAIMINTERNALCOMMENTS" AS "RR_INTERNAL_COMMENTS", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_EXPECTED_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS", 
  "ACTIVITY_CUSTOMER_ENGAGEMENTS_ACTUAL_NUMBER_OF_ONLINE_MEDIA_IMPRESSIONS", 
  "PLANEXTERNALCOMMENTS" 

FROM -- ($T{MDP_I360_RAW})
    --BSM_ETL.MDF.MDP_I360_RAW
    {{ ref('MDP_I360_RAW') }} 

)



SELECT *
      ,'20'||RIGHT(LEFT(REPLACE(FUND_NAME,' ',''),6),2)||'Q'||LEFT(FUND_NAME,1) as YEAR_QUARTER
      ,CASE WHEN CLAIM_AUDIT_STATUS IS NULL THEN ' ' ELSE CLAIM_AUDIT_STATUS END AS "ClaimAuditStatus_new"
      ,CASE WHEN CLAIM_AUDIT_STATUS = 'Pending Claim' THEN 'Pending Results Review'
            WHEN CLAIM_AUDIT_STATUS = 'Approved Claim' THEN 'Results Report Approved'
            WHEN CLAIM_AUDIT_STATUS = 'Draft Claim' THEN 'Results Report Draft'
            WHEN CLAIM_AUDIT_STATUS = 'Held for Documents' THEN 'Results Report Held' 
            WHEN CLAIM_AUDIT_STATUS = 'Documents Submitted' THEN 'Results Report Re-submitted'
            WHEN CLAIM_AUDIT_STATUS = 'Denied Claim' THEN 'Results Report Denied'
            WHEN CLAIM_AUDIT_STATUS = 'Voided' THEN 'Results Report Voided'
            WHEN CLAIM_AUDIT_STATUS = 'Cancelled' THEN 'Results Report Cancelled'
        ELSE NULL END AS RR_STATUS
        
       ,CASE WHEN UPPER(CAMPAIGN_NAME) LIKE '%AEC%' THEN 'AEC'
             WHEN UPPER(CAMPAIGN_NAME) LIKE '%AUTOCAD%' THEN 'AUTOCAD'
             WHEN UPPER(CAMPAIGN_NAME) LIKE '%D&M%' THEN 'D&M'
             WHEN UPPER(CAMPAIGN_NAME) LIKE '%M&E%' THEN 'M&E'
             WHEN UPPER(CAMPAIGN_NAME) LIKE '%X-INDUSTRY%' THEN 'X-INDUSTRY'
             WHEN UPPER(CAMPAIGN_NAME) LIKE '%GFP%' THEN 'GFP'
        ELSE NULL END AS CAMPAIGN_INDUSTRY

      ,CASE WHEN REGEXP_COUNT(CAMPAIGN_NAME, '_')>1 
              THEN LEFT(CAMPAIGN_NAME,regexp_instr(CAMPAIGN_NAME, '_[^_]',1,2)-1) 
              ELSE CAMPAIGN_NAME
        END AS CAMPAIGN_PARENT
      ,CAMPAIGN_NAME AS CAMPAIGN_CHILD
        
    FROM RENAME_COLUMNS

    WHERE FUND_NAME NOT LIKE 'Re-branding Opex (non MDP)%' AND (
    (UPPER(PLAN_STATUS) IN ('ROUTED FOR APPROVAL') 
    AND COALESCE(PLAN_APPROVER,'') <> '') 
    OR UPPER(PLAN_STATUS) IN ('APPROVED','APPROVED WITH EXCEPTION','CLAIMED FOR PAYMENT','DRAFT CLAIM','PAID')
    OR UPPER(PLAN_STATUS) LIKE ('%READY FOR PAYMENT%'))
    AND NOT (
    ( CLAIM_NUMBER = '10390' and PLANDETAILID in ('102') )
    or ( CLAIM_NUMBER = '11140' and PLANDETAILID in ('102', '106', '116', '118', '125', '130', '131', '132', '133', '134', '135', '138', '139', '140', '143', '144', '145', '146', '147', '148', '318', '332', '333', '334', '335') )
    or ( CLAIM_NUMBER = '12230' and PLANDETAILID in ('236') )
    or ( CLAIM_NUMBER = '11200' and PLANDETAILID in ('433', '434', '435') )
    or ( CLAIM_NUMBER = '13370' and PLANDETAILID in ('518') )
    or ( CLAIM_NUMBER = '14870' and PLANDETAILID in ('711', '712', '713', '714', '715') )
    or ( CLAIM_NUMBER = '17510' and PLANDETAILID in ('1373', '1374', '1366', '1420', '1364', '1368') )
    or ( CLAIM_NUMBER = '16570' and PLANDETAILID in ('1787') )
    or ( CLAIM_NUMBER = '31600' and PLANDETAILID in ('2637') )
    or ( CLAIM_NUMBER = '30000' and PLANDETAILID in ('2909') )
    or ( CLAIM_NUMBER = '20920' and PLANDETAILID in ('3185') )
    or ( CLAIM_NUMBER = '19240' and PLANDETAILID in ('3759') )

)